force-app/main/default/objects/Client_Follow_up__c/Client_Follow_up__c.object-meta.xml
<CustomObject>
    <description>A follow-up process that re-engages ET clients if they completed a business registration, consultation or training event.</description>
    <label>Client Follow-Up</label>
    <nameField>
        <displayFormat>CLF-{0000}</displayFormat>
        <label>Client Follow-up Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Follow-Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Follow_up__c/fields/Account_ClientFollowUp__c.field-meta.xml
<CustomField>
    <fullName>Account_ClientFollowUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Follow-Ups</relationshipLabel>
    <relationshipName>Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/fields/Campaign_ID__c.field-meta.xml
<CustomField>
    <fullName>Campaign_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If they have a record that created or modified this object, it would be linked to via this object.</description>
    <label>Campaign ID</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Client Follow-Ups</relationshipLabel>
    <relationshipName>Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/fields/Contact_ClientFollowUp__c.field-meta.xml
<CustomField>
    <fullName>Contact_ClientFollowUp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Follow-Ups</relationshipLabel>
    <relationshipName>Client_Follow_Ups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/fields/ET_Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Engagement_Type__c</fullName>
    <label>ET Engagement Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/fields/Work_Flow_Session__c.field-meta.xml
<CustomField>
    <fullName>Work_Flow_Session__c</fullName>
    <description>Identifies what record type is driving the work flow.</description>
    <label>Work Flow Session</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClientFollowUpsForCampaignTests.cls
@isTest
public class ClientFollowUpsForCampaignTests {
    static testMethod void validateUpdate() {
        Account a = new Account(Name = 'TestAccount', RecordTypeId='012o0000000Gb8K');
        insert a;
        
        Contact c = new Contact();
        c.Email = 'test@testmail.com';
        c.AccountId = a.Id;
        c.LastName = 'Test';
        insert c;
        
        Campaign ca = new Campaign(Name='ET-Event Test', Type='Training (ET)');
        ca.IsActive = False;
        ca.Status = 'Completed';
        insert ca;
        
        CampaignMember cm = new CampaignMember();
        cm.CampaignId = ca.Id;
        cm.ContactId = c.Id;
        insert cm;
        
        //cm.Street = '1111111';
        update cm;
        
        // Retrieve the new Client_Follow_up__c
        /*
        Client_Follow_up__c cf = [SELECT ET_Engagement_Type__c, Work_Flow_Session__c FROM Client_Follow_up__c WHERE Contact_ClientFollowUp__c =: c.Id];
        
        System.assertEquals('Training', cf.ET_Engagement_Type__c);
        System.assertEquals('Training', cf.Work_Flow_Session__c);
        */
    }
    
    static testMethod void validateInsert1() {
        Account a = new Account(Name = 'TestAccount', RecordTypeId='012o0000000Gb8K');
        insert a;
        
        Contact c = new Contact();
        c.Email = 'test@testmail.com';
        c.AccountId = a.Id;
        c.LastName = 'Test';
        insert c;
        
        Client_Follow_up__c cf = new Client_Follow_up__c();
        cf.Contact_ClientFollowUp__c = c.Id;
        cf.Account_ClientFollowUp__c = a.Id;
        insert cf;
        
        Campaign ca = new Campaign(Name='ET-Event Test', Type='Training (ET)');
        ca.IsActive = False;
        ca.Status = 'Completed';
        insert ca;
        
        CampaignMember cm = new CampaignMember();
        cm.CampaignId = ca.Id;
        cm.ContactId = c.Id;
        insert cm;
        
        // Retrieve the new Client_Follow_up__c
        /*
        cf = [SELECT Campaign_ID__c, Contact_ClientFollowUp__c, ET_Engagement_Type__c, Work_Flow_Session__c FROM Client_Follow_up__c WHERE Campaign_ID__c =: ca.Id];
        
        System.assertEquals(ca.Id, cf.Campaign_ID__c);
        System.assertEquals(c.Id, cf.Contact_ClientFollowUp__c);
        System.assertEquals('Training', cf.ET_Engagement_Type__c);
        System.assertEquals('Training', cf.Work_Flow_Session__c);  
        */ 
    }
    
    static testMethod void validateInsert2() {
        Account a = new Account(Name = 'TestAccount', RecordTypeId='012o0000000Gb8K');
        insert a;
        
        Contact c = new Contact();
        c.Email = 'test@testmail.com';
        c.AccountId = a.Id;
        c.LastName = 'Test';
        insert c;
        
        Campaign ca = new Campaign(Name='ET-Event Test', Type='Training (ET)');
        ca.IsActive = False;
        ca.Status = 'Completed';
        insert ca;
        
        CampaignMember cm = new CampaignMember();
        cm.CampaignId = ca.Id;
        cm.ContactId = c.Id;
        insert cm;
        
        // Retrieve the new Client_Follow_up__c
        /*
        Client_Follow_up__c cf = [SELECT Campaign_ID__c, Contact_ClientFollowUp__c, ET_Engagement_Type__c, Work_Flow_Session__c FROM Client_Follow_up__c WHERE Campaign_ID__c =: ca.Id];
        
        //System.assertEquals(cm.Id, cf.Campaign_ID__c);
        System.assertEquals(c.Id, cf.Contact_ClientFollowUp__c);
        System.assertEquals('Training', cf.ET_Engagement_Type__c);
        System.assertEquals('Training', cf.Work_Flow_Session__c);
        */
    }
    
}