force-app/main/default/objects/Campaign/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investment Activity Programs</relationshipLabel>
    <relationshipName>Investment_Activity_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Mapping_Custom_Setting__c/Campaign_Mapping_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CampaignMappingCustomSetting</label>
</CustomObject>

force-app/main/default/objects/Campaign_Mapping_Custom_Setting__c/fields/CampaignRecordId__c.field-meta.xml
<CustomField>
    <fullName>CampaignRecordId__c</fullName>
    <label>CampaignRecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Starter_Company_Clients__c/Starter_Company_Clients__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s grant management module for the Starter Company Program.</description>
    <label>Starter Company</label>
    <nameField>
        <displayFormat>SC-{YYYY}-{00000000}</displayFormat>
        <label>Starter Company Acct</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Starter Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Starter_Company_Clients__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Starter_Company_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Starter_Company_Clients__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Starter_Company_Clients</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Starter_Company_Clients__c/fields/Phase_1_Application_Approved__c.field-meta.xml
<CustomField>
    <fullName>Phase_1_Application_Approved__c</fullName>
    <label>Phase #1 - Application Approved</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Training Deferred</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Starter_Company_Clients__c/fields/Phase_2_GrantApproved__c.field-meta.xml
<CustomField>
    <fullName>Phase_2_GrantApproved__c</fullName>
    <label>Phase #2 - Grant Committee Approved</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Starter_Company_Clients__c/fields/Program_Completed__c.field-meta.xml
<CustomField>
    <fullName>Program_Completed__c</fullName>
    <label>Program Completed</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddClientsToCampaign_Test.cls
@isTest(seeAllData=false)
public class AddClientsToCampaign_Test
{
     Static testMethod Void checkClientAddition()
     {
         Campaign camp = new Campaign(Name='Stage#1');
         insert camp;
         
         Campaign_Mapping_Custom_Setting__c Cmap = new Campaign_Mapping_Custom_Setting__c(Name='Stage#1',CampaignRecordId__c = camp.ID);
         insert Cmap; 
         
         Campaign camp2 = new Campaign(Name='GrantRecipient');
         insert camp2;
         
         Campaign_Mapping_Custom_Setting__c Cmap2 = new Campaign_Mapping_Custom_Setting__c(Name='Grant Recipient',CampaignRecordId__c = camp2.ID);
         insert Cmap2; 
         
         Campaign camp3 = new Campaign(Name='Graduate');
         insert camp3;
         
         Campaign_Mapping_Custom_Setting__c Cmap3 = new Campaign_Mapping_Custom_Setting__c(Name='Graduate',CampaignRecordId__c = camp3.ID);
         insert Cmap3; 
        
        
         
         Account acct = new Account(Name='City Of Toronto');
         insert acct;
         
         Contact firstCon = new Contact(LastName='Ray', AccountID = acct.ID, Email='test@cityoftoronto.com');
         insert firstCon;
         
         Starter_Company_Clients__c sc = new Starter_Company_Clients__c(Account__c = acct.ID, Contact__c = firstCon.ID, Phase_1_Application_Approved__c= 'yes');
         insert sc;
         
         Starter_Company_Clients__c upsc =[Select id, Phase_1_Application_Approved__c,Phase_2_GrantApproved__c,Program_Completed__c from Starter_Company_Clients__c where Id =: sc.Id];
         upsc.Program_Completed__c ='yes';
         update upsc;
         
         
         /*****************************************************************************************************************/
         Account acct1 = new Account(Name='Enterprise Toronto');
         insert acct1;
         
         Contact SecCon = new Contact(LastName='Kim', AccountID = acct1.ID, Email='test@toronto.com');
         insert  SecCon;
         
         
         Starter_Company_Clients__c sc2 = new Starter_Company_Clients__c(Account__c = acct.ID, Contact__c = SecCon.ID, Phase_2_GrantApproved__c = 'yes');
         insert sc2;
         
         Starter_Company_Clients__c upsc2 =[Select id, Phase_1_Application_Approved__c,Phase_2_GrantApproved__c,Program_Completed__c from Starter_Company_Clients__c where Id =: sc2.Id];
         upsc2.Phase_1_Application_Approved__c ='Yes';
         update upsc2;
         
       /*****************************************************************************************************************/
         Account acct2 = new Account(Name='Toronto Canada');
         insert acct2;
         
         Contact ThirdCon = new Contact(LastName='Kim', AccountID = acct2.ID, Email='test@toronto.ca');
         insert ThirdCon ;
         
         
         Starter_Company_Clients__c sc3 = new Starter_Company_Clients__c(Account__c = acct2.ID, Contact__c = ThirdCon.ID, Program_Completed__c ='yes');
         insert sc3;
         
         Starter_Company_Clients__c upsc3 =[Select id, Program_Completed__c,Phase_2_GrantApproved__c from Starter_Company_Clients__c where Id =: sc3.Id];
         upsc3.Phase_2_GrantApproved__c= 'Yes';
         update upsc3;
     }
    
}