force-app/main/default/objects/Campaign/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <inlineHelpText>Business Support - Supporting external organizations and their events.
Networking Events -Track attendees at networking events delivered by EDC.
Business Training-Track attendees at training sessions delivered by EDC.</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Event Support</fullName>
            </value>
            <value>
                <fullName>Networking Events</fullName>
            </value>
            <value>
                <fullName>Business Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/International_Project_Type__c.field-meta.xml
<CustomField>
    <fullName>International_Project_Type__c</fullName>
    <label>International Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outbound Mission</fullName>
            </value>
            <value>
                <fullName>Inbound Mission</fullName>
            </value>
            <value>
                <fullName>International Relationships</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Program_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Sub_Type__c</fullName>
    <label>Business Training Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Event_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>International Events</fullName>
            </value>
            <value>
                <fullName>Business Start Up</fullName>
            </value>
            <value>
                <fullName>Business Expansion</fullName>
            </value>
            <value>
                <fullName>Online Training</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Projects</fullName>
            </value>
            <value>
                <fullName>Project Support (BIA)</fullName>
            </value>
            <value>
                <fullName>International Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Events.recordType-meta.xml
<RecordType>
    <fullName>Events</fullName>
    <active>true</active>
    <description>For tracking work on external event projects where the City is providing support in organizing.</description>
    <label>Events</label>
</RecordType>

force-app/main/default/objects/Campaign/recordTypes/Group_Management.recordType-meta.xml
<RecordType>
    <fullName>Group_Management</fullName>
    <active>true</active>
    <description>Groups associated with economic development projects, including advisory bodies and stakeholders.</description>
    <label>Group Management</label>
</RecordType>

force-app/main/default/objects/Campaign/recordTypes/Investment_Activity.recordType-meta.xml
<RecordType>
    <fullName>Investment_Activity</fullName>
    <active>true</active>
    <description>Project of Investment Activity type</description>
    <label>Investment Activity</label>
</RecordType>

force-app/main/default/objects/Campaign/recordTypes/Projects.recordType-meta.xml
<RecordType>
    <fullName>Projects</fullName>
    <active>true</active>
    <description>Projects that are being developed and implemented to support the business community.</description>
    <label>Projects</label>
</RecordType>

force-app/main/default/objects/CampaignMember/fields/Initiative_Status__c.field-meta.xml
<CustomField>
    <fullName>Initiative_Status__c</fullName>
    <description>This field is referred in trigger Logic to map the value from its parent Initiative and will not be exposed on UI</description>
    <label>Initiative Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Survey_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Start_Date__c</fullName>
    <label>Survey Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CampaignMember/recordTypes/Business_Training_Campaign_Member.recordType-meta.xml
<RecordType>
    <fullName>Business_Training_Campaign_Member</fullName>
    <active>true</active>
    <description>This Program Member Type should be selected for Event Program Record Type</description>
    <label>Business Training Program Member</label>
</RecordType>

force-app/main/default/objects/CampaignMember/recordTypes/International_Program_Member.recordType-meta.xml
<RecordType>
    <fullName>International_Program_Member</fullName>
    <active>true</active>
    <description>This Program Member Type should be selected for Event Program Record Type and applicable to International Business</description>
    <label>International Program Member</label>
</RecordType>

force-app/main/default/objects/CampaignMember/recordTypes/Mission_Campaign_Member.recordType-meta.xml
<RecordType>
    <fullName>Mission_Campaign_Member</fullName>
    <active>true</active>
    <description>This Program Member Type should be selected for Project Program Record Type</description>
    <label>Mission Program Member</label>
</RecordType>

force-app/main/default/classes/CampaignTriggerActions.cls
public class CampaignTriggerActions{
    public static void updateCampaignMemberRecordType(List<Campaign> newCampaignList,Map<Id,Campaign> oldCampaignMap){
        Map<String,String> recTypeNameIDMap = new Map<String,String>();
        for(RecordType recType:[SELECT DeveloperName,Id,Name,SobjectType FROM RecordType WHERE (SobjectType = 'CampaignMember' OR SobjectType = 'Campaign')]){
            recTypeNameIDMap.put(recType.DeveloperName,recType.Id);
        }
        Set<String> projectTypeSet = new Set<String>{'Business Start Up','Business Expansion','Online Training'};
        for(Campaign camp: newCampaignList){
            system.debug('camp++'+camp);
            if(camp.RecordTypeId == recTypeNameIDMap.get('Events') && (projectTypeSet.contains(camp.Program_Sub_Type__c) || camp.Event_Type__c=='Networking Events'))
                camp.CampaignMemberRecordTypeId = recTypeNameIDMap.get('Business_Training_Campaign_Member');
            if(camp.RecordTypeId == recTypeNameIDMap.get('Events') && camp.Program_Sub_Type__c=='International Events' )
                camp.CampaignMemberRecordTypeId = recTypeNameIDMap.get('International_Program_Member');
            if(camp.RecordTypeId == recTypeNameIDMap.get('Projects') && camp.Project_Type__c=='International Project' && camp.International_Project_Type__c=='Outbound Mission' )
                camp.CampaignMemberRecordTypeId = recTypeNameIDMap.get('Mission_Campaign_Member');
        }    
        //Below Logic for updating related Campaign Member Record Survey Start Date
        Map<String,Campaign> camMap = new Map<String,Campaign>(); 
        List<CampaignMember> camMemList = new List<CampaignMember>();
        for(Campaign camp: newCampaignList){
            if(((camp.EndDate!=null && oldCampaignMap!=null && camp.EndDate!=oldCampaignMap.get(camp.Id).EndDate) || (camp.EndDate!=null && oldCampaignMap==null) || (camp.Status!=null && camp.Status=='Completed' && oldCampaignMap!=null && camp.Status!=oldCampaignMap.get(camp.Id).Status) || (camp.Status!=null && camp.Status=='Completed' && oldCampaignMap==null)) && camp.RecordTypeId != recTypeNameIDMap.get('Group_Management') && camp.RecordTypeId != recTypeNameIDMap.get('Investment_Activity')){
                camMap.put(camp.Id,camp); 
            }
        }
        system.debug('camMap+++'+camMap);
        for(CampaignMember camMem: [SELECT Id, Survey_Start_Date__c, CampaignId, Campaign.Program_Sub_Type__c FROM CampaignMember WHERE CampaignId IN: camMap.keySet() AND Campaign.Program_Sub_Type__c!='Online Training']){
            system.debug('camMem+++'+camMem);
            if(camMem.Survey_Start_Date__c!= camMap.get(camMem.CampaignId).EndDate || camMap.get(camMem.CampaignId).Status == 'Completed'){
                camMem.Survey_Start_Date__c = camMap.get(camMem.CampaignId).EndDate;
                if(camMap.get(camMem.CampaignId).Status == 'Completed'){
                    camMem.Initiative_Status__c = 'Completed';
                }   
                camMemList.add(camMem);                 
            }
        }
        if(camMemList!=null){
            Database.update(camMemList);
        }
    }
    public static void updateCampaignActiveCheck(List<Campaign> newCampaignList){
        for(Campaign camp: newCampaignList){
            if(camp.IsActive== false)
            camp.IsActive= true;
        }
    }
}