force-app/main/default/objects/Financial_Incentive__c/Financial_Incentive__c.object-meta.xml
<CustomObject>
    <description>This object will be used to build various grant process within salesforce application to various department like ES, BIA and BGS</description>
    <label>Financial Incentive</label>
    <nameField>
        <displayFormat>FIN-{YYYY}-{000000}</displayFormat>
        <label>Financial Incentive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Incentives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Incentive__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Incentives</relationshipLabel>
    <relationshipName>Financial_Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Amount_Approved__c.field-meta.xml
<CustomField>
    <fullName>Amount_Approved__c</fullName>
    <description>Manager should specify the value before Approving Grant Request</description>
    <inlineHelpText>Manager should specify the value before Approving Grant Request</inlineHelpText>
    <label>Amount Approved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Application_Extension_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Extension_Date__c</fullName>
    <description>This date will be approved by Approver if extension is requested but should not be later than one year after Expiry date.</description>
    <inlineHelpText>This date will be approved by Approver if extension is requested but should not be later than one year after Expiry date.</inlineHelpText>
    <label>Grant Extension Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/BIC_Report_Trigger_Date__c.field-meta.xml
<CustomField>
    <fullName>BIC_Report_Trigger_Date__c</fullName>
    <description>This date is Read Only field that will be Nov 15th every year and year will be automatically assigned based on BIC Grant Completion Status date.</description>
    <inlineHelpText>This date is Read Only field that will be Nov 15th every year and year will be automatically assigned based on BIC Grant Completion Status date.</inlineHelpText>
    <label>BIC Report Trigger Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/City_Council_s_Approval_Doc_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>City_Council_s_Approval_Doc_Uploaded__c</fullName>
    <description>For IMIT grant that requires city council approval i.e. greater than 150M grant can only be Approved if City council&#39;s approval document has been uploaded.</description>
    <inlineHelpText>For IMIT grant that requires city council approval i.e. greater than 150M grant can only be Approved if City council&#39;s approval document has been uploaded.</inlineHelpText>
    <label>City Council&#39;s Approval Doc Uploaded</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Financial Incentives</relationshipLabel>
    <relationshipName>Financial_Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Financial_Incentive_Name__c.field-meta.xml
<CustomField>
    <fullName>Financial_Incentive_Name__c</fullName>
    <description>This is a read only field used to store unique Record Name with Auto-number based on Record Type</description>
    <inlineHelpText>This is a read only field used to store unique Record Name with Auto-number based on Record Type</inlineHelpText>
    <label>Unique Identifier Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Has_No_Conflict_Doc_Uploaded_EDC_GM__c.field-meta.xml
<CustomField>
    <fullName>Has_No_Conflict_Doc_Uploaded_EDC_GM__c</fullName>
    <description>If there are No Conflict than EDC GM should upload the document before Approving IMIT Application.</description>
    <inlineHelpText>If there are No Conflict than EDC GM should upload the document before Approving IMIT Application.</inlineHelpText>
    <label>Has No Conflict Doc Uploaded(EDC GM)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>No_Conflict_of_Interest_EDC_GM__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/No_Conflict_of_Interest_EDC_GM__c.field-meta.xml
<CustomField>
    <fullName>No_Conflict_of_Interest_EDC_GM__c</fullName>
    <description>EDC GM who is reviewing the application required to specify the value.</description>
    <inlineHelpText>EDC GM who is reviewing the application required to specify the value.</inlineHelpText>
    <label>No Conflict of Interest (EDC GM)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Property_Street__c.field-meta.xml
<CustomField>
    <fullName>Property_Street__c</fullName>
    <description>Property Street Address</description>
    <inlineHelpText>Property Street Address</inlineHelpText>
    <label>Property Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Record_Submitter__c.field-meta.xml
<CustomField>
    <fullName>Record_Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Record Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Financial_Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <description>Reason specified for Declined Status</description>
    <inlineHelpText>Reason specified for Declined Status</inlineHelpText>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>More Information Required</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Pending Extension</fullName>
            </value>
            <value>
                <fullName>Extension Approved</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved by GM</fullName>
            </value>
            <value>
                <fullName>Approved by City Council</fullName>
            </value>
            <value>
                <fullName>With Legal</fullName>
            </value>
            <value>
                <fullName>Legal Agreement Completed</fullName>
            </value>
            <value>
                <fullName>Reassessment</fullName>
            </value>
            <value>
                <fullName>Amending Agreement</fullName>
            </value>
            <value>
                <fullName>Compliance/Payment Review</fullName>
            </value>
            <value>
                <fullName>Withdrawn/Inactive</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Application Declined</fullName>
            </value>
            <value>
                <fullName>Extension Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Eligibility Criteria not Met</fullName>
            </value>
            <value>
                <fullName>Interview Required</fullName>
            </value>
            <value>
                <fullName>Declined after Interview</fullName>
            </value>
            <value>
                <fullName>Approved for Training</fullName>
            </value>
            <value>
                <fullName>Declined for Training</fullName>
            </value>
            <value>
                <fullName>Training Completed</fullName>
            </value>
            <value>
                <fullName>Business Plan Received</fullName>
            </value>
            <value>
                <fullName>Score Card Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/BIA_Commercial_Industrial_Facade_and_Property_Improvement.recordType-meta.xml
<RecordType>
    <fullName>BIA_Commercial_Industrial_Facade_and_Property_Improvement</fullName>
    <active>true</active>
    <description>This type is specifically applicable to BIA Commercial - Industrial Facade and Property Improvement for BIA Accounts</description>
    <label>BIA Commercial - Industrial Facade and Property Improvement</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/BIA_Innovation_Fund.recordType-meta.xml
<RecordType>
    <fullName>BIA_Innovation_Fund</fullName>
    <active>true</active>
    <description>This type is specifically applicable to BIA Innovation Fund and Property Improvement for BIA Accounts</description>
    <label>BIA Innovation Fund</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/BIA_Leadership_Fund.recordType-meta.xml
<RecordType>
    <fullName>BIA_Leadership_Fund</fullName>
    <active>true</active>
    <description>This type is specifically applicable to BIA Leadership Fund and Property Improvement for BIA Accounts</description>
    <label>BIA Leadership Fund</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/BIA_Outside_Mural_and_Street_Art_Grant.recordType-meta.xml
<RecordType>
    <fullName>BIA_Outside_Mural_and_Street_Art_Grant</fullName>
    <active>true</active>
    <description>This type is specifically applicable to BIA Outside Mural and Street Art Grant and Property Improvement for BIA Accounts</description>
    <label>BIA Outside Mural and Street Art</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/BIA_Streetscape_Master_Plan_Funding.recordType-meta.xml
<RecordType>
    <fullName>BIA_Streetscape_Master_Plan_Funding</fullName>
    <active>true</active>
    <description>This type is specifically applicable to BIA Streetscape Master Plan Funding and Property Improvement for BIA Accounts</description>
    <label>BIA Streetscape Master Plan Funding</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/Business_Incubation_Grant.recordType-meta.xml
<RecordType>
    <fullName>Business_Incubation_Grant</fullName>
    <active>true</active>
    <description>This type is used for creating Grant records applicable only for Business Incubation i.e. a grant to a business incubator.</description>
    <label>Business Incubation Grant</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/Event_Sponsorship_Grant.recordType-meta.xml
<RecordType>
    <fullName>Event_Sponsorship_Grant</fullName>
    <active>true</active>
    <description>This type is used for creating Grant records applicable only for Event Sponsorship for an external event focused on the business community</description>
    <label>Event Sponsorship Grant</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/IMIT.recordType-meta.xml
<RecordType>
    <fullName>IMIT</fullName>
    <active>true</active>
    <description>This is used for creating Financial Incentive of IMIT Type</description>
    <label>IMIT</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/Sector_Grant.recordType-meta.xml
<RecordType>
    <fullName>Sector_Grant</fullName>
    <active>true</active>
    <description>This Record type is only applicable to various Grant related to sector like Event. Project and Membership</description>
    <label>Sector Grant</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/Starter_Company_Grant.recordType-meta.xml
<RecordType>
    <fullName>Starter_Company_Grant</fullName>
    <active>true</active>
    <description>Applicable to Starter Company Program</description>
    <label>Starter Company Grant</label>
</RecordType>

force-app/main/default/classes/FinancialIncentiveTriggerActions.cls
public class FinancialIncentiveTriggerActions{
    public static void validateRejectionReason( List<Financial_Incentive__c> newFinancialIncentiveList, Map<ID, Financial_Incentive__c> oldFinancialIncentiveMap){
        Map<Id, Financial_Incentive__c> rejectedStatements = new Map<Id, Financial_Incentive__c>{};
        Map<Id, Financial_Incentive__c> approvedAmountMap = new Map<Id, Financial_Incentive__c>{};
        Map<Id, Financial_Incentive__c> imitApprovedMap = new Map<Id, Financial_Incentive__c>{};
        Map<Id, Financial_Incentive__c> imitCityCounApprovedMap = new Map<Id, Financial_Incentive__c>{};
        Map<String,String> recTypeNameIDMap = new Map<String,String>();
        for(RecordType recType:[SELECT DeveloperName,Id,Name,SobjectType FROM RecordType WHERE SobjectType = 'Financial_Incentive__c']){
            recTypeNameIDMap.put(recType.DeveloperName,recType.Id);
        }
        
        if(oldFinancialIncentiveMap!=null){
        for(Financial_Incentive__c inv: newFinancialIncentiveList){
                /* 
                  Get the old object record, and check if the approval status 
                  field has been updated to rejected. If so, put it in a map 
                  so we only have to use 1 SOQL query to do all checks.
                */
                system.debug('inside update loop');
                Financial_Incentive__c oldInv = oldFinancialIncentiveMap.get(inv.Id);

                //Below condition to capture the Financial Incentive Record Ids for which Grant request has been declined
                if ((oldInv.Status__c != 'Declined'  && inv.Status__c == 'Declined')|| (oldInv.Status__c != 'Application Declined'  && inv.Status__c == 'Application Declined')){ 
                    rejectedStatements.put(inv.Id, inv);  
                    system.debug('rejectedStatements++++'+rejectedStatements);
                }
                
                //Below condition to capture the Financial Incentive Record Ids that has no Amount Approved value specified
                if(oldInv.Status__c != 'Approved'  && inv.Status__c == 'Approved' && inv.RecordTypeId==recTypeNameIDMap.get('Sector_Grant') && inv.Amount_Approved__c==null){ 
                    approvedAmountMap.put(inv.Id, inv);  
                }
                
                //Below condition to capture the IMIT Financial Incentive Record Ids that has been Approved without specifying No Conflict
                if(oldInv.Status__c != 'Approved by GM'  && inv.Status__c == 'Approved by GM' && inv.RecordTypeId==recTypeNameIDMap.get('IMIT') && (inv.Has_No_Conflict_Doc_Uploaded_EDC_GM__c!='Yes' || inv.No_Conflict_of_Interest_EDC_GM__c!='Yes')){ 
                    imitApprovedMap.put(inv.Id, inv);  
                }
                
                //Below condition to capture the IMIT Financial Incentive Record Ids that has been Approved without specifying if Approval Document from City Council has been Uploaded
                if(oldInv.Status__c != 'Approved by City Council'  && inv.Status__c == 'Approved by City Council' && inv.RecordTypeId==recTypeNameIDMap.get('IMIT') && inv.City_Council_s_Approval_Doc_Uploaded__c != 'Yes'){ 
                    imitCityCounApprovedMap.put(inv.Id, inv);  
                }
                
                //Below logic will assign current user as Record Submitter
                if (oldInv.Status__c != 'Pending Approval'  && inv.Status__c == 'Pending Approval'){ 
                    inv.Record_Submitter__c = UserInfo.getUserId();  
                }
                system.debug('invRecord_Submitter__c ++++'+inv.Record_Submitter__c );
                
                //Below Logic will Update the Financial Incentive Records owner from  Queue to Current User when Status changes to In Review for all record type except Sector   
                if (oldInv.Status__c == 'Submitted' && inv.Status__c == 'In Review' && inv.RecordTypeId!=recTypeNameIDMap.get('Sector_Grant')){ 
                    inv.OwnerId = UserInfo.getUserId();  
                }
                
                //Below code block is to update the Event Report Date for BIC Grant Records once status has been completed
                if (inv.Status__c == 'Completed' && oldFinancialIncentiveMap.get(inv.Id).Status__c != 'Completed' && inv.RecordTypeId==recTypeNameIDMap.get('Business_Incubation_Grant')){ 
                    Integer currentYear = System.Today().year();
                    Integer nextYear = currentYear+1;
                    Date currentYearDate = Date.newInstance(currentYear, 11, 15);
                    Date nextYearDate = Date.newInstance(nextYear, 11, 15);
                    if(currentYearDate.addDays(1)>date.today()){
                        inv.BIC_Report_Trigger_Date__c = currentYearDate;
                    }
                    else{
                        inv.BIC_Report_Trigger_Date__c = nextYearDate;
                    }
                }
            }
        }
        if (!rejectedStatements.isEmpty()){
            // Get the most recent approval process instance for the object.
            // If there are some approvals to be reviewed for approval, then
            // get the most recent process instance for each object.
            List<Id> processInstanceIds = new List<Id>{};
            for (Financial_Incentive__c invs : [SELECT Rejection_Reason__c,Id, (SELECT ID
                                                FROM ProcessInstances
                                                ORDER BY CreatedDate DESC
                                                LIMIT 1)
                                                FROM Financial_Incentive__c
                                                WHERE ID IN :rejectedStatements.keySet() AND Rejection_Reason__c='' ]){
                if(invs.ProcessInstances.size()>0)
                processInstanceIds.add(invs.ProcessInstances[0].Id);
            }

            // Now that we have the most recent process instances, we can check
            // the most recent process steps for comments.  
            for (ProcessInstance pi : [SELECT TargetObjectId,
                                        (SELECT Id, StepStatus, Comments 
                                        FROM Steps
                                        ORDER BY CreatedDate DESC
                                        LIMIT 1 )
                                        FROM ProcessInstance
                                        WHERE Id IN :processInstanceIds
                                        ORDER BY CreatedDate DESC]){                   
                rejectedStatements.get(pi.TargetObjectId).addError('Operation Cancelled: Please provide a Rejection Reason!');
            }
        }
       
        if (!approvedAmountMap.isEmpty()){
            List<Id> processApprovedAmountInstanceIds = new List<Id>{};
            for (Financial_Incentive__c invs : [SELECT Rejection_Reason__c,Application_Extension_Date__c,Id, (SELECT ID
                                                FROM ProcessInstances
                                                ORDER BY CreatedDate DESC
                                                LIMIT 1)
                                                FROM Financial_Incentive__c
                                                WHERE ID IN :approvedAmountMap.keySet()]){
                if(invs.ProcessInstances.size()>0)
                processApprovedAmountInstanceIds.add(invs.ProcessInstances[0].Id);
            }

            for (ProcessInstance piAppAm : [SELECT TargetObjectId,
                                        (SELECT Id, StepStatus, Comments 
                                        FROM Steps
                                        ORDER BY CreatedDate DESC
                                        LIMIT 1 )
                                        FROM ProcessInstance
                                        WHERE Id IN :processApprovedAmountInstanceIds
                                        ORDER BY CreatedDate DESC]){                   
                approvedAmountMap.get(piAppAm.TargetObjectId).addError('Operation Cancelled: Please specify Amount Approved before Approval');
            }
        }
        if (!imitApprovedMap.isEmpty()){
            List<Id> processIMITApprovedInstanceIds = new List<Id>{};
            for (Financial_Incentive__c invs : [SELECT Has_No_Conflict_Doc_Uploaded_EDC_GM__c, No_Conflict_of_Interest_EDC_GM__c,Id, (SELECT ID                                 FROM ProcessInstances
                                                ORDER BY CreatedDate DESC
                                                LIMIT 1)
                                                FROM Financial_Incentive__c
                                                WHERE ID IN :imitApprovedMap.keySet()]){
                if(invs.ProcessInstances.size()>0)
                processIMITApprovedInstanceIds.add(invs.ProcessInstances[0].Id);
            }

            for (ProcessInstance piAppAm : [SELECT TargetObjectId,
                                        (SELECT Id, StepStatus, Comments 
                                        FROM Steps
                                        ORDER BY CreatedDate DESC
                                        LIMIT 1 )
                                        FROM ProcessInstance
                                        WHERE Id IN :processIMITApprovedInstanceIds
                                        ORDER BY CreatedDate DESC]){                   
                imitApprovedMap.get(piAppAm.TargetObjectId).addError('Operation Cancelled: Please specify you have No Conflict of Interest and uploaded its document before Approval');
            }
        }
        if (!imitCityCounApprovedMap.isEmpty()){
            List<Id> processIMITCityCouApprovedInstanceIds = new List<Id>{};
            for (Financial_Incentive__c invs : [SELECT City_Council_s_Approval_Doc_Uploaded__c, Id, (SELECT ID                                 FROM ProcessInstances
                                                ORDER BY CreatedDate DESC
                                                LIMIT 1)
                                                FROM Financial_Incentive__c
                                                WHERE ID IN :imitCityCounApprovedMap.keySet()]){
                if(invs.ProcessInstances.size()>0)
                processIMITCityCouApprovedInstanceIds.add(invs.ProcessInstances[0].Id);
            }

            for (ProcessInstance piAppAm : [SELECT TargetObjectId,
                                        (SELECT Id, StepStatus, Comments 
                                        FROM Steps
                                        ORDER BY CreatedDate DESC
                                        LIMIT 1 )
                                        FROM ProcessInstance
                                        WHERE Id IN :processIMITCityCouApprovedInstanceIds
                                        ORDER BY CreatedDate DESC]){                   
                imitCityCounApprovedMap.get(piAppAm.TargetObjectId).addError('Operation Cancelled: IMIT Application can not be Approved without uploading City Council Approval Document');
            }
        }
    }
    public static void validateAccountRelationOnFinancialIncentive( List<Financial_Incentive__c> newFinancialIncentiveList){
        Map<Id, Set<String>> accountToRelatedContacts = new Map<Id, Set<String>>();
        Set<Id> accIdSet = new Set<Id>();
        Set<Id> contIdSet = new Set<Id>();
        Set<Id> busAccountIdSet = new Set<Id>();
        Set<Id> busContIdSet = new Set<Id>();
         
        for(Financial_Incentive__c finInc: newFinancialIncentiveList){
            accIdSet.add(finInc.Account__c);
            contIdSet.add(finInc.Contact__c);
        }
        if(accIdSet!=null){
            for(Account acc: [SELECT ID,Name,IsPersonAccount From Account WHERE ID IN:accIdSet]){
                if(!acc.IsPersonAccount)
                busAccountIdSet.add(acc.Id);
            }
        }   
        if(contIdSet!=null){
        for(Contact con: [SELECT ID,LastName,IsPersonAccount From Contact WHERE ID IN:contIdSet]){
                if(!con.IsPersonAccount)
                busContIdSet.add(con.Id);
            }
        }
        if(busAccountIdSet!=null || busContIdSet!=null){
            for(AccountContactRelation accCon: [SELECT Id, AccountId, ContactId FROM AccountContactRelation WHERE AccountId IN: busAccountIdSet OR ContactId IN: busContIdSet]){
                if(!accountToRelatedContacts.containsKey(accCon.AccountId)){
                    accountToRelatedContacts.put(accCon.AccountId, new Set<String>{accCon.ContactId});
                    system.debug('++accountToRelatedContactsinside++'+accountToRelatedContacts);
                }else{
                    accountToRelatedContacts.get(accCon.AccountId).add(accCon.ContactId);
                }
            }
            for(Financial_Incentive__c finIncVal: newFinancialIncentiveList){
                system.debug('++finIncVal++'+finIncVal);
                if(finIncVal.Account__c!=null && finIncVal.Contact__c!=null && busAccountIdSet.contains(finIncVal.Account__c) && busContIdSet.contains(finIncVal.Contact__c) && (!accountToRelatedContacts.containsKey(finIncVal.Account__c) || (accountToRelatedContacts.containsKey(finIncVal.Account__c) && !accountToRelatedContacts.get(finIncVal.Account__c).contains(finIncVal.Contact__c)))){
                    finIncVal.adderror('IMIT Account and IMIT Contact are not related to each other');
                }
            }
        }
    }
    public static void updateFinancialIncentiveNameCustom(List<Financial_Incentive__c> newFinancialIncentiveList){
        List<Financial_Incentive__c> lstToUpdate = new List<Financial_Incentive__c>();
        Map<String,String> recTypeNameIDMap = new Map<String,String>();
        for(RecordType recType:[SELECT DeveloperName,Id,Name,SobjectType FROM RecordType WHERE SobjectType = 'Financial_Incentive__c']){
            recTypeNameIDMap.put(recType.DeveloperName,recType.Id);
        }
        for(Financial_Incentive__c fInc: [SELECT Id, Name, Property_Street__c,Financial_Incentive_Name__c,RecordTypeId,Account__c,Account__r.Name FROM Financial_Incentive__c WHERE ID IN: newFinancialIncentiveList]){
            if(fInc.Name!=null){
                List<String> lsName = fInc.Name.split('-',3);
                System.debug('lsName+++'+lsName);
                String autoNumber = lsName[2];
                if(fInc.RecordTypeId==recTypeNameIDMap.get('BIA_Commercial_Industrial_Facade_and_Property_Improvement')){
                    fInc.Financial_Incentive_Name__c = 'FIN-CFI-'+System.Today().year()+'-'+autoNumber;
                }
                if(fInc.RecordTypeId==recTypeNameIDMap.get('BIA_Innovation_Fund')){
                    fInc.Financial_Incentive_Name__c = 'FIN-INO-'+System.Today().year()+'-'+autoNumber;
                }
                if(fInc.RecordTypeId==recTypeNameIDMap.get('BIA_Leadership_Fund')){
                    fInc.Financial_Incentive_Name__c = 'FIN-LDR-'+System.Today().year()+'-'+autoNumber;
                }
                if(fInc.RecordTypeId==recTypeNameIDMap.get('BIA_Outside_Mural_and_Street_Art_Grant')){
                    fInc.Financial_Incentive_Name__c = 'FIN-OMS-'+System.Today().year()+'-'+autoNumber;
                }
                if(fInc.RecordTypeId==recTypeNameIDMap.get('BIA_Streetscape_Master_Plan_Funding')){
                    fInc.Financial_Incentive_Name__c = 'FIN-SMP-'+System.Today().year()+'-'+autoNumber;
                }
                if(fInc.RecordTypeId==recTypeNameIDMap.get('Business_Incubation_Grant')){
                    fInc.Financial_Incentive_Name__c = 'FIN-OPG-'+System.Today().year()+'-'+autoNumber;
                }
                if(fInc.RecordTypeId==recTypeNameIDMap.get('Event_Sponsorship_Grant')){
                    fInc.Financial_Incentive_Name__c = 'FIN-EVT-'+System.Today().year()+'-'+autoNumber;
                }
                if(fInc.RecordTypeId==recTypeNameIDMap.get('Sector_Grant')){
                    fInc.Financial_Incentive_Name__c = 'FIN-SEC-'+System.Today().year()+'-'+autoNumber;
                }
                if(fInc.RecordTypeId==recTypeNameIDMap.get('Starter_Company_Grant')){
                    fInc.Financial_Incentive_Name__c = 'FIN-STR-'+System.Today().year()+'-'+autoNumber;
                }
                if(fInc.RecordTypeId==recTypeNameIDMap.get('IMIT')){
                    if(fInc.Property_Street__c!=null){
                        fInc.Financial_Incentive_Name__c = 'FIN-IMIT-'+System.Today().year()+'-'+fInc.Property_Street__c+'-'+autoNumber;
                    }else{
                    fInc.Financial_Incentive_Name__c = 'FIN-IMIT-'+System.Today().year()+'-'+autoNumber;
                        
                    }
                }
                
                lstToUpdate.add(fInc);
            }           
        }
        if(lstToUpdate.size()>0){
            Database.update(lstToUpdate);
        }
   }
}