force-app/main/default/objects/Financial_Incentive__c/Financial_Incentive__c.object-meta.xml
<CustomObject>
    <description>This object will be used to build various grant process within salesforce application to various department like ES, BIA and BGS</description>
    <label>Financial Incentive</label>
    <nameField>
        <displayFormat>FIN-{YYYY}-{000000}</displayFormat>
        <label>Financial Incentive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Incentives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Incentive__c/fields/Financial_Incentive_Name__c.field-meta.xml
<CustomField>
    <fullName>Financial_Incentive_Name__c</fullName>
    <description>This is a read only field used to store unique Record Name with Auto-number based on Record Type</description>
    <inlineHelpText>This is a read only field used to store unique Record Name with Auto-number based on Record Type</inlineHelpText>
    <label>Unique Identifier Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Pending Extension</fullName>
            </value>
            <value>
                <fullName>Extension Approved</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved by GM</fullName>
            </value>
            <value>
                <fullName>Approved by City Council</fullName>
            </value>
            <value>
                <fullName>With Legal</fullName>
            </value>
            <value>
                <fullName>Legal Agreement Completed</fullName>
            </value>
            <value>
                <fullName>Reassessment</fullName>
            </value>
            <value>
                <fullName>Amending Agreement</fullName>
            </value>
            <value>
                <fullName>Compliance/Payment Review</fullName>
            </value>
            <value>
                <fullName>Withdrawn/Inactive</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Application Declined</fullName>
            </value>
            <value>
                <fullName>Extension Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Eligibility Criteria not Met</fullName>
            </value>
            <value>
                <fullName>Interview Required</fullName>
            </value>
            <value>
                <fullName>Declined after Interview</fullName>
            </value>
            <value>
                <fullName>Approved for Training</fullName>
            </value>
            <value>
                <fullName>Declined for Training</fullName>
            </value>
            <value>
                <fullName>Training Completed</fullName>
            </value>
            <value>
                <fullName>Business Plan Received</fullName>
            </value>
            <value>
                <fullName>Score Card Received</fullName>
            </value>
            <value>
                <fullName>Document Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FinIncStarterCompanyInboundEmail.cls
/**
* @File Name:  FinIncStarterCompanyInboundEmail.cls
* @Description:   Email Logging Integration
* Provides an entry point to manage the inbound emails sent to Email Service and attach to Financial Incentive Record
* @Author:    Manish 
* @Group:     Apex
* @Last Modified by:   Manish Gaur
* @Last Modified time: 2019-09-09
* @Modification Log  :
*-------------------------------------------------------------------------------------
* Ver       Date        Author         Modification
* 1.0       2019-09-09  Manish Gaur    Created the file/class
* 1.1       2019-11-18  DZ             Change inserting Note to ContentNot for Lightning Conversion
*/
global class FinIncStarterCompanyInboundEmail implements Messaging.InboundEmailHandler {
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email,
                                                    Messaging.InboundEnvelope envelope) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
        String emailSubject = email.subject;
        String startrCompRecord = 'FIN'+ (emailSubject.substringAfter('FIN')).substring(0,16);
        Financial_Incentive__c finRecord ;
        List<ContentDocumentLink> contentFileList = new List<ContentDocumentLink>();
        
        try{
            if(startrCompRecord!=null && startrCompRecord.length()==19){
                
                //Get the Starter Company Record based on unique record Name
                finRecord = [SELECT Id,Status__c,Financial_Incentive_Name__c FROM Financial_Incentive__c WHERE Financial_Incentive_Name__c=:startrCompRecord];
                
                if(finRecord!=null){
                    
                    finRecord.Status__c='Document Received';
                    update finRecord;
                          

                    ContentNote cnt = new ContentNote();
                    cnt.Content = Blob.valueOf(email.htmlBody);
                    cnt.Title = 'Email From -'+email.fromAddress + ' (' + DateTime.now() + ')';
                    insert cnt;

                    ContentDocumentLink clnk = new ContentDocumentLink();
                    clnk.LinkedEntityId = finRecord.Id;
                    clnk.ContentDocumentId = cnt.Id;
                    clnk.ShareType = 'I';
                    insert clnk;
                    
                    /*
                    Note note = new Note();
                    note.Title = 'Email From -'+email.fromAddress + ' (' + DateTime.now() + ')';
                    note.Body = email.plainTextBody;
                    note.ParentId = finRecord.Id;
                    insert note;
                    */

                    // Save any Text Attachment
                    if(email.textAttachments!=null && email.textAttachments.size()>0) {
                        for (Messaging.Inboundemail.TextAttachment tAttachment : email.textAttachments) {
                            ContentVersion cv = new ContentVersion();
                            cv.VersionData =  Blob.valueOf(tAttachment.body);
                            cv.Title = tAttachment.fileName;
                            cv.PathOnClient = tAttachment.fileName;
                            insert cv;
                     
                            cv = [select ContentDocumentId from ContentVersion where id = :cv.id limit 1];
                            ContentDocumentLink cdl1 = new ContentDocumentLink();
                            cdl1.LinkedEntityId = finRecord.Id;
                            cdl1.ContentDocumentId = cv.ContentDocumentId;
                            cdl1.ShareType = 'V';
                            contentFileList.add(cdl1);
                        }
                    }
                    //Save any Binary Attachment
                    if(email.binaryAttachments!=null){
                        for (Messaging.Inboundemail.BinaryAttachment bAttachment : email.binaryAttachments) {
                            if(bAttachment.body.size()>0){
                                ContentVersion cv = new ContentVersion();
                                cv.VersionData = bAttachment.body;
                                cv.Title = bAttachment.fileName;
                                cv.PathOnClient = bAttachment.fileName;
                                insert cv;
                         
                                cv = [select ContentDocumentId from ContentVersion where id = :cv.id limit 1];
                                ContentDocumentLink cdl2 = new ContentDocumentLink();
                                cdl2.LinkedEntityId = finRecord.Id;
                                cdl2.ContentDocumentId = cv.ContentDocumentId;
                                cdl2.ShareType = 'V';
                                contentFileList.add(cdl2);
                            }
                        }
                    }
                }
                if(!contentFileList.isEmpty()){
                    insert contentFileList;
                }
           }
        }
        catch (Exception e) {
            result.success = false;
            result.message = 'Relevant Starter Company Record not Found : '+e.getMessage();
        }
        return result;
    }
}