force-app/main/default/objects/Financial_Incentive__c/Financial_Incentive__c.object-meta.xml
<CustomObject>
    <description>This object will be used to build various grant process within salesforce application to various department like ES, BIA and BGS</description>
    <label>Financial Incentive</label>
    <nameField>
        <displayFormat>FIN-{YYYY}-{000000}</displayFormat>
        <label>Financial Incentive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Incentives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Incentive__c/fields/Application_Stream__c.field-meta.xml
<CustomField>
    <fullName>Application_Stream__c</fullName>
    <label>Application Stream</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Creative Arts</fullName>
            </value>
            <value>
                <fullName>DMS - Expansion</fullName>
            </value>
            <value>
                <fullName>DMS - New</fullName>
            </value>
            <value>
                <fullName>Fashion Venture</fullName>
            </value>
            <value>
                <fullName>Fashion Your Future</fullName>
            </value>
            <value>
                <fullName>Food Venture - New</fullName>
            </value>
            <value>
                <fullName>Food Venture - Original</fullName>
            </value>
            <value>
                <fullName>Ontario Works</fullName>
            </value>
            <value>
                <fullName>SC - Founder Institute</fullName>
            </value>
            <value>
                <fullName>SC - Helix</fullName>
            </value>
            <value>
                <fullName>Starter Company - General</fullName>
            </value>
            <value>
                <fullName>Starter Company - Original</fullName>
            </value>
            <value>
                <fullName>StarterSpace @Crossways</fullName>
            </value>
            <value>
                <fullName>Summer Company</fullName>
            </value>
            <value>
                <fullName>SC - Startup Boost</fullName>
            </value>
            <value>
                <fullName>SC - TorontoStarts</fullName>
            </value>
            <value>
                <fullName>SC - Music</fullName>
            </value>
            <value>
                <fullName>Starter Company Retail Accel Program</fullName>
                <default>true</default>
                <label>Starter Company Retail Accel Program</label>
            </value>
            <value>
                <fullName>Female Founders Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Customer_Retention_and_Experience__c.field-meta.xml
<CustomField>
    <fullName>Customer_Retention_and_Experience__c</fullName>
    <label>Customer Retention and Experience</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Financial_Management__c.field-meta.xml
<CustomField>
    <fullName>Financial_Management__c</fullName>
    <label>Financial Management</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Inventory_Management_and_Supply_Chain__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Management_and_Supply_Chain__c</fullName>
    <label>Inventory Management and Supply-Chain</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Managing_Staff__c.field-meta.xml
<CustomField>
    <fullName>Managing_Staff__c</fullName>
    <label>Managing Staff</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Market_Research_and_Value_Proposition__c.field-meta.xml
<CustomField>
    <fullName>Market_Research_and_Value_Proposition__c</fullName>
    <label>Market Research and Value Proposition</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Program_Specific_Question_and_Answers__c.field-meta.xml
<CustomField>
    <fullName>Program_Specific_Question_and_Answers__c</fullName>
    <label>Program Specific Question and Answers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Store_Design_and_Merchandising__c.field-meta.xml
<CustomField>
    <fullName>Store_Design_and_Merchandising__c</fullName>
    <label>Store Design and Merchandising</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/COT_BusinessPlanDatahandler.cls
public with sharing class COT_BusinessPlanDatahandler {

    public static string RETAILPROGRAM = 'Starter Company Retail Accel Program';

    @AuraEnabled(cacheable=true)
    public static List<QuestionAndAnswerSection> GetQuestionAndAnswers(string incentiveId){

        system.debug('incentiveId:' + incentiveId);

        List<QuestionAndAnswerSection> rtn = new List<QuestionAndAnswerSection>();
        Financial_Incentive__c  fi = [SELECT id,Market_Research_and_Value_Proposition__c,Financial_Management__c,
            Inventory_Management_and_Supply_Chain__c,Customer_Retention_and_Experience__c,Managing_Staff__c,
            Store_Design_and_Merchandising__c,Program_Specific_Question_And_Answers__c,Application_Stream__c from Financial_Incentive__c where Id = :incentiveId];

        String type='Financial_Incentive__c';

        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType leadSchema = schemaMap.get(type);
        Map<String, Schema.SObjectField> fieldMap = leadSchema.getDescribe().fields.getMap();


        QuestionAndAnswerSection sectionData = new QuestionAndAnswerSection();
        sectionData.Name = 'Business Plan';

        List<QuestionAndAnswer> questionAndAnswers =  new List<QuestionAndAnswer>();

        QuestionAndAnswer newQA = new QuestionAndAnswer();

        
        newQA = new QuestionAndAnswer();
        newQA.Question = fieldMap.get('Market_Research_and_Value_Proposition__c').getDescribe().getLabel();
        newQA.Answer = fi.Market_Research_and_Value_Proposition__c;
        questionAndAnswers.add(newQA);

        newQA = new QuestionAndAnswer();
        newQA.Question = fieldMap.get('Financial_Management__c').getDescribe().getLabel();
        newQA.Answer = fi.Financial_Management__c;
        questionAndAnswers.add(newQA);

        if (fi.Application_Stream__c == RETAILPROGRAM)
         {   

            newQA = new QuestionAndAnswer();
            newQA.Question = fieldMap.get('Customer_Retention_and_Experience__c').getDescribe().getLabel();
            newQA.Answer = fi.Customer_Retention_and_Experience__c;
            questionAndAnswers.add(newQA);

            newQA = new QuestionAndAnswer();
            newQA.Question = fieldMap.get('Managing_Staff__c').getDescribe().getLabel();
            newQA.Answer = fi.Managing_Staff__c;
            questionAndAnswers.add(newQA);

            newQA = new QuestionAndAnswer();
            newQA.Question = fieldMap.get('Inventory_Management_and_Supply_Chain__c').getDescribe().getLabel();
            newQA.Answer = fi.Inventory_Management_and_Supply_Chain__c;
            questionAndAnswers.add(newQA);
        
            newQA = new QuestionAndAnswer();
            newQA.Question = fieldMap.get('Store_Design_and_Merchandising__c').getDescribe().getLabel();
            newQA.Answer = fi.Store_Design_and_Merchandising__c;
            questionAndAnswers.add(newQA);
        }


        if (string.isNotEmpty(fi.Program_Specific_Question_And_Answers__c))
        {

            try {
                
                List<Map<string,List<Map<string,string>>>> finallist = (List<Map<string,List<Map<string,string>>>>)JSON.deserialize(fi.Program_Specific_Question_And_Answers__c, List<Map<string,List<Map<string,string>>>>.class);

                for (Map<string,List<Map<string,string>>> sectionMap : finallist)
                {

                    for (string sectionName : sectionMap.keySet())
                    {
                        
                        List<Map<string,string>> sectionList = sectionMap.get(sectionName);

                        for (Map<string,string> mp : sectionList)
                        {
                            for (string key : mp.keySet())
                            {
                                newQA = new QuestionAndAnswer();
                                newQA.Question = key;
                                newQA.Answer = EncodingUtil.urlDecode(mp.get(key), 'UTF-8');
                                questionAndAnswers.add(newQA);
                            }
                        }
                        
                    }

                }

            } catch (System.Exception ex) {
                
            }
        }

        sectionData.QuestionAndAnswers = questionAndAnswers;

        rtn.add(sectionData);

        system.debug('rtn:' + rtn);
        return rtn;
    }

    public class QuestionAndAnswerSection
    {
        @AuraEnabled
        public string Name;

        @AuraEnabled
        public List<QuestionAndAnswer> QuestionAndAnswers;
    }

    public class QuestionAndAnswer
    {
        @AuraEnabled
        public string Question;

        @AuraEnabled
        public string Answer;

        @AuraEnabled
        public string Type;
    }
}