force-app/main/default/objects/Consultation__c/Consultation__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s client sign-in and follow-up module.</description>
    <label>Consultation</label>
    <nameField>
        <displayFormat>C-{YYYY}-{00000000}</displayFormat>
        <label>Consultation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultation__c/fields/Business_Status__c.field-meta.xml
<CustomField>
    <fullName>Business_Status__c</fullName>
    <label>Business Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation__c/fields/Contact_Consultation__c.field-meta.xml
<CustomField>
    <fullName>Contact_Consultation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consultations</relationshipLabel>
    <relationshipName>Consultations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consultation__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/Consultation_Follow_up__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s client consultation follow-up module.  Used to track clients who come back to ET for services.</description>
    <label>Consultation Follow-up</label>
    <nameField>
        <displayFormat>CF-{000000000}</displayFormat>
        <label>Consultation Follow-Up Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultation Follow-ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <label>Advisors</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vikas Jain</fullName>
            </value>
            <value>
                <fullName>Sandi Koitsis-Zigomanis</fullName>
            </value>
            <value>
                <fullName>Jason Li</fullName>
            </value>
            <value>
                <fullName>Karen Keskull</fullName>
            </value>
            <value>
                <fullName>Chris Rickett</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Consultation__c.field-meta.xml
<CustomField>
    <fullName>Consultation__c</fullName>
    <label>Consultation</label>
    <referenceTo>Consultation__c</referenceTo>
    <relationshipLabel>Consultation Follow-ups</relationshipLabel>
    <relationshipName>Consultation_Follow_ups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>City Hall</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <label>Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Meeting_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Time__c</fullName>
    <label>Meeting Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Meeting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rescheduled by Advisor</fullName>
            </value>
            <value>
                <fullName>Rescheduled by Client</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JqueryDatePicker__c/JqueryDatePicker__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>JqueryDatePicker</label>
</CustomObject>

force-app/main/default/objects/JqueryDatePicker__c/fields/NoOfMonths__c.field-meta.xml
<CustomField>
    <fullName>NoOfMonths__c</fullName>
    <label>NoOfMonths</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JqueryDatePicker__c/fields/StartDateFrom__c.field-meta.xml
<CustomField>
    <fullName>StartDateFrom__c</fullName>
    <label>StartDateFrom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JqueryDatePicker__c/fields/StartDateTo__c.field-meta.xml
<CustomField>
    <fullName>StartDateTo__c</fullName>
    <label>StartDateTo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/Leave_Plan__c.object-meta.xml
<CustomObject>
    <description>This custom object is used to capture Leave Plan for various ES Users that will be checked against showing their availability for online consultations.</description>
    <label>Leave Plan</label>
    <nameField>
        <label>Leave Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Plan__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leave_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/End_of_day__c.field-meta.xml
<CustomField>
    <fullName>End_of_day__c</fullName>
    <label>End of DAY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Friday__c.field-meta.xml
<CustomField>
    <fullName>Friday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Friday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>City Hall</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Start_of_day__c.field-meta.xml
<CustomField>
    <fullName>Start_of_day__c</fullName>
    <label>Start of DAY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Thursday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tuesday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wednesday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_ScheduleMeetingCompCtrl.cls
@istest
public class Test_ScheduleMeetingCompCtrl
{
      static testmethod void createTestData1()
    {
         Account acct = new Account(Name='City Of Toronto', RecordTypeId='012o0000000Gb8K');
         insert acct;
         ID acctID = acct.ID;
         
         Contact firstCon = new Contact (LastName='Ray', AccountID = acctID, Email='test@cityoftoronto.com');
         insert firstCon;
         
         ID contactID = firstCon.ID;
         
         Consultation__c cont = new Consultation__c(Contact_Consultation__c = contactID, Business_Status__c= 'Existing',Gender__c= 'Male');
         insert cont;
         ID ConsultationID = cont.ID;
         
         List<Consultation_Follow_up__c> lstFollowup = new List<Consultation_Follow_up__c>();   
         Date myDate = Date.newInstance(2015,10,20);
         Date myDate5 = Date.newInstance(2015,10,27);
         lstFollowup.add(new Consultation_Follow_up__c(Consultation__c = ConsultationID, Meeting_Date__c = myDate, Advisor__c = 'Ankita Srivastava', Status__c ='Confirmed', Meeting_Time__c ='10',Location__c = 'City Hall'));
         lstFollowup.add(new Consultation_Follow_up__c(Consultation__c = ConsultationID, Meeting_Date__c = myDate5, Advisor__c = 'Ankita Srivastava', Status__c ='Confirmed', Meeting_Time__c ='10',Location__c = 'North York Civic Centre'));
         insert lstFollowup;
         
         Date myDate1 = Date.newInstance(2015,11,11);
         Date myDate2 = Date.newInstance(2015,10,23);
         Date myDate3 = Date.newInstance(2015,10,27);
         Date myDate4 = Date.newInstance(2015,10,28);
         
         Profile pfl = [select id from profile where name='Standard User'];     
         List<User> lstUser = new List<User>();
         
         lstUser.add(new User(alias = 'asriv', email='16sep.ankitta@gmail.com', emailencodingkey= 'UTF-8', Firstname='Ankita' ,lastname='Srivastava',languagelocalekey='en_US',localesidkey='en_US', profileid = pfl.Id,country='United States',CommunityNickname = 'u1',timezonesidkey='America/Los_Angeles',username='16sep.ankitta@gmail.com', Start_of_day__c ='09 AM', End_of_day__c = '05 PM', Monday__c = true, Tuesday__c = false, Wednesday__c = true, Thursday__c = false, Friday__c = true, Location__c = 'Scarborough Civic Centre'));
         
         lstUser.add(new User(alias = 'jli', email='jlli@toronto.ca.sandplay',emailencodingkey='UTF-8', Firstname='Ankita', lastname='Srivastava', languagelocalekey='en_US',localesidkey='en_US', profileid = pfl.Id,  country='United States',CommunityNickname = 'u2',timezonesidkey='America/Los_Angeles',username='jlli@toronto.ca.sandplay',Start_of_day__c ='09 AM', End_of_day__c = '05 PM', Monday__c = true, Tuesday__c = false, Wednesday__c = true, Thursday__c = false, Friday__c = false, Location__c = 'North York Civic Centre'));
         insert lstUser;
         
         List<Leave_Plan__c> lstLeavePlan = new List<Leave_Plan__c>();
         lstLeavePlan.add( new Leave_Plan__c(User__c =lstUser[0].Id, Start_Date__c = myDate1 , End_Date__c = myDate1 , Start_Time__c ='09 AM', End_Time__c ='03 PM'));
         lstLeavePlan.add( new Leave_Plan__c(User__c =lstUser[0].Id, Start_Date__c = myDate3 , End_Date__c = myDate4 , Start_Time__c ='09 AM', End_Time__c ='06 PM'));
         insert lstLeavePlan;
         
         JqueryDatePicker__c Jdp = new JqueryDatePicker__c(Name = 'DatePicker', NoOfMonths__c = '1', StartDateFrom__c = '', StartDateTo__c = '60');
         insert Jdp;
        
         Set<Date> NotWorkingDates = New Set<Date>();
         for(integer i=1; i <45; i++)
         {
            Datetime dt = DateTime.newInstance(System.today().adddays(i), Time.newInstance(0, 0, 0, 0));
            NotWorkingDates.add(dt.date());
         }
         
         ScheduleMeetingCompCtrl Smeet = new ScheduleMeetingCompCtrl();
         Smeet.NotWorkingDates = NotWorkingDates;
         Smeet.FollowUpEmail = cont.Contact_Consultation__r.Email; 
         Smeet.AdvisorSelected = lstUser[0].id;
         Smeet.DateSelected = '11/11/2015';
         Smeet.NoOfMonths = Jdp.NoOfMonths__c; 
         Smeet.StartDateTo = Jdp.StartDateTo__c;
         Smeet.AvailableLocations();
         Smeet.AvailableAdvisors();
         Smeet.AvailableDays();
         Smeet.AvailableTimeSlots();
         Smeet.ReScheduleMeeting();
         Smeet.Dummy();
         Smeet.FollowUpEmail = 'test@cityoftoronto.com';
         PageReference pageRef = new PageReference('/apex/ClientMeetingSchedule?email=test@cityoftoronto.com');
         Smeet.PG = pageRef;
         Test.setCurrentPage(pageRef);
         Smeet.TimeSelected = '10';
         Smeet.scheduleMeeting();  
         
         
         ScheduleMeetingCompCtrl Smeet1 = new ScheduleMeetingCompCtrl();
         Smeet1.NotWorkingDates = NotWorkingDates;
         Smeet1.FollowUpEmail = cont.Contact_Consultation__r.Email; 
         Smeet1.AdvisorSelected = lstUser[0].id;
         Smeet1.DateSelected = '11/11/2015';
         Smeet1.NoOfMonths = Jdp.NoOfMonths__c; 
         Smeet1.StartDateTo = Jdp.StartDateTo__c;
         Smeet1.AvailableLocations();
         Smeet1.AvailableAdvisors();
         Smeet1.AvailableDays();
         Smeet1.AvailableTimeSlots();
         Smeet1.ReScheduleMeeting();
         Smeet1.Dummy();
         Smeet1.FollowUpId= lstFollowup[0].Id;
         PageReference pageRef1 = new PageReference('/apex/ClientMeetingSchedule?FollowUpId='+lstFollowup[0].Id);
         Smeet1.PG = pageRef1;
         Test.setCurrentPage(pageRef1);
         Smeet1.TimeSelected = '10';
         Smeet1.scheduleMeeting();        
     }
}