force-app/main/default/objects/Consultation__c/Consultation__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s client sign-in and follow-up module.</description>
    <label>Consultation</label>
    <nameField>
        <displayFormat>C-{YYYY}-{00000000}</displayFormat>
        <label>Consultation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultation__c/fields/Business_Status__c.field-meta.xml
<CustomField>
    <fullName>Business_Status__c</fullName>
    <label>Business Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation__c/fields/Contact_Consultation__c.field-meta.xml
<CustomField>
    <fullName>Contact_Consultation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consultations</relationshipLabel>
    <relationshipName>Consultations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consultation__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/Consultation_Follow_up__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s client consultation follow-up module.  Used to track clients who come back to ET for services.</description>
    <label>Consultation Follow-up</label>
    <nameField>
        <displayFormat>CF-{000000000}</displayFormat>
        <label>Consultation Follow-Up Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultation Follow-ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <label>Advisors</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vikas Jain</fullName>
            </value>
            <value>
                <fullName>Sandi Koitsis-Zigomanis</fullName>
            </value>
            <value>
                <fullName>Jason Li</fullName>
            </value>
            <value>
                <fullName>Karen Keskull</fullName>
            </value>
            <value>
                <fullName>Chris Rickett</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Consultation__c.field-meta.xml
<CustomField>
    <fullName>Consultation__c</fullName>
    <label>Consultation</label>
    <referenceTo>Consultation__c</referenceTo>
    <relationshipLabel>Consultation Follow-ups</relationshipLabel>
    <relationshipName>Consultation_Follow_ups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>City Hall</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <label>Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Meeting_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Time__c</fullName>
    <label>Meeting Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Meeting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rescheduled by Advisor</fullName>
            </value>
            <value>
                <fullName>Rescheduled by Client</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/Leave_Plan__c.object-meta.xml
<CustomObject>
    <description>This custom object is used to capture Leave Plan for various ES Users that will be checked against showing their availability for online consultations.</description>
    <label>Leave Plan</label>
    <nameField>
        <label>Leave Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Plan__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/End_of_day__c.field-meta.xml
<CustomField>
    <fullName>End_of_day__c</fullName>
    <label>End of DAY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Friday__c.field-meta.xml
<CustomField>
    <fullName>Friday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Friday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>City Hall</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Start_of_day__c.field-meta.xml
<CustomField>
    <fullName>Start_of_day__c</fullName>
    <label>Start of DAY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Thursday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tuesday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wednesday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_UserSettingController.cls
@istest
public class Test_UserSettingController
{
    static testmethod void createTestData1()
    {
         Account acct = new Account(Name='City Of Toronto', RecordTypeId='012o0000000Gb8K');
         insert acct;
         ID acctID = acct.ID;
         
         Contact firstCon = new Contact (LastName='Ray', AccountID = acctID, Email='test@cityoftoronto.com');
         insert firstCon;
         ID contactID = firstCon.ID;
         
         Consultation__c cont = new Consultation__c(Contact_Consultation__c = contactID, Business_Status__c= 'Existing',Gender__c= 'Male');
         insert cont;
         ID ConsultationID = cont.ID;
            
         Date myDate = Date.newInstance(2015,10,17);
         Consultation_Follow_up__c Followup = new Consultation_Follow_up__c(Consultation__c = ConsultationID, Meeting_Date__c = myDate, Advisor__c = 'Vikas Jain', Status__c ='Confirmed', Meeting_Time__c ='10',Location__c = 'City Hall');
         insert Followup;
         
         Date myDate1 = Date.newInstance(2015,10,22);
         Date myDate2 = Date.newInstance(2015,10,23);
         Date myDate3 = Date.newInstance(2015,10,27);
         Date myDate4 = Date.newInstance(2015,10,28);
         
         List<Leave_Plan__c> lstLeavePlan = new List<Leave_Plan__c>();
         lstLeavePlan.add( new Leave_Plan__c(Start_Date__c = myDate1 , End_Date__c = myDate2 , Start_Time__c ='09 AM', End_Time__c ='06 PM'));
         lstLeavePlan.add( new Leave_Plan__c(Start_Date__c = myDate3 , End_Date__c = myDate4 , Start_Time__c ='09 AM', End_Time__c ='06 PM'));
         insert lstLeavePlan;
        
         
         PageReference pageRef = Page.User_Setting_Panel;
         Test.setCurrentPage(pageRef);
         
         UserSettingController usc = new UserSettingController();
         usc.AddLine();
     }
     
     
    static testmethod void createTestData2()
    {
        Profile pfl = [select id from profile where name='Standard User'];     
        
        List<User> lstUser = new List<User>();
        lstUser.add(new User(alias = 'db', email='deepabalib@mfs.com', emailencodingkey= 'UTF-8', FirstName='Ankita', lastname='Srivastava',languagelocalekey='en_US',localesidkey='en_US', profileid = pfl.Id,country='United States',CommunityNickname = 'u1',timezonesidkey='America/Los_Angeles',username='deepabaliwwww@mindfiresolutions.com', Start_of_day__c ='09 AM', End_of_day__c = '05 PM', Monday__c = true, Tuesday__c = false, Wednesday__c = true, Thursday__c = false, Friday__c = true, Location__c = 'City Hall'));
        
        lstUser.add(new User(alias = 'dbm', email='deepalib@mfs.com',emailencodingkey='UTF-8', FirstName='Ankita', lastname='Srivastava' , languagelocalekey='en_US',localesidkey='en_US', profileid = pfl.Id,  country='United States',CommunityNickname = 'u2',timezonesidkey='America/Los_Angeles',username='deepaliiiii@mindfiresolutions.com',Start_of_day__c ='09 AM', End_of_day__c = '05 PM', Monday__c = true, Tuesday__c = false, Wednesday__c = true, Thursday__c = false, Friday__c = false, Location__c = 'North York Civic Centre'));
        insert lstUser;
        
        Account acct = new Account(Name='City Of Toronto', RecordTypeId='012o0000000Gb8K');
        insert acct;
        ID acctID = acct.ID;
        
        Contact firstCon = new Contact (LastName='Ray', AccountID = acctID, Email='test@cityoftoronto.com');
        insert firstCon;
        ID contactID = firstCon.ID;
        
        Consultation__c cont = new Consultation__c(Contact_Consultation__c = contactID, Business_Status__c= 'Existing',Gender__c= 'Male');
        insert cont;
        ID ConsultationID = cont.ID;
        
        List<Consultation_Follow_up__c> lstFollowup = new List<Consultation_Follow_up__c>();   
        Date myDate = Date.newInstance(2015,10,20);
        Date myDate5 = Date.newInstance(2015,10,27);
        lstFollowup.add(new Consultation_Follow_up__c(Consultation__c = ConsultationID, Meeting_Date__c = myDate, Advisor__c = 'Ankita Srivastava', Status__c ='Confirmed', Meeting_Time__c ='10',Location__c = 'City Hall'));
        lstFollowup.add(new Consultation_Follow_up__c(Consultation__c = ConsultationID, Meeting_Date__c = myDate5, Advisor__c = 'Ankita Srivastava', Status__c ='Confirmed', Meeting_Time__c ='10',Location__c = 'North York Civic Centre'));
        insert lstFollowup;
        
        Date myDate1 = Date.newInstance(2015,10,22);
        Date myDate2 = Date.newInstance(2015,10,23);
        Date myDate3 = Date.newInstance(2015,10,27);
        Date myDate4 = Date.newInstance(2015,10,28);
        
        List<Leave_Plan__c> lstLeavePlan = new List<Leave_Plan__c>();
        lstLeavePlan.add( new Leave_Plan__c(Start_Date__c = myDate1 , End_Date__c = myDate2 , Start_Time__c ='09 AM', End_Time__c ='06 PM'));
        lstLeavePlan.add( new Leave_Plan__c(Start_Date__c = myDate3 , End_Date__c = myDate4 , Start_Time__c ='09 AM', End_Time__c ='06 PM'));
        insert lstLeavePlan;
        
        PageReference pageRef = Page.User_Setting_Panel;
        Test.setCurrentPage(pageRef);
        
        UserSettingController usc = new UserSettingController();
        usc.LoggedUserName = 'Ankita Srivastava';
        usc.Approved = true;
        usc.Rescheduled = true;
        usc.followupId = lstFollowup[0].id;
        usc.SaveLeave();
        usc.SaveWorkingHour();
        usc.SaveFollowup();
        usc.EditUser();
        usc.EditLeave();
        usc.ApprovedFollowup();
        usc.ConfirmedCustomer();
        usc.ReschdueldFollowup();
        usc.CancelWorkingHrs();
        usc.CancelLeave();
        usc.CancelFollowUp();
        usc.leaveId = lstLeavePlan[0].id;
        usc.DeleteLeave();
        
     }
}