force-app/main/default/objects/Consultation__c/Consultation__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s client sign-in and follow-up module.</description>
    <label>Consultation</label>
    <nameField>
        <displayFormat>C-{YYYY}-{00000000}</displayFormat>
        <label>Consultation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultation__c/fields/Business_Status__c.field-meta.xml
<CustomField>
    <fullName>Business_Status__c</fullName>
    <label>Business Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation__c/fields/Contact_Consultation__c.field-meta.xml
<CustomField>
    <fullName>Contact_Consultation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consultations</relationshipLabel>
    <relationshipName>Consultations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consultation__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/Consultation_Follow_up__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s client consultation follow-up module.  Used to track clients who come back to ET for services.</description>
    <label>Consultation Follow-up</label>
    <nameField>
        <displayFormat>CF-{000000000}</displayFormat>
        <label>Consultation Follow-Up Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultation Follow-ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <label>Advisors</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vikas Jain</fullName>
            </value>
            <value>
                <fullName>Sandi Koitsis-Zigomanis</fullName>
            </value>
            <value>
                <fullName>Jason Li</fullName>
            </value>
            <value>
                <fullName>Karen Keskull</fullName>
            </value>
            <value>
                <fullName>Chris Rickett</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Consultation__c.field-meta.xml
<CustomField>
    <fullName>Consultation__c</fullName>
    <label>Consultation</label>
    <referenceTo>Consultation__c</referenceTo>
    <relationshipLabel>Consultation Follow-ups</relationshipLabel>
    <relationshipName>Consultation_Follow_ups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>City Hall</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <label>Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Meeting_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Time__c</fullName>
    <label>Meeting Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Meeting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rescheduled by Advisor</fullName>
            </value>
            <value>
                <fullName>Rescheduled by Client</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_ClientMeetingScheduleCtrl.cls
@isTest

public class Test_ClientMeetingScheduleCtrl
{
    static testmethod void createTestData1()
    {
         Account acct = new Account(Name='City Of Toronto', RecordTypeId='012o0000000Gb8K');
         insert acct;
         ID acctID = acct.ID;
         
         Contact firstCon = new Contact (LastName='Ray', AccountID = acctID, Email='test@cityoftoronto.com');
         insert firstCon;
         ID contactID = firstCon.ID;
         
         Consultation__c cont = new Consultation__c(Contact_Consultation__c = contactID, Business_Status__c= 'Existing',Gender__c= 'Male');
         insert cont;
         ID ConsultationID = cont.ID;
            
         Date myDate = Date.newInstance(2015,10,17);
         Consultation_Follow_up__c Followup = new Consultation_Follow_up__c(Consultation__c = ConsultationID, Meeting_Date__c = myDate, Advisor__c = 'Vikas Jain', Status__c ='Confirmed', Meeting_Time__c ='10',Location__c = 'City Hall');
         insert Followup;
         
         PageReference pageRef = Page.ClientMeetingSchedule;
         Test.setCurrentPage(pageRef);
         ApexPages.currentPage().getParameters().put('email',firstCon.Email);
         
         ClientMeetingScheduleCtrl cmeeting = new ClientMeetingScheduleCtrl();
        
    }
    
    static testmethod void createTestData2()
    {
         Account acct = new Account(Name='City Of Toronto', RecordTypeId='012o0000000Gb8K');
         insert acct;
         ID acctID = acct.ID;
         
         Contact firstCon = new Contact (LastName='Ray', AccountID = acctID, Email='test@cityoftoronto.com');
         insert firstCon;
         ID contactID = firstCon.ID;
         
         Consultation__c cont = new Consultation__c(Contact_Consultation__c = contactID, Business_Status__c= 'Existing',Gender__c= 'Male');
         insert cont;
         ID ConsultationID = cont.ID;
            
         Date myDate = Date.newInstance(2015,10,17);
         Consultation_Follow_up__c Followup = new Consultation_Follow_up__c(Consultation__c = ConsultationID, Meeting_Date__c = myDate, Advisor__c = 'Vikas Jain', Status__c ='Requested', Meeting_Time__c ='10',Location__c = 'City Hall');
         insert Followup;
         
         PageReference pageRef = Page.ClientMeetingSchedule;
         Test.setCurrentPage(pageRef);
         ApexPages.currentPage().getParameters().put('email','');
         
         ClientMeetingScheduleCtrl cmeeting = new ClientMeetingScheduleCtrl();
        
    }
    
    
    
      static testmethod void createTestData3()
    {
         Account acct = new Account(Name='City Of Toronto', RecordTypeId='012o0000000Gb8K');
         insert acct;
         ID acctID = acct.ID;
         
         Contact firstCon = new Contact (LastName='Ray', AccountID = acctID, Email='test@cityoftoronto.com');
         insert firstCon;
         ID contactID = firstCon.ID;
         
         Consultation__c cont = new Consultation__c(Contact_Consultation__c = contactID, Business_Status__c= 'Existing',Gender__c= 'Male');
         insert cont;
         ID ConsultationID = cont.ID;
            
         Date myDate = Date.newInstance(2015,10,17);
         Consultation_Follow_up__c Followup = new Consultation_Follow_up__c(Consultation__c = ConsultationID, Meeting_Date__c = myDate, Advisor__c = 'Vikas Jain', Status__c ='Confirmed', Meeting_Time__c ='10',Location__c = 'City Hall');
         insert Followup;
         
         PageReference pageRef = Page.ClientMeetingSchedule;
         Test.setCurrentPage(pageRef);
         ApexPages.currentPage().getParameters().put('FollowRecId','');
         ClientMeetingScheduleCtrl cmeeting = new ClientMeetingScheduleCtrl();
        
    }
    
     static testmethod void createTestData4()
    {
         Account acct = new Account(Name='City Of Toronto', RecordTypeId='012o0000000Gb8K');
         insert acct;
         ID acctID = acct.ID;
         
         Contact firstCon = new Contact (LastName='Ray', AccountID = acctID, Email='test@cityoftoronto.com');
         insert firstCon;
         ID contactID = firstCon.ID;
         
         Consultation__c cont = new Consultation__c(Contact_Consultation__c = contactID, Business_Status__c= 'Existing',Gender__c= 'Male');
         insert cont;
         ID ConsultationID = cont.ID;
            
         Date myDate = Date.newInstance(2015,10,17);
         Consultation_Follow_up__c Followup = new Consultation_Follow_up__c(Consultation__c = ConsultationID, Meeting_Date__c = myDate, Advisor__c = 'Vikas Jain', Status__c ='Confirmed', Meeting_Time__c ='10',Location__c = 'City Hall');
         insert Followup;
         
         PageReference pageRef = Page.ClientMeetingSchedule;
         Test.setCurrentPage(pageRef);
         ApexPages.currentPage().getParameters().put('FollowRecId',Followup.id);
         ClientMeetingScheduleCtrl cmeeting = new ClientMeetingScheduleCtrl();
        
    }
}