force-app/main/default/objects/Client_FollowUp__c/Client_FollowUp__c.object-meta.xml
<CustomObject>
    <description>This Object is to capture the Business Outcome response against various objects like Interaction, Online Registration and Project of Event Type.</description>
    <label>Business Outcome Survey</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Business Outcome Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Outcome Surveys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_FollowUp__c/fields/Survey_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Start_Date__c</fullName>
    <description>This field will be used as base date to trigger all email alert through workflow.</description>
    <inlineHelpText>This field will be used as base date to trigger all email alert through workflow.</inlineHelpText>
    <label>Survey Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_DeleteBlankOutcomeSurveyRecords.cls
@isTest
public class Test_DeleteBlankOutcomeSurveyRecords{
     private static testmethod void test1(){
      Test.startTest();
        Client_FollowUp__c cf=new Client_FollowUp__c();
        cf.Survey_Start_Date__c =System.Date.Today()-1;
        insert cf;

       // This test runs a scheduled job at midnight Sept. 3rd. 2022
        String CRON_EXP = '0 0 0 3 9 ? 2022';
       // Schedule the test job
       String jobId = System.schedule('Test_DeleteBlankOutcomeSurveyRecords', CRON_EXP, new DeleteBlankOutcomeSurveyRecords());
      // Get the information from the CronTrigger API object 
         CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
       // Verify the expressions are the same System.assertEquals(CRON_EXP, ct.CronExpression); 
      // Verify the job has not run 
      System.assertEquals(0, ct.TimesTriggered); 
      // Verify the next time the job will run 
      System.assertEquals('2022-09-03 00:00:00', String.valueOf(ct.NextFireTime));   
      Test.stopTest();        
    }
}