force-app/main/default/objects/Consultation_Follow_up__c/Consultation_Follow_up__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s client consultation follow-up module.  Used to track clients who come back to ET for services.</description>
    <label>Consultation Follow-up</label>
    <nameField>
        <displayFormat>CF-{000000000}</displayFormat>
        <label>Consultation Follow-Up Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultation Follow-ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <label>Advisors</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vikas Jain</fullName>
            </value>
            <value>
                <fullName>Sandi Koitsis-Zigomanis</fullName>
            </value>
            <value>
                <fullName>Jason Li</fullName>
            </value>
            <value>
                <fullName>Karen Keskull</fullName>
            </value>
            <value>
                <fullName>Chris Rickett</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Advisors__c.field-meta.xml
<CustomField>
    <fullName>Advisors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Consultation_Follow_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <label>Confirmation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed by client</fullName>
            </value>
            <value>
                <fullName>Confirmed by advisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>City Hall</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <label>Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Meeting_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Time__c</fullName>
    <label>Meeting Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/MeetingTime__c.field-meta.xml
<CustomField>
    <fullName>MeetingTime__c</fullName>
    <label>MeetingTime</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM - 09 AM</fullName>
            </value>
            <value>
                <fullName>09 AM - 10 AM</fullName>
            </value>
            <value>
                <fullName>10 AM - 11 AM</fullName>
            </value>
            <value>
                <fullName>11 AM - 12 PM</fullName>
            </value>
            <value>
                <fullName>12 PM - 01 PM</fullName>
            </value>
            <value>
                <fullName>01 PM - 02 PM</fullName>
            </value>
            <value>
                <fullName>02 PM - 03 PM</fullName>
            </value>
            <value>
                <fullName>03 PM - 04 PM</fullName>
            </value>
            <value>
                <fullName>04 PM - 05 PM</fullName>
            </value>
            <value>
                <fullName>05 PM - 06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Meeting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rescheduled by Advisor</fullName>
            </value>
            <value>
                <fullName>Rescheduled by Client</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClientMeetingConfirmCtrl.cls
public class ClientMeetingConfirmCtrl
{
    public Consultation_Follow_up__c FollowUp {get; set;}
    
    public boolean ShowFollowUpRecord{get;set;}
    public boolean ShowMeetingConfirmMsg {get;set;}
    public boolean ShowRegisMeetingConfirmMsg {get;set;}
    public boolean ShowCalendar{get;set;}
    public boolean ShowErrorMsg{get;set;}
    public ID FollowUpRecId;

    public ClientMeetingConfirmCtrl()
    {  
        ShowErrorMsg = true;
        ShowFollowUpRecord = false;
        ShowMeetingConfirmMsg = false;
        ShowRegisMeetingConfirmMsg = false;
        ShowCalendar = false;
            
        if(ApexPages.currentPage().getParameters().get('Id') != null)
        {
            if(ApexPages.currentPage().getParameters().get('id') != '')
            {
                FollowUp = [select id, Meeting_Time__c,MeetingTime__c,Advisors__c,Confirmation_Status__c,Meeting_Date__c,  Advisor__c, Location__c, Status__c From Consultation_Follow_up__c WHERE Id = : ApexPages.currentPage().getParameters().get('Id')];
                ShowFollowUpRecord = true;
                ShowErrorMsg = false;
            }
            else
            {
                ShowErrorMsg = true;
                ShowFollowUpRecord = false;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.info, 'Please check the Url'));
            }
        }
        
        if(ApexPages.currentPage().getParameters().get('FollowRecId') != null)
        {
            if(ApexPages.currentPage().getParameters().get('FollowRecId') != '')
            {
                ShowCalendar = false;
                ShowErrorMsg = false;
                ShowFollowUpRecord = false;
                ShowMeetingConfirmMsg = false;
                ShowRegisMeetingConfirmMsg = true;
            }
            else
            {
                ShowCalendar = false;
                ShowErrorMsg = true;
                ShowFollowUpRecord = false;
                ShowMeetingConfirmMsg = false;
                ShowRegisMeetingConfirmMsg = false;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.info, 'Please check the Url'));
            }
        }
        
         
        if(ApexPages.currentPage().getParameters().get('ShowCal') != null)
        {
            if(ApexPages.currentPage().getParameters().get('ShowCal') == 'True')
            {
                ShowCalendar = true;
                ShowFollowUpRecord = true;
                ShowErrorMsg = false;
                ShowMeetingConfirmMsg = false;
                ShowRegisMeetingConfirmMsg = false;
            }
            else
            {
                ShowErrorMsg = true;
                ShowCalendar = false;
                ShowFollowUpRecord = false;
                ShowMeetingConfirmMsg = false;
                ShowRegisMeetingConfirmMsg = false;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.info, 'Please check the Url'));
            }
        }
    }
    
    public PageReference MeetingConfirmed()
    {
        FollowUp.Status__c='Confirmed';
        FollowUp.Confirmation_Status__c = 'Confirmed by client';
        update FollowUp ;
        
        ShowFollowUpRecord = false;
        ShowMeetingConfirmMsg = true;
        ShowRegisMeetingConfirmMsg = false;
        ShowCalendar = false;
        ShowErrorMsg = false;
            
        return null; 
    }
    
    public PageReference MeetingReschuled()
    {
        ShowCalendar = true;
        ShowFollowUpRecord = true;
        ShowMeetingConfirmMsg = false;
        ShowRegisMeetingConfirmMsg = false;
        ShowErrorMsg = false;
        
        PageReference PG = new PageReference(System.Label.ForcecomSite+'/ClientMeetingConfirm?Id='+FollowUp.Id+'&ShowCal=True');
        PG.setRedirect(true);
        return PG;
    }
}