force-app/main/default/objects/Consultation_Follow_up__c/Consultation_Follow_up__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s client consultation follow-up module.  Used to track clients who come back to ET for services.</description>
    <label>Consultation Follow-up</label>
    <nameField>
        <displayFormat>CF-{000000000}</displayFormat>
        <label>Consultation Follow-Up Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultation Follow-ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Advisors__c.field-meta.xml
<CustomField>
    <fullName>Advisors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Consultation_Follow_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <label>Confirmation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed by client</fullName>
            </value>
            <value>
                <fullName>Confirmed by advisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Consultation__c.field-meta.xml
<CustomField>
    <fullName>Consultation__c</fullName>
    <label>Consultation</label>
    <referenceTo>Consultation__c</referenceTo>
    <relationshipLabel>Consultation Follow-ups</relationshipLabel>
    <relationshipName>Consultation_Follow_ups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>City Hall</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <label>Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Meeting_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Time__c</fullName>
    <label>Meeting Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/MeetingTime__c.field-meta.xml
<CustomField>
    <fullName>MeetingTime__c</fullName>
    <label>MeetingTime</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM - 09 AM</fullName>
            </value>
            <value>
                <fullName>09 AM - 10 AM</fullName>
            </value>
            <value>
                <fullName>10 AM - 11 AM</fullName>
            </value>
            <value>
                <fullName>11 AM - 12 PM</fullName>
            </value>
            <value>
                <fullName>12 PM - 01 PM</fullName>
            </value>
            <value>
                <fullName>01 PM - 02 PM</fullName>
            </value>
            <value>
                <fullName>02 PM - 03 PM</fullName>
            </value>
            <value>
                <fullName>03 PM - 04 PM</fullName>
            </value>
            <value>
                <fullName>04 PM - 05 PM</fullName>
            </value>
            <value>
                <fullName>05 PM - 06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation_Follow_up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Meeting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rescheduled by Advisor</fullName>
            </value>
            <value>
                <fullName>Rescheduled by Client</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JqueryDatePicker__c/JqueryDatePicker__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>JqueryDatePicker</label>
</CustomObject>

force-app/main/default/objects/JqueryDatePicker__c/fields/NoOfMonths__c.field-meta.xml
<CustomField>
    <fullName>NoOfMonths__c</fullName>
    <label>NoOfMonths</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JqueryDatePicker__c/fields/StartDateTo__c.field-meta.xml
<CustomField>
    <fullName>StartDateTo__c</fullName>
    <label>StartDateTo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/Leave_Plan__c.object-meta.xml
<CustomObject>
    <description>This custom object is used to capture Leave Plan for various ES Users that will be checked against showing their availability for online consultations.</description>
    <label>Leave Plan</label>
    <nameField>
        <label>Leave Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Plan__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <formula>IF(!ISBLANK(TEXT(End_Time__c)), IF(CONTAINS(TEXT(End_Time__c),&#39;PM&#39;) &amp;&amp; TEXT(End_Time__c) != &#39;12 PM&#39;, Value(LEFT(TEXT(End_Time__c),2))+12, Value(LEFT(TEXT(End_Time__c),2))), 18)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EndTime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <formula>IF(!ISBLANK(TEXT(Start_Time__c)), IF(CONTAINS(TEXT(Start_Time__c),&#39;PM&#39;) &amp;&amp; TEXT(Start_Time__c) != &#39;12 PM&#39;, Value(LEFT(TEXT(Start_Time__c),2))+12, Value(LEFT(TEXT(Start_Time__c),2))), 9)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StartTime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leave_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/DayEndTime__c.field-meta.xml
<CustomField>
    <fullName>DayEndTime__c</fullName>
    <formula>IF(!ISBLANK(TEXT(End_of_day__c)), IF(CONTAINS(TEXT(End_of_day__c),&#39;PM&#39;) &amp;&amp; TEXT(End_of_day__c) != &#39;12 PM&#39;, Value(LEFT(TEXT(End_of_day__c),2))+12, Value(LEFT(TEXT(End_of_day__c),2))), 18)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DayEndTime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/DayStartTime__c.field-meta.xml
<CustomField>
    <fullName>DayStartTime__c</fullName>
    <formula>IF(!ISBLANK(TEXT(Start_of_day__c)), IF(CONTAINS(TEXT(Start_of_day__c),&#39;PM&#39;) &amp;&amp; TEXT(Start_of_day__c) != &#39;12 PM&#39;, Value(LEFT(TEXT(Start_of_day__c),2))+12, Value(LEFT(TEXT(Start_of_day__c),2))), 9)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DayStartTime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/End_of_day__c.field-meta.xml
<CustomField>
    <fullName>End_of_day__c</fullName>
    <label>End of DAY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Friday__c.field-meta.xml
<CustomField>
    <fullName>Friday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Friday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>City Hall</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Start_of_day__c.field-meta.xml
<CustomField>
    <fullName>Start_of_day__c</fullName>
    <label>Start of DAY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Thursday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tuesday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wednesday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ScheduleMeetingCompCtrl.cls
public class ScheduleMeetingCompCtrl
{ 
    public string NoOfMonths {get;set;}
    public string StartDateFrom {get;set;}
    public string StartDateTo {get;set;}
    
    public String LocationSelected {get;set;}
    public String AdvisorSelected {get;set;}
    public String DateSelected {get;set;}
    public String TimeSelected {get;set;}
    
    public String StartYear {get;set;}
    public String StartMonth {get;set;}
    public String StartDay {get;set;}
    
    public boolean AvailableAdvisorsDisable {get;set;}
    public boolean AvailableTimeDisable {get;set;}
    
    public Boolean AlreadyScheduled {get; set;}
    public String AdvisorsWokringDays {get; set;}
    public String disableddates {get;set;}
    
    public String FollowUpEmail {get;set;}
    public String FollowUpId {get;set;}
    
    public Set<Date> NotWorkingDates;
    
    public List<SelectOption> LocationOptions = New List<SelectOption>();
    public List<SelectOption> AdvisorOptions = New List<SelectOption>();
    public List<SelectOption> TimeOptions = New List<SelectOption>();

    public List<SelectOption> AvailableLocations { get{ return LocationOptions;} set{ value = LocationOptions;} }
    public List<SelectOption> AvailableAdvisors { get{ return AdvisorOptions;} set{ value = AdvisorOptions;} }
    public List<SelectOption> AvailableTimeSlots { get{ return TimeOptions;} set{ value = TimeOptions;} }
    
    public PageReference PG;
    
    public ScheduleMeetingCompCtrl()
    {
        Date TD = Date.Today();
        StartYear = String.ValueOf(TD.Year());
        StartMonth = String.ValueOf(TD.Month()-1);
        StartDay = String.ValueOf(TD.adddays(35).Day());
        
        NoOfMonths = '0'; 
        StartDateTo = '-1'; 
        AdvisorsWokringDays = 'day == 9';
        
        AvailableLocations();
        AdvisorOptions.add(new SelectOption('-SELECT-', '-SELECT-'));
        TimeOptions.add(new SelectOption('-SELECT-', '-SELECT-'));
        
        AvailableAdvisorsDisable = true;
        AvailableTimeDisable = true;
        
        //Set<Date> NotWorkingDates = New Set<Date>();
        NotWorkingDates = New Set<Date>();
        for(integer i=1; i <Integer.ValueOf(NoOfMonths)*30; i++)
        {
            Datetime dt = DateTime.newInstance(System.today().adddays(i), Time.newInstance(0, 0, 0, 0));
            NotWorkingDates.add(dt.date());
        }
        
        if(NotWorkingDates.size()>0)
        {
            disableddates = '';
            integer k = 1;
            For(Date dt : NotWorkingDates)
            {
                if(NotWorkingDates.size() != k)
                    disableddates = disableddates + dt.Month() + '-' + dt.Day() + '-' + dt.Year() + '", "';
                else
                    disableddates = disableddates + dt.Month() + '-' + dt.Day() + '-' + dt.Year();
            
                ++k;  
            }
        }
        
        disableddates = '["' + disableddates + '"]';  
    }
    
    public PageReference AvailableLocations()
    {
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Consultation_Follow_up__c.Location__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        LocationOptions.add(new SelectOption('-SELECT-', '-SELECT-'));
        
        for(Schema.PicklistEntry f : ple)
        LocationOptions.add(new SelectOption(f.getLabel(), f.getValue()));
        
        return null;
    }
    
    public void AvailableAdvisors()
    {
        Date TD = Date.Today();
        StartYear = String.ValueOf(TD.Year());
        StartMonth = String.ValueOf(TD.Month()-1);
        StartDay = String.ValueOf(TD.adddays(35).Day());
        
        NoOfMonths = '0'; 
        StartDateTo = '-1'; 
        AdvisorsWokringDays = 'day == 9';
           
        AdvisorOptions.clear();
        AvailableAdvisorsDisable = true;
        AdvisorOptions.add(new SelectOption('-SELECT-', '-SELECT-'));
        
        TimeOptions.clear();
        TimeOptions.add(new SelectOption('-SELECT-', '-SELECT-'));
        AvailableTimeDisable = true;
        
        List<User> userList = [Select Id, Name From User Where Location__c =: LocationSelected AND Location__c !=''];
        
        for(User u : userList)
            AdvisorOptions.add(new SelectOption(u.id, u.name));
            
        if(AdvisorOptions.size()>1)
        {
            AvailableAdvisorsDisable = false;
        }
    }
    
    public void AvailableDays()
    {
        Date TD = Date.Today().adddays(2);
        StartYear = String.ValueOf(TD.Year());
        StartMonth = String.ValueOf(TD.Month()-1);
        StartDay = String.ValueOf(TD.Day());
        
        JqueryDatePicker__c DatePicker = JqueryDatePicker__c.getInstance('DatePicker');
        NoOfMonths = DatePicker.NoOfMonths__c;
        StartDateTo = DatePicker.StartDateTo__c;
        
        User U = [select Id, Name, DayStartTime__c, DayEndTime__c, Start_of_day__c, End_of_day__c, Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, Location__c From User Where Id =: AdvisorSelected];
        
        Set<String> NoWorkingDaysOfWeek = New Set<String>();
        
        if(U.Monday__c==false)
        {
            NoWorkingDaysOfWeek.add('Monday');
        }
        if(U.Tuesday__c==false)
        {
             NoWorkingDaysOfWeek.add('Tuesday');
        }
        if(U.Wednesday__c==false)
        {
             NoWorkingDaysOfWeek.add('Wednesday');
        }
        if(U.Thursday__c==false)
        {
             NoWorkingDaysOfWeek.add('Thursday');
        }
        if(U.Friday__c==false)
        {
             NoWorkingDaysOfWeek.add('Friday');
        } 
        
        List<Leave_Plan__c> lstLeaveplan = [select id, StartTime__c, EndTime__c, Start_Date__c, End_Date__c, Start_Time__c, End_Time__c, Comments__c from Leave_Plan__c where User__c =: AdvisorSelected];
        
        System.debug('-lstLeaveplan- '+ lstLeaveplan);
        
        Set<Date> LeaveSet = New Set<Date>();
        integer LStartTime, LEndTime, WStartTime, WEndTime;
        
        for(Leave_Plan__c l : lstLeaveplan)
        {
            LStartTime = Integer.ValueOf(l.StartTime__c);
            LEndTime = Integer.ValueOf(l.EndTime__c);
            WStartTime = Integer.ValueOf(U.DayStartTime__c); 
            WEndTime = Integer.ValueOf(U.DayEndTime__c);
            
            if(l.Start_Date__c == l.End_Date__c && LStartTime <= WStartTime && LEndTime >= WEndTime)
            {
                LeaveSet.add(l.Start_Date__c);
            }
            else if(l.Start_Date__c != l.End_Date__c)
            {
                While(l.Start_Date__c <= l.End_Date__c)
                {  
                    //if(l.Start_Date__c == l.End_Date__c && LStartTime <= WStartTime && LEndTime >= WEndTime)
                    if(l.Start_Date__c <= l.End_Date__c && LStartTime <= WStartTime && LEndTime >= WEndTime)
                    {
                        LeaveSet.add(l.Start_Date__c);
                    }
                    l.Start_Date__c = l.Start_Date__c.adddays(1);
                }
            }
        }
        
        NotWorkingDates = New Set<Date>();
        
        for(integer i=1; i <Integer.ValueOf(NoOfMonths)*30; i++)
        {
            Datetime dt = DateTime.newInstance(System.today().adddays(i), Time.newInstance(0, 0, 0, 0));
            String dayOfWeek = dt.format('EEEE');
            System.debug('Day : ' + dayOfWeek);
            
            if(noWorkingDaysOfWeek.size()>0 && NoWorkingDaysOfWeek.contains(dayOfWeek))
                NotWorkingDates.add(dt.date());
            else if(LeaveSet.size()>0 && LeaveSet.contains(dt.date()))
                NotWorkingDates.add(dt.date());
        }
        
        disableddates = '';
          
        if(NotWorkingDates.size()>0)
        {
            disableddates = '';
            integer k = 1;
            
            For(Date dt : NotWorkingDates)
            {
                if(NotWorkingDates.size() != k)
                    disableddates = disableddates + dt.Month() + '-' + dt.Day() + '-' + dt.Year() + '", "';
                else
                    disableddates = disableddates + dt.Month() + '-' + dt.Day() + '-' + dt.Year();
                    
                ++k;  
            }
        }
        
        disableddates = '["' + disableddates + '"]';
        
        System.debug('-DisableddatesFinal- ' + disableddates);
        
        //return null;
    }
    
    public void AvailableTimeSlots()
    {
        TimeOptions.clear();
        AvailableTimeDisable = true;
        
        integer LStartTime, LEndTime, WStartTime, WEndTime;
       
        User U = [select Id, Name, DayStartTime__c, DayEndTime__c, Start_of_day__c, End_of_day__c, Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, Location__c From User Where Id =: AdvisorSelected];
        
        Date dt = Date.newInstance(Integer.Valueof(DateSelected.split('/')[2]), Integer.Valueof(DateSelected.split('/')[0]), Integer.Valueof(DateSelected.split('/')[1]));
        
        System.debug('-dt-'+ dt);
        System.debug('-AdvisorSelected-'+ AdvisorSelected );
        
        List<Leave_Plan__c> lstLeaveplan = [select id, StartTime__c, EndTime__c, Start_Date__c, End_Date__c, Start_Time__c, End_Time__c, Comments__c from Leave_Plan__c where User__c =: AdvisorSelected AND (Start_Date__c=:dt OR End_Date__c=:dt)];
        
        List<Consultation_Follow_up__c> lstFollowUpObj = [select id, Consultation__r.Name, Meeting_Date__c, MeetingTime__c, Advisors__c,Confirmation_Status__c, Meeting_Time__c, Location__c,Advisor__c, Status__c from Consultation_Follow_up__c where Advisors__c=: AdvisorSelected and Meeting_date__c=:dt];
        
        List<Consultation_Follow_up__c> lstFollowUpObj1 = [select id, Consultation__r.Name, Meeting_Date__c, MeetingTime__c, Advisors__c,Confirmation_Status__c, Meeting_Time__c, Location__c,Advisor__c, Status__c from Consultation_Follow_up__c];
        
        System.debug('-lstFollowUpObj1 - '+ lstFollowUpObj1);
        
        Set<Integer> FLSet = New Set<Integer>();
        
        if(lstFollowUpObj.size() > 0)
        {
            for(Consultation_Follow_up__c c : lstFollowUpObj){
                if(c.Status__c != 'Rejected')
                    FLSet.add(Integer.ValueOf(c.Meeting_Time__c));
            }
        }
        
        System.debug('-VKS3FLSet-'+ FLSet);
        
        System.debug('-VKSlstLeaveplan size-'+ lstLeaveplan.size());
        
        System.debug('-VKSlstLeaveplan-'+ lstLeaveplan);
        
        TimeOptions.add(new SelectOption('-SELECT-', '-SELECT-'));
        
        WStartTime = Integer.ValueOf(U.DayStartTime__c);
        WEndTime = Integer.ValueOf(U.DayEndTime__c);
        
        if(lstLeaveplan.size()>0)
        {
            for(Leave_Plan__c l : lstLeaveplan)
            {
                LStartTime = Integer.ValueOf(l.StartTime__c);
                LEndTime = Integer.ValueOf(l.EndTime__c);
                
                Set<Integer> iSet = New Set<Integer>();
                
                if(l.Start_Date__c == dt && l.End_Date__c == dt)
                {
                     for(Integer i=LStartTime; i< LEndTime; i++)
                     iSet.add(i);
                     
                     System.debug('-VKS3iSet-'+ iSet);
                     
                     for(Integer i= WStartTime; i < WEndTime; i++)
                     {
                         if(!iSet.contains(i) && !FLSet.contains(i))
                             TimeOptions.add(new SelectOption( String.ValueOf(i), SetAmPm(i)));
                     }
                }
            }
        }
        else
        {
            for(Integer i=WStartTime; i< WEndTime; i++)
            {
                 if(!FLSet.contains(i)) {
                     TimeOptions.add(new SelectOption( String.ValueOf(i), SetAmPm(i)));
                 }   
            }
        }
        
        System.debug('-VKS3-'+ TimeOptions);
        
        if(TimeOptions.size()>1)
            AvailableTimeDisable = false;
    }
    
    public String SetAmPm(integer t)
    {
        String tm;
        
        if(t==12)
            tm = String.ValueOf(t) + ' PM' + ' - ' + '0'+ String.ValueOf(t-11) + ' PM';
        else if(t>12)
            tm = '0'+ String.ValueOf(t-12) + ' PM' + ' - ' + '0'+ String.ValueOf(t-11) + ' PM';
        
        if(t==11)
            tm = String.ValueOf(t) + ' AM' + ' - ' + String.ValueOf(t+1) + ' PM';
        else if(t==10)
            tm = String.ValueOf(t) + ' AM' + ' - ' + String.ValueOf(t+1) + ' AM';
        else if(t==9)
            tm = '0'+ String.ValueOf(t) + ' AM' + ' - ' + String.ValueOf(t+1) + ' AM';
        else if(t<9)
            tm = '0'+ String.ValueOf(t) + ' AM' + ' - ' + '0'+ String.ValueOf(t+1) + ' AM';
            
       return tm;
    }
    
    public PageReference scheduleMeeting()
    {
        System.debug('## VKS - ' + PG);
        
        System.debug('$$ VKS - ' + FollowUpEmail +' - '+ FollowUpId);
        
        if(FollowUpEmail != null && FollowUpEmail != '')
        {
            Consultation__c Con1 = [select id,ET_Consultant__c From Consultation__c WHERE Contact_Consultation__r.Email = : FollowUpEmail limit 1];
            
            System.debug(' %% VKS - ' + Con1);
            
            Consultation__c Con = [select id,ET_Consultant__c From Consultation__c WHERE Contact_Consultation__r.Email = : FollowUpEmail limit 1];
            
            Consultation_Follow_up__c FollowUp = New Consultation_Follow_up__c();
            FollowUp.Meeting_Time__c = TimeSelected;
            FollowUp.MeetingTime__c = SetAmPm(Integer.valueOf(TimeSelected));
            FollowUp.Meeting_Date__c = Date.newInstance(Integer.Valueof(DateSelected.split('/')[2]), Integer.Valueof(DateSelected.split('/')[0]), Integer.Valueof(DateSelected.split('/')[1]));
            FollowUp.Advisor__c = [Select Id, Name From User Where id =: AdvisorSelected limit 1].Name;
            FollowUp.Advisors__c = AdvisorSelected;
            FollowUp.Location__c = LocationSelected;
            FollowUp.Status__c ='Requested';
            FollowUp.Consultation__c = Con.id;
            FollowUp.FollowUp_Consultation_Type__c = 'Follow-up for online clients';
            
            insert FollowUp;
            
            Con.ET_Consultant__c = [Select Id, Name From User Where id =: AdvisorSelected limit 1].Name;
            update Con;
            
            PG = new PageReference(System.Label.ForcecomSite+'/ClientMeetingSchedule?FollowRecId='+FollowUp.Id);
            
        }
        
        if(FollowUpId != null && FollowUpId != '')
        {
            Consultation_Follow_up__c FollowUp = [Select Id,Consultation__c,Meeting_Time__c, MeetingTime__c,Meeting_Date__c,Advisor__c,Advisors__c,Location__c, Status__c From Consultation_Follow_up__c Where Id =:FollowUpId];
            FollowUp.Meeting_Time__c = TimeSelected;
            FollowUp.MeetingTime__c = SetAmPm(Integer.valueOf(TimeSelected));
            FollowUp.Meeting_Date__c = Date.newInstance(Integer.Valueof(DateSelected.split('/')[2]), Integer.Valueof(DateSelected.split('/')[0]), Integer.Valueof(DateSelected.split('/')[1]));
            FollowUp.Advisor__c = [Select Id, Name From User Where id =: AdvisorSelected limit 1].Name;
            FollowUp.Advisors__c = AdvisorSelected; 
            FollowUp.Location__c = LocationSelected;
            FollowUp.Status__c ='Rescheduled by Client';
            
            update FollowUp;
              
            Consultation__c Con = [select id,ET_Consultant__c From Consultation__c WHERE id = : FollowUp.Consultation__c  limit 1];
            Con.ET_Consultant__c = [Select Id, Name From User Where id =: AdvisorSelected limit 1].Name;
            update Con;
            
            PG = new PageReference(System.Label.ForcecomSite+'/ClientMeetingConfirm?FollowRecId='+FollowUp.Id);
        }
     
        PG.setRedirect(true);
        
        FollowUpEmail = '';
        FollowUpId = '';
        
        return PG;
    }  
    
    public void ReScheduleMeeting()
    {
        
    } 
    
    public void Dummy()
    {
        
    } 
}