force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This is the ability to classify the types of organizations.
It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.
Options are:
Business Client - a business we are working with.
Business Prospect - a business or investment we are trying to work with.
Service Provider - a business that we purchase goods or services from.
Partner - an organization that we work with.</description>
    <inlineHelpText>It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Client</fullName>
                <default>true</default>
                <label>Business Client</label>
            </value>
            <value>
                <fullName>Business Prospect</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investment Activity Programs</relationshipLabel>
    <relationshipName>Investment_Activity_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <inlineHelpText>Business Support - Supporting external organizations and their events.
Networking Events -Track attendees at networking events delivered by EDC.
Business Training-Track attendees at training sessions delivered by EDC.</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Event Support</fullName>
            </value>
            <value>
                <fullName>Networking Events</fullName>
            </value>
            <value>
                <fullName>Business Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Group_Management_Type__c.field-meta.xml
<CustomField>
    <fullName>Group_Management_Type__c</fullName>
    <inlineHelpText>Advisory Group - Groups providing input in Toronto programming and policy making.
Stakeholder Group - Used to manage a list of stakeholders – such as a list of manufacturers that can be consulted on projects.</inlineHelpText>
    <label>Group Management Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advisory Group (Formal)</fullName>
            </value>
            <value>
                <fullName>Distribution List (Informal)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/International_Project_Type__c.field-meta.xml
<CustomField>
    <fullName>International_Project_Type__c</fullName>
    <label>International Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outbound Mission</fullName>
            </value>
            <value>
                <fullName>Inbound Mission</fullName>
            </value>
            <value>
                <fullName>International Relationships</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Program_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Sub_Type__c</fullName>
    <label>Business Training Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Event_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>International Events</fullName>
            </value>
            <value>
                <fullName>Business Start Up</fullName>
            </value>
            <value>
                <fullName>Business Expansion</fullName>
            </value>
            <value>
                <fullName>Online Training</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Projects</fullName>
            </value>
            <value>
                <fullName>Project Support (BIA)</fullName>
            </value>
            <value>
                <fullName>International Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Events.recordType-meta.xml
<RecordType>
    <fullName>Events</fullName>
    <active>true</active>
    <description>For tracking work on external event projects where the City is providing support in organizing.</description>
    <label>Events</label>
</RecordType>

force-app/main/default/objects/Campaign/recordTypes/Investment_Activity.recordType-meta.xml
<RecordType>
    <fullName>Investment_Activity</fullName>
    <active>true</active>
    <description>Project of Investment Activity type</description>
    <label>Investment Activity</label>
</RecordType>

force-app/main/default/objects/CampaignMember/fields/Direct_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Direct_Account_ID__c</fullName>
    <formula>Contact.Account.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Direct Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Initiative_Status__c.field-meta.xml
<CustomField>
    <fullName>Initiative_Status__c</fullName>
    <description>This field is referred in trigger Logic to map the value from its parent Initiative and will not be exposed on UI</description>
    <label>Initiative Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Member_Role__c.field-meta.xml
<CustomField>
    <fullName>Member_Role__c</fullName>
    <inlineHelpText>Int-Team Memb-CoT staff
Ext-Team Memb-Ext Org
Srvcs Provider- Hired to assist
Attendee-Registers for the event
Invs, Target-Investment attraction project
BIA Member 
Bus Community Member - Part of the project
Dlgte Inb -Dlgte from inb miss</inlineHelpText>
    <label>Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>External - Team Member</fullName>
            </value>
            <value>
                <fullName>Internal - Team Member</fullName>
            </value>
            <value>
                <fullName>Stakeholder - Attendee</fullName>
            </value>
            <value>
                <fullName>Stakeholder - BIA Member</fullName>
            </value>
            <value>
                <fullName>Stakeholder - Business Community</fullName>
            </value>
            <value>
                <fullName>Stakeholder - Delegate (Inbound)</fullName>
            </value>
            <value>
                <fullName>Stakeholder - Delegate (Outbound)</fullName>
            </value>
            <value>
                <fullName>Stakeholder - Investment Target</fullName>
            </value>
            <value>
                <fullName>Stakeholder - Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Member_Type__c</fullName>
    <label>Member Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Event Support</fullName>
            </value>
            <value>
                <fullName>Networking Events</fullName>
            </value>
            <value>
                <fullName>Business Training</fullName>
            </value>
            <value>
                <fullName>General Projects</fullName>
            </value>
            <value>
                <fullName>International Project</fullName>
            </value>
            <value>
                <fullName>Investment Activity</fullName>
            </value>
            <value>
                <fullName>Advisory Group (Formal)</fullName>
            </value>
            <value>
                <fullName>Distribution List (Informal)</fullName>
            </value>
            <value>
                <fullName>Project Support (BIA)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Related_Contact_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Related_Contact_Account_Type__c</fullName>
    <description>This Field is used to capture Account Type value on Account records related to Contact on Initiative Member and the value will be used in workflow logic to send Client Satisfaction and Business Outcome Survey to Client</description>
    <formula>TEXT(Contact.Account.Account_Type__c)</formula>
    <inlineHelpText>This Field is used to capture Account Type value on Account records related to Contact on Initiative Member and the value will be used in workflow logic to send Client Satisfaction and Business Outcome Survey to Client</inlineHelpText>
    <label>Related Contact Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Survey_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Start_Date__c</fullName>
    <label>Survey Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/Client_FollowUp__c.object-meta.xml
<CustomObject>
    <description>This Object is to capture the Business Outcome response against various objects like Interaction, Online Registration and Project of Event Type.</description>
    <label>Business Outcome Survey</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Business Outcome Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Outcome Surveys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_FollowUp__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Outcome Surveys</relationshipLabel>
    <relationshipName>Account_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contat_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Start Up</fullName>
            </value>
            <value>
                <fullName>Business Expansion</fullName>
            </value>
            <value>
                <fullName>Export Development</fullName>
            </value>
            <value>
                <fullName>Mission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Survey_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Start_Date__c</fullName>
    <description>This field will be used as base date to trigger all email alert through workflow.</description>
    <inlineHelpText>This field will be used as base date to trigger all email alert through workflow.</inlineHelpText>
    <label>Survey Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture the Interaction with various Account and Contact coming through various different channels in salesforce.</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{00000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT(Account__r.Account_Type__c)</formula>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interaction</relationshipLabel>
    <relationshipName>Interaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Survey_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Start_Date__c</fullName>
    <description>This will be the date referenced by Survey workflow to sent out the business outcome survey notification after 30, 60 and 90 days</description>
    <inlineHelpText>This will be the date referenced by Survey workflow to sent out the business outcome survey notification after 30, 60 and 90 days</inlineHelpText>
    <label>Survey Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Online_Registration__c/Online_Registration__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s online business registration module - handles data related to business registrations.</description>
    <label>Online Registration</label>
    <nameField>
        <displayFormat>ET-Reg-{000000}</displayFormat>
        <label>ET-Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Online_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Online Registrations</relationshipLabel>
    <relationshipName>Online_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CampaignMemberTriggerActions.cls
public class CampaignMemberTriggerActions{
    
    public static void updateSurveyStartDateAndMemberType(List<CampaignMember> newCampaignMemberList){
        Set<String> campIdSet = new Set<String>();
        for(CampaignMember campMem: newCampaignMemberList){
            campIdSet.add(campMem.CampaignId);
        }
        Map<String,String> recTypeNameIDMap = new Map<String,String>();
        
        for(RecordType recType:[SELECT DeveloperName,Id,Name,SobjectType FROM RecordType WHERE SobjectType = 'Campaign' ]){
            recTypeNameIDMap.put(recType.DeveloperName,recType.Id);
        }
        
        Map<Id,Campaign> campMap = new Map<Id,Campaign>([Select Id, RecordTypeId, EndDate,Group_Management_Type__c,Project_Type__c, Event_Type__c,Program_Sub_Type__c,International_Project_Type__c FROM Campaign WHERE Id IN: campIdSet]);
        system.debug('campMap +++'+campMap);
        
        for(CampaignMember updCampMem: newCampaignMemberList){
            system.debug('inside+++'+campMap);
            if(campMap.size()>0 && campMap.containsKey(updCampMem.CampaignId) && campMap.get(updCampMem.CampaignId).EndDate !=null && campMap.get(updCampMem.CampaignId).Program_Sub_Type__c != 'Online Training')
            updCampMem.Survey_Start_Date__c = campMap.get(updCampMem.CampaignId).EndDate;
            if(campMap.size()>0 && campMap.containsKey(updCampMem.CampaignId) && campMap.get(updCampMem.CampaignId).Program_Sub_Type__c != null && campMap.get(updCampMem.CampaignId).Program_Sub_Type__c == 'Online Training')
            updCampMem.Survey_Start_Date__c = date.today();
        
            if(campMap.size()>0 && campMap.get(updCampMem.CampaignId).Event_Type__c!= null && updCampMem.Member_Role__c==null){
                updCampMem.Member_Type__c = campMap.get(updCampMem.CampaignId).Event_Type__c;
                updCampMem.Member_Role__c = 'Stakeholder - Attendee';
            }
            if(campMap.size()>0 && campMap.get(updCampMem.CampaignId).Project_Type__c!= null && updCampMem.Member_Role__c==null){
                updCampMem.Member_Type__c = campMap.get(updCampMem.CampaignId).Project_Type__c; 
                if(campMap.get(updCampMem.CampaignId).International_Project_Type__c!= null && campMap.get(updCampMem.CampaignId).International_Project_Type__c == 'Outbound Mission' )
                updCampMem.Member_Role__c = 'Stakeholder - Delegate (Outbound)';                
                if(campMap.get(updCampMem.CampaignId).International_Project_Type__c!= null && campMap.get(updCampMem.CampaignId).International_Project_Type__c == 'Inbound Mission' )
                updCampMem.Member_Role__c = 'Stakeholder - Delegate (Inbound)';     
            }   
            if(campMap.size()>0 && campMap.get(updCampMem.CampaignId).Group_Management_Type__c!= null && updCampMem.Member_Role__c==null){
                updCampMem.Member_Type__c = campMap.get(updCampMem.CampaignId).Group_Management_Type__c;
                updCampMem.Member_Role__c = 'Stakeholder - Business Community';     
            }
            if(campMap.size()>0 && recTypeNameIDMap!=null && campMap.get(updCampMem.CampaignId).RecordTypeId== recTypeNameIDMap.get('Investment_Activity') && updCampMem.Member_Role__c==null){
                updCampMem.Member_Type__c = 'Investment Activity'; 
                updCampMem.Member_Role__c = 'Stakeholder - Investment Target';
            }
        }
    }
    public static void upsertClientFollowUpForCampaignMember(List<CampaignMember> newCampaignMemberList,Map<Id,CampaignMember> oldCampaignMemberMap){
        Set<String> contactIdSet = new Set<String>(); 
        //Set<String> campIdSet = new Set<String>(); 
        Map<String,Client_FollowUp__c> ContClientFollowMap = new Map<String,Client_FollowUp__c>();
        List<Client_FollowUp__c> clientFollowUpUpdateList = new List<Client_FollowUp__c>();
        List<Client_FollowUp__c> clientFollowUpInsertList = new List<Client_FollowUp__c>();
        Set<String> projectTypeSet = new Set<String>{'Business Start Up','Business Expansion'};
        Set<String> accountSet = new Set<String>(); 
        Map<String,String> recTypeNameIDMap = new Map<String,String>();
        for(RecordType recType:[SELECT DeveloperName,Id,Name,SobjectType FROM RecordType WHERE SobjectType = 'Campaign' ]){
            recTypeNameIDMap.put(recType.DeveloperName,recType.Id);
        }
        system.debug('++recTypeNameIDMap++'+recTypeNameIDMap);
        
        List<CampaignMember> camMemList = new List<CampaignMember>([SELECT Id, CampaignId,Campaign.RecordTypeId,ContactId, Campaign.EndDate,Campaign.Program_Sub_Type__c, Direct_Account_ID__c,Survey_Start_Date__c FROM CampaignMember WHERE (ID IN: newCampaignMemberList AND Campaign.RecordTypeId=: recTypeNameIDMap.get('Events') AND Member_Role__c = 'Stakeholder - Attendee' AND ((Campaign.Program_Sub_Type__c IN: projectTypeSet AND Initiative_Status__c = 'Completed') OR (Campaign.Program_Sub_Type__c = 'Online Training')) AND Related_Contact_Account_Type__c = 'Business Client' AND Contact.HasOptedOutOfEmail=false)]);
        system.debug('camMemList'+camMemList);
        for(CampaignMember campMem : camMemList){
            if(campMem.ContactId!=null){
                contactIdSet.add(campMem.ContactId);
                accountSet.add(campMem.Direct_Account_ID__c);
            }
        }
        system.debug('++contactIdSet++'+contactIdSet);
        List<Client_FollowUp__c> clientFollowUpList = [SELECT Account__c, Contact__c, Interaction__c, Engagement_Type__c,Workflow_Session__c , Online_Registration__c, Event__c,Survey_Start_Date__c,Initial_Survey_Completed__c,Initial_Survey_Stage__c FROM Client_FollowUp__c WHERE Contact__c IN: contactIdSet AND (Initial_Survey_Completed__c = false OR Initial_Survey_Stage__c != 'Unresponsive')];
        Map<Id,Account> accountMap = new Map<Id,Account>();
        if(accountSet!=null && accountSet.size()>0){
            accountMap = new Map<Id,Account>([SELECT Id, Account_Type__c FROM Account WHERE ID IN: accountSet]);
        }
        
        if(clientFollowUpList.size()>0){
            for(Client_FollowUp__c cfollow : clientFollowUpList){
                ContClientFollowMap.put(cfollow.Contact__c,cfollow);
            }
        }
        system.debug('++ContClientFollowMap++'+ContClientFollowMap);
        if(AvoidRecursion.isFirstRun()){ 
            for(CampaignMember campMemUpdate: camMemList){
                if(accountMap!=null && accountMap.containsKey(campMemUpdate.Direct_Account_ID__c) && accountMap.get(campMemUpdate.Direct_Account_ID__c).Account_Type__c == 'Business Client'){
                    if(ContClientFollowMap.keySet().size() > 0){
                        for(Client_FollowUp__c cfollowup :  ContClientFollowMap.Values()){
                             system.debug('++cfollowup ++'+cfollowup );
                            if(ContClientFollowMap.containsKey(campMemUpdate.ContactId) && campMemUpdate.ContactId == cfollowup.contact__c && campMemUpdate.Campaign.RecordTypeId == recTypeNameIDMap.get('Events') && (campMemUpdate.Campaign.Program_Sub_Type__c == 'Business Start Up' ||campMemUpdate.Campaign.Program_Sub_Type__c == 'Business Expansion'||campMemUpdate.Campaign.Program_Sub_Type__c == 'Online Training')){
                                system.debug('++cfollowup++'+cfollowup);
                                cfollowup.Event__c = campMemUpdate.CampaignId;
                                if(campMemUpdate.Campaign.Program_Sub_Type__c == 'Business Start Up'){
                                    if(cfollowup.Engagement_Type__c==null){
                                        cfollowup.Engagement_Type__c= 'Business Start Up Event';
                                    }else if(cfollowup.Engagement_Type__c!=null && !cfollowup.Engagement_Type__c.contains('Business Start Up Event')){
                                        cfollowup.Engagement_Type__c+= ';Business Start Up Event';
                                    }
                                    if((cfollowup.Survey_Start_Date__c!=null && cfollowup.Survey_Start_Date__c<campMemUpdate.Campaign.EndDate)||(cfollowup.Survey_Start_Date__c ==null)){
                                        cFollowUp.Workflow_Session__c = 'Business Start Up Event';
                                        cfollowup.Survey_Start_Date__c = campMemUpdate.Campaign.EndDate;
                                    }
                                }else if(campMemUpdate.Campaign.Program_Sub_Type__c == 'Online Training'){
                                    if(cfollowup.Engagement_Type__c==null){
                                        cfollowup.Engagement_Type__c= 'Online Training';
                                    }else if(cfollowup.Engagement_Type__c!=null && !cfollowup.Engagement_Type__c.contains('Online Training')){
                                        cfollowup.Engagement_Type__c+= ';Online Training';
                                    }
                                    if((cfollowup.Survey_Start_Date__c!=null && cfollowup.Survey_Start_Date__c<campMemUpdate.Survey_Start_Date__c.addDays(7)) ||(cfollowup.Survey_Start_Date__c ==null)){
                                        cFollowUp.Workflow_Session__c = 'Online Training';
                                        cfollowup.Survey_Start_Date__c = campMemUpdate.Survey_Start_Date__c.addDays(7);
                                    }   
                                }
                                else{
                                    if(cfollowup.Engagement_Type__c==null){
                                        cfollowup.Engagement_Type__c= 'Business Expansion Event';
                                     }else if(cfollowup.Engagement_Type__c!=null && !cfollowup.Engagement_Type__c.contains('Business Expansion Event')){
                                        cfollowup.Engagement_Type__c+= ';Business Expansion Event';
                                    }
                                    if((cfollowup.Survey_Start_Date__c!=null && cfollowup.Survey_Start_Date__c<campMemUpdate.Campaign.EndDate) || (cfollowup.Survey_Start_Date__c ==null)){
                                        cFollowUp.Workflow_Session__c = 'Business Expansion Event';
                                        cfollowup.Survey_Start_Date__c = campMemUpdate.Campaign.EndDate;
                                    }
                                }
                            }
                            clientFollowUpUpdateList.add(cfollowup);  
                        }
                    }
                    else{
                        Client_FollowUp__c cFolloUpNew = new Client_FollowUp__c();
                        if(campMemUpdate.Campaign.RecordTypeId == recTypeNameIDMap.get('Events')){
                            if(campMemUpdate.Campaign.Program_Sub_Type__c == 'Business Start Up' || campMemUpdate.Campaign.Program_Sub_Type__c == 'Business Expansion' || campMemUpdate.Campaign.Program_Sub_Type__c == 'Online Training' ){
                                cFolloUpNew.Contact__c = campMemUpdate.ContactId;
                                cFolloUpNew.Event__c = campMemUpdate.CampaignId;
                                cFolloUpNew.Account__c = campMemUpdate.Direct_Account_ID__c;
                                if(campMemUpdate.Campaign.Program_Sub_Type__c == 'Online Training')
                                    cFolloUpNew.Survey_Start_Date__c = campMemUpdate.Survey_Start_Date__c.addDays(7);
                                else
                                    cFolloUpNew.Survey_Start_Date__c = campMemUpdate.Campaign.EndDate;
                                if(campMemUpdate.Campaign.Program_Sub_Type__c == 'Business Start Up'){
                                    cFolloUpNew.Workflow_Session__c = 'Business Start Up Event';
                                    cFolloUpNew.Engagement_Type__c= 'Business Start Up Event';
                                }
                                else if(campMemUpdate.Campaign.Program_Sub_Type__c == 'Online Training'){
                                    cFolloUpNew.Workflow_Session__c = 'Online Training';
                                    cFolloUpNew.Engagement_Type__c= 'Online Training';
                                }else{
                                    cFolloUpNew.Workflow_Session__c = 'Business Expansion Event';
                                    cFolloUpNew.Engagement_Type__c= 'Business Expansion Event';
                                }   
                            }
                        }   
                        clientFollowUpInsertList.add(cFolloUpNew);
                    }
                }   
            }
            try{
                if(clientFollowUpUpdateList.size() > 0) {
                    Database.update(clientFollowUpUpdateList);
                }
                if(clientFollowUpInsertList.size() > 0) {
                    Database.insert(clientFollowUpInsertList);
                }
            }
            catch (Exception ex){
                System.debug('Error occurred in upsertClientFollowUpForCampaignMember: ' + ex.getMessage());
            }
        }   
    }
}