force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This is the ability to classify the types of organizations.
It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.
Options are:
Business Client - a business we are working with.
Business Prospect - a business or investment we are trying to work with.
Service Provider - a business that we purchase goods or services from.
Partner - an organization that we work with.</description>
    <inlineHelpText>It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Client</fullName>
                <default>true</default>
                <label>Business Client</label>
            </value>
            <value>
                <fullName>Business Prospect</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Continent__c.field-meta.xml
<CustomField>
    <fullName>Physical_Continent__c</fullName>
    <description>The continent value in this field is corresponding to country.</description>
    <label>Physical Continent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Antartica</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia/Europe</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <description>Organization accounts with multiple contacts.</description>
    <label>Business Account</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/Financial_Incentive__c.object-meta.xml
<CustomObject>
    <description>This object will be used to build various grant process within salesforce application to various department like ES, BIA and BGS</description>
    <label>Financial Incentive</label>
    <nameField>
        <displayFormat>FIN-{YYYY}-{000000}</displayFormat>
        <label>Financial Incentive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Incentives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Incentive__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Incentives</relationshipLabel>
    <relationshipName>Financial_Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Financial Incentives</relationshipLabel>
    <relationshipName>Financial_Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Financial_Incentive_Name__c.field-meta.xml
<CustomField>
    <fullName>Financial_Incentive_Name__c</fullName>
    <description>This is a read only field used to store unique Record Name with Auto-number based on Record Type</description>
    <inlineHelpText>This is a read only field used to store unique Record Name with Auto-number based on Record Type</inlineHelpText>
    <label>Unique Identifier Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Pending Extension</fullName>
            </value>
            <value>
                <fullName>Extension Approved</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved by GM</fullName>
            </value>
            <value>
                <fullName>Approved by City Council</fullName>
            </value>
            <value>
                <fullName>With Legal</fullName>
            </value>
            <value>
                <fullName>Legal Agreement Completed</fullName>
            </value>
            <value>
                <fullName>Reassessment</fullName>
            </value>
            <value>
                <fullName>Amending Agreement</fullName>
            </value>
            <value>
                <fullName>Compliance/Payment Review</fullName>
            </value>
            <value>
                <fullName>Withdrawn/Inactive</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Application Declined</fullName>
            </value>
            <value>
                <fullName>Extension Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Eligibility Criteria not Met</fullName>
            </value>
            <value>
                <fullName>Interview Required</fullName>
            </value>
            <value>
                <fullName>Declined after Interview</fullName>
            </value>
            <value>
                <fullName>Approved for Training</fullName>
            </value>
            <value>
                <fullName>Declined for Training</fullName>
            </value>
            <value>
                <fullName>Training Completed</fullName>
            </value>
            <value>
                <fullName>Business Plan Received</fullName>
            </value>
            <value>
                <fullName>Score Card Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/Sector_Grant.recordType-meta.xml
<RecordType>
    <fullName>Sector_Grant</fullName>
    <active>true</active>
    <description>This Record type is only applicable to various Grant related to sector like Event. Project and Membership</description>
    <label>Sector Grant</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/Starter_Company_Grant.recordType-meta.xml
<RecordType>
    <fullName>Starter_Company_Grant</fullName>
    <active>true</active>
    <description>Applicable to Starter Company Program</description>
    <label>Starter Company Grant</label>
</RecordType>

force-app/main/default/classes/Test_FinIncStarterCompanyInboundEmail.cls
/**
* @File Name:   Test_FinIncStarterCompanyInboundEmail.cls
* @Description: Test class for email service FinIncStarterCompanyInboundEmail.cls   
* @Author:      Manish Gaur
* @Group:       Apex 
* @Last Modified by:   Manish
* @Last Modified time: 2019-09-09
* @Modification Log :
*-------------------------------------------------------------------------------------
* Ver       Date        Author         Modification
* 1.0       2019-09-09  Manish Gaur    Created the file/class
*/
@isTest
private without sharing class Test_FinIncStarterCompanyInboundEmail{
    @testsetup
    static void setupTestData(){
        RecordType rtBus = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
        Map<String,String> finRTMap = new Map<String,String>();
        for(RecordType rt: [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType WHERE SobjectType = 'Financial_Incentive__c']){
            finRTMap.put(rt.DeveloperName,rt.Id); 
        }
        //Below code create list of Account records Business and Person Account
        List<Account> accList = new List<Account>(); 
        accList.add(new Account(Name='City Of Toronto 1',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='North America'));
        insert accList;
        
        //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
        conList.add(new Contact(firstname='Test',lastname='Contact',Email='test@cityoftoronto.com',AccountId=accList[0].Id));
        insert conList;
                //Below code create list of Starter Company records
        List<Financial_Incentive__c> finIncList = new List<Financial_Incentive__c >();
        //Sector Grant Record
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[0].Id, Account__c = accList[0].Id,RecordTypeId=finRTMap.get('Sector_Grant'),Status__c='Draft'));
        //Starter Company Grant Record
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[0].Id, Account__c = accList[0].Id,RecordTypeId=finRTMap.get('Starter_Company_Grant'),Status__c='Draft'));
        insert finIncList;
    }
    
    static testMethod void test_PositiveCalllInboundEmailService() {
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        Financial_Incentive__c fin=[SELECT Id, Financial_Incentive_Name__c FROM Financial_Incentive__c WHERE Financial_Incentive_Name__c LIKE: '%STR%'];
        String recName = fin.Financial_Incentive_Name__c;
        email.subject = 'Sample Subject'+recName;
        email.plainTextBody = 'FromEmail Sample Test Data';
        env.fromAddress = 'SampleEmail@testcom';
        Messaging.InboundEmail.BinaryAttachment binaryAttachment = new Messaging.InboundEmail.BinaryAttachment();
        binaryAttachment.Filename = 'test.pdf';
        binaryAttachment.body = blob.valueOf('my attachment text');
        email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { binaryattachment }; 
        
        Messaging.InboundEmail.TextAttachment textAttachment = new Messaging.InboundEmail.TextAttachment ();
        textAttachment.Filename = 'test.txt';
        textAttachment.body = 'my attachment text';
        email.TextAttachments = new Messaging.inboundEmail.TextAttachment [] { textAttachment }; 
 
         
        FinIncStarterCompanyInboundEmail updateFinInc = new FinIncStarterCompanyInboundEmail();
        updateFinInc.handleInboundEmail(email, env );
    
    }
    static testMethod void test_NegativeCalllInboundEmailService() {
        try{
            Messaging.InboundEmail email = new Messaging.InboundEmail() ;
            Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
      
            email.plainTextBody = 'FromEmail Sample Test Data';
            env.fromAddress = 'SampleEmail@testcom';
      
            FinIncStarterCompanyInboundEmail updateFinInc = new FinIncStarterCompanyInboundEmail();
            updateFinInc.handleInboundEmail(email, env );
        }
        catch (Exception e) {
        
        }
    }
    
}