force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This is the ability to classify the types of organizations.
It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.
Options are:
Business Client - a business we are working with.
Business Prospect - a business or investment we are trying to work with.
Service Provider - a business that we purchase goods or services from.
Partner - an organization that we work with.</description>
    <inlineHelpText>It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Client</fullName>
                <default>true</default>
                <label>Business Client</label>
            </value>
            <value>
                <fullName>Business Prospect</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/Client_FollowUp__c.object-meta.xml
<CustomObject>
    <description>This Object is to capture the Business Outcome response against various objects like Interaction, Online Registration and Project of Event Type.</description>
    <label>Business Outcome Survey</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Business Outcome Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Outcome Surveys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_FollowUp__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Outcome Surveys</relationshipLabel>
    <relationshipName>Account_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contat_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Start Up Event</fullName>
            </value>
            <value>
                <fullName>Online Registration</fullName>
            </value>
            <value>
                <fullName>Consultation Interaction</fullName>
            </value>
            <value>
                <fullName>Company Intelligence Interaction</fullName>
            </value>
            <value>
                <fullName>Business Expansion Event</fullName>
            </value>
            <value>
                <fullName>Online Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>Events_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Initial_Survey_Completed__c.field-meta.xml
<CustomField>
    <fullName>Initial_Survey_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is to indicated whether initial survey sent out after 30/60/90 days has been completed or not.</description>
    <inlineHelpText>This field is to indicated whether initial survey sent out after 30/60/90 days has been completed or not.</inlineHelpText>
    <label>Initial Survey Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Initial_Survey_Stage__c.field-meta.xml
<CustomField>
    <fullName>Initial_Survey_Stage__c</fullName>
    <description>This field is to track the various stages of Business Outcome surveys including reminder sent in interval of 30. 60 90  days or 6 Months.</description>
    <inlineHelpText>This field is to track the various stages of Business Outcome surveys including reminder sent in interval of 30. 60 90  days or 6 Months.</inlineHelpText>
    <label>Initial Survey Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Queue - 30 Days</fullName>
            </value>
            <value>
                <fullName>In Queue - 60 Days</fullName>
            </value>
            <value>
                <fullName>In Queue - 90 Days</fullName>
            </value>
            <value>
                <fullName>Sent - 90 Days</fullName>
            </value>
            <value>
                <fullName>Responded</fullName>
            </value>
            <value>
                <fullName>Unresponsive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Interaction__c.field-meta.xml
<CustomField>
    <fullName>Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interaction</label>
    <referenceTo>Interaction__c</referenceTo>
    <relationshipName>Interaction_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Online_Registration__c.field-meta.xml
<CustomField>
    <fullName>Online_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Online Registration</label>
    <referenceTo>Online_Registration__c</referenceTo>
    <relationshipName>Online_Registration_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Survey_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Start_Date__c</fullName>
    <description>This field will be used as base date to trigger all email alert through workflow.</description>
    <inlineHelpText>This field will be used as base date to trigger all email alert through workflow.</inlineHelpText>
    <label>Survey Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Workflow_Session__c.field-meta.xml
<CustomField>
    <fullName>Workflow_Session__c</fullName>
    <label>Workflow Session</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consultation Interaction</fullName>
            </value>
            <value>
                <fullName>Business Start Up Event</fullName>
            </value>
            <value>
                <fullName>Online Registration</fullName>
            </value>
            <value>
                <fullName>Company Intelligence Interaction</fullName>
            </value>
            <value>
                <fullName>Business Expansion Event</fullName>
            </value>
            <value>
                <fullName>Online Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture the Interaction with various Account and Contact coming through various different channels in salesforce.</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{00000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT(Account__r.Account_Type__c)</formula>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interaction</relationshipLabel>
    <relationshipName>Interaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Survey_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Start_Date__c</fullName>
    <description>This will be the date referenced by Survey workflow to sent out the business outcome survey notification after 30, 60 and 90 days</description>
    <inlineHelpText>This will be the date referenced by Survey workflow to sent out the business outcome survey notification after 30, 60 and 90 days</inlineHelpText>
    <label>Survey Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Online_Registration__c/Online_Registration__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s online business registration module - handles data related to business registrations.</description>
    <label>Online Registration</label>
    <nameField>
        <displayFormat>ET-Reg-{000000}</displayFormat>
        <label>ET-Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Online_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Online Registrations</relationshipLabel>
    <relationshipName>Online_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Online_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Online Registrations</relationshipLabel>
    <relationshipName>Online_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OnlineRegTriggerActions.cls
public class OnlineRegTriggerActions{
    
    public static void upsertClientFollowUpForOnlineReg(List<Online_Registration__c> newOnlineRegistrationList,Map<Id,Online_Registration__c> oldOnlineRegistrationMap){
        Set<String> contactSet = new Set<String>(); 
        Map<String,Client_FollowUp__c> ContClientFollowMap = new Map<String,Client_FollowUp__c>();
        List<Client_FollowUp__c> clientFollowUpUpdateList = new List<Client_FollowUp__c>();
        List<Client_FollowUp__c> clientFollowUpInsertList = new List<Client_FollowUp__c>();
        Set<String> accountSet = new Set<String>();
        
        for(Online_Registration__c oreg : newOnlineRegistrationList){
            if(oreg.Contact__c!=null)
            contactSet.add(oreg.Contact__c);
            accountSet.add(oreg.Account__c);
        }
        Map<Id,Account> accountMap = new Map<Id,Account>();
        if(accountSet!=null && accountSet.size()>0){
            accountMap = new Map<Id,Account>([SELECT Id, Account_Type__c FROM Account WHERE ID IN: accountSet]);
        }
        List<Client_FollowUp__c> clientFollowUpList = [SELECT Account__c, Contact__c, Engagement_Type__c,Workflow_Session__c ,Interaction__c, Online_Registration__c, Event__c, Survey_Start_Date__c,Initial_Survey_Completed__c,Initial_Survey_Stage__c  FROM Client_FollowUp__c WHERE Contact__c IN: contactSet AND (Initial_Survey_Completed__c = false OR Initial_Survey_Stage__c != 'Unresponsive')];
        if(clientFollowUpList.size()>0){
            for(Client_FollowUp__c cfollow : clientFollowUpList){
                ContClientFollowMap.put(cfollow.Contact__c,cfollow);
            }
        }
        if(AvoidRecursion.isFirstRun()){ 
            for(Online_Registration__c oregToUpdate: newOnlineRegistrationList){
                if(accountMap!=null && accountMap.containsKey(oregToUpdate.Account__c) && accountMap.get(oregToUpdate.Account__c).Account_Type__c == 'Business Client'){
                    if(ContClientFollowMap.keySet().size() > 0){
                    for(Client_FollowUp__c cfollowup :  ContClientFollowMap.Values()){
                            if(ContClientFollowMap.containsKey(oregToUpdate.Contact__c) && oregToUpdate.Contact__c == cfollowup.contact__c){
                                cfollowup.Online_Registration__c = oregToUpdate.Id;
                                if(cfollowup.Engagement_Type__c==null){
                                    cfollowup.Engagement_Type__c= 'Online Registration';
                                }else if(cfollowup.Engagement_Type__c!=null && !cfollowup.Engagement_Type__c.contains('Online Registration')){
                                        cfollowup.Engagement_Type__c+= ';Online Registration';
                                }
                                if(cfollowup.Survey_Start_Date__c!=null && cfollowup.Survey_Start_Date__c<oregToUpdate.CreatedDate.date()){
                                    cfollowup.Workflow_Session__c = 'Online Registration';
                                    cfollowup.Survey_Start_Date__c = oregToUpdate.CreatedDate.date();
                                }
                               clientFollowUpUpdateList.add(cfollowup);  
                            }
                        }
                    }
                    else{
                        Client_FollowUp__c cFolloUpNew = new Client_FollowUp__c();
                        cFolloUpNew.Online_Registration__c = oregToUpdate.Id;
                        cFolloUpNew.Contact__c = oregToUpdate.Contact__c;
                        cFolloUpNew.Account__c = oregToUpdate.Account__c;
                         cFolloUpNew.Survey_Start_Date__c = oregToUpdate.CreatedDate.date();
                        cFolloUpNew.Workflow_Session__c = 'Online Registration';
                        cFolloUpNew.Engagement_Type__c= 'Online Registration';
                        clientFollowUpInsertList.add(cFolloUpNew);
                    }
                }   
            }
            try{
                if(clientFollowUpUpdateList.size() > 0) {
                    Database.update(clientFollowUpUpdateList);
                }
                if(clientFollowUpInsertList.size() > 0) {
                    Database.insert(clientFollowUpInsertList);
                }
            }
            catch (Exception ex){
                System.debug('Error occurred in upsertClientFollowUpForOnlineRegistration: ' + ex.getMessage());
            }
        }
    }
    
}