force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This is the ability to classify the types of organizations.
It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.
Options are:
Business Client - a business we are working with.
Business Prospect - a business or investment we are trying to work with.
Service Provider - a business that we purchase goods or services from.
Partner - an organization that we work with.</description>
    <inlineHelpText>It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Client</fullName>
                <default>true</default>
                <label>Business Client</label>
            </value>
            <value>
                <fullName>Business Prospect</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <description>Organization accounts with multiple contacts.</description>
    <label>Business Account</label>
</RecordType>

force-app/main/default/objects/Client_FollowUp__c/Client_FollowUp__c.object-meta.xml
<CustomObject>
    <description>This Object is to capture the Business Outcome response against various objects like Interaction, Online Registration and Project of Event Type.</description>
    <label>Business Outcome Survey</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Business Outcome Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Outcome Surveys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_FollowUp__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Outcome Surveys</relationshipLabel>
    <relationshipName>Account_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contat_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Start Up Event</fullName>
            </value>
            <value>
                <fullName>Online Registration</fullName>
            </value>
            <value>
                <fullName>Consultation Interaction</fullName>
            </value>
            <value>
                <fullName>Company Intelligence Interaction</fullName>
            </value>
            <value>
                <fullName>Business Expansion Event</fullName>
            </value>
            <value>
                <fullName>Online Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Interaction__c.field-meta.xml
<CustomField>
    <fullName>Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interaction</label>
    <referenceTo>Interaction__c</referenceTo>
    <relationshipName>Interaction_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Survey_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Start_Date__c</fullName>
    <description>This field will be used as base date to trigger all email alert through workflow.</description>
    <inlineHelpText>This field will be used as base date to trigger all email alert through workflow.</inlineHelpText>
    <label>Survey Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture the Interaction with various Account and Contact coming through various different channels in salesforce.</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{00000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT(Account__r.Account_Type__c)</formula>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <description>Which Advisor is conducting consultation</description>
    <inlineHelpText>Which Advisor is conducting consultation</inlineHelpText>
    <label>Advisor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vikas Jain</fullName>
            </value>
            <value>
                <fullName>Sandi Koitsis-Zigomanis</fullName>
            </value>
            <value>
                <fullName>Jason Li</fullName>
            </value>
            <value>
                <fullName>Karen Keskull</fullName>
            </value>
            <value>
                <fullName>Chris Rickett</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Advisor_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which Advisor is conducting consultation</description>
    <inlineHelpText>Which Advisor is conducting consultation</inlineHelpText>
    <label>Advisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Related_Interaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Business_Status__c.field-meta.xml
<CustomField>
    <fullName>Business_Status__c</fullName>
    <description>Business Status</description>
    <inlineHelpText>Business Status</inlineHelpText>
    <label>Business Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
                <default>true</default>
                <label>Existing Client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interaction</relationshipLabel>
    <relationshipName>Interaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Date_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Contact__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date the interaction took place</description>
    <inlineHelpText>The date the interaction took place</inlineHelpText>
    <label>Date of Contact</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Follow_Up_Consultation_Type__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Consultation_Type__c</fullName>
    <description>What type of follow up is required</description>
    <inlineHelpText>What type of follow up is required</inlineHelpText>
    <label>Follow-Up Consultation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Follow-Up for Walk in clients</fullName>
            </value>
            <value>
                <fullName>Follow-Up for Online clients</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender</description>
    <inlineHelpText>Gender</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of consultation</description>
    <inlineHelpText>Location of consultation</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scarborough Civic Centre - 150 Borough Drive - Main Floor</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre - 5100 Yonge Street - Main Floor</fullName>
            </value>
            <value>
                <fullName>Parkdale Innovation Centre (1464 Queen Street West)</fullName>
            </value>
            <value>
                <fullName>Outreach</fullName>
            </value>
            <value>
                <fullName>Downtown Toronto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <description>Meeting Date</description>
    <inlineHelpText>Meeting Date</inlineHelpText>
    <label>Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Meeting_Status__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Status__c</fullName>
    <description>Meeting Status</description>
    <inlineHelpText>Meeting Status</inlineHelpText>
    <label>Meeting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled by Client</fullName>
            </value>
            <value>
                <fullName>Cancelled by Advisor</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/MeetingTime__c.field-meta.xml
<CustomField>
    <fullName>MeetingTime__c</fullName>
    <description>Meeting Time</description>
    <inlineHelpText>Meeting Time</inlineHelpText>
    <label>Meeting Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 00 AM - 08 30 AM</fullName>
            </value>
            <value>
                <fullName>08 30 AM - 09 00 AM</fullName>
            </value>
            <value>
                <fullName>09 00 AM - 09 30 AM</fullName>
            </value>
            <value>
                <fullName>09 30 AM - 10 00 AM</fullName>
            </value>
            <value>
                <fullName>10 00 AM - 10 30 AM</fullName>
            </value>
            <value>
                <fullName>10 30 AM - 11 00 AM</fullName>
            </value>
            <value>
                <fullName>11 00 AM - 11 30 AM</fullName>
            </value>
            <value>
                <fullName>11 30 AM - 12 00 PM</fullName>
            </value>
            <value>
                <fullName>12 00 PM - 12 30 PM</fullName>
            </value>
            <value>
                <fullName>12 30 PM - 01 30 PM</fullName>
            </value>
            <value>
                <fullName>01 00 PM - 01 00 PM</fullName>
            </value>
            <value>
                <fullName>01 30 PM - 02 00 PM</fullName>
            </value>
            <value>
                <fullName>02 00 PM - 02 30 PM</fullName>
            </value>
            <value>
                <fullName>02 30 PM - 03 00 PM</fullName>
            </value>
            <value>
                <fullName>03 00 PM - 03 30 PM</fullName>
            </value>
            <value>
                <fullName>03 30 PM - 04 00 PM</fullName>
            </value>
            <value>
                <fullName>04 00 PM - 04 30 PM</fullName>
            </value>
            <value>
                <fullName>04 30 PM - 05 00 PM</fullName>
            </value>
            <value>
                <fullName>05 00 PM - 05 30 PM</fullName>
            </value>
            <value>
                <fullName>05 30 PM - 06 00 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Survey_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Start_Date__c</fullName>
    <description>This will be the date referenced by Survey workflow to sent out the business outcome survey notification after 30, 60 and 90 days</description>
    <inlineHelpText>This will be the date referenced by Survey workflow to sent out the business outcome survey notification after 30, 60 and 90 days</inlineHelpText>
    <label>Survey Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Interaction__c/recordTypes/Consultation.recordType-meta.xml
<RecordType>
    <fullName>Consultation</fullName>
    <active>true</active>
    <description>Interaction for providing new Business Consultation</description>
    <label>Consultation</label>
</RecordType>

force-app/main/default/classes/Test_InteractionTriggerAction.cls
@isTest
private class Test_InteractionTriggerAction{
        
     static testMethod void createTestData(){
     
     RecordType rt = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
        
        //Below code create list of Account records
        List<Account> accList = new List<Account>(); 
        for(Integer i=0;i<6;i++){
            Account acc = new Account();
            acc.Name='City Of Toronto';
            acc.BillingCountry = 'Canada';
            acc.ShippingCountry = 'Canada';
            acc.RecordTypeId = rt.Id;
            accList.add(acc);
        }
        
        insert accList ;
        
       //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
        for (Integer j=0;j<accList.size();j++) {
            Account acct = accList[j];            
            // For each account just inserted, add contacts
            for (Integer k=0;k<5;k++) {
                conList.add(new Contact(firstname='Test'+k,
                                     lastname='Test'+k,
                                     Email='test@cityoftoronto.com'+k,
                                     AccountId=acct.Id));
            }
        }
        // Insert all contacts for all accounts
        insert conList;
        
        //Below code create list of Interaction records
        Date myDate = Date.newInstance(2015,10,17);
        List<Interaction__c > interList = new List<Interaction__c >();
        for (Integer k=0;k<4;k++) {
            interList.add(new Interaction__c (Contact__c = conList[0].Id,
                                              Account__c = accList[0].Id,
                                              Business_Status__c= 'Existing',
                                              Gender__c= 'Male',
                                              Meeting_Date__c = myDate, 
                                              Advisor_Lookup__c= UserInfo.getUserId(),
                                              Meeting_Status__c ='Requested', 
                                              Meetingtime__c ='09 00 AM - 10 00 AM',
                                              Location__c = 'City Hall'));
        }                                 
        insert interList;
        interList[0].Meeting_Status__c='Confirmed';
        interList[1].Meeting_Status__c='Confirmed';
        update interList;
        interList[1].Meeting_Status__c='Cancelled by Client';
        update interList[1];
    
    }
    
    static testMethod void createTestData2(){
        
        RecordType rtBus = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
        RecordType rtPerson = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='PersonAccount'];
        
        Id RecordTypeIdConsInteraction = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Consultation').getRecordTypeId();
        Id RecordTypeIdComIntInteraction = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Company Intelligence').getRecordTypeId();
        //Below code create list of Account records Business and Person Account
        List<Account> accList = new List<Account>(); 
        
        accList.add(new Account(Name='City Of Toronto',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client'));
        accList.add(new Account(FirstName='City Of Toronto ',LastName='Person Account', PersonEmail = 'city11@toronto.ca',PersonMailingCountry = 'Canada', PersonOtherCountry = 'Canada',RecordTypeId = rtPerson.Id));
        accList.add(new Account(FirstName='City Of Oakville ',LastName='Person Account', PersonEmail = 'city12@toronto.ca',PersonMailingCountry = 'Canada', PersonOtherCountry = 'Canada',RecordTypeId = rtPerson.Id));
        insert accList ;
        
        //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
           Account acct = accList[0];            
            // For each account just inserted, add contacts
            for (Integer k=0;k<6;k++) {
                conList.add(new Contact(firstname='Test'+k,
                                     lastname='Test'+k,
                                     Email='test@cityoftoronto.com'+k,
                                     AccountId=acct.Id));
            }
        // Insert all contacts for all accounts
        insert conList;
        
        //Business Outcome Survey Sample Records
        List<Client_FollowUp__c> busOutList = new List<Client_FollowUp__c >();
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[0].Id,Survey_Start_Date__c = system.today()-12,Engagement_Type__c='Consultation Interaction'));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[1].Id,Survey_Start_Date__c = system.today()-12,Engagement_Type__c='Online Registration'));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[2].Id,Survey_Start_Date__c = system.today()+12,Engagement_Type__c=''));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[3].Id,Survey_Start_Date__c = system.today()-12,Engagement_Type__c='Company Intelligence Interaction'));
        
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[4].Id,Survey_Start_Date__c = system.today()+12,Engagement_Type__c=null));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[5].Id,Survey_Start_Date__c = system.today()-12,Engagement_Type__c='Online Registration'));
        insert busOutList;
        List<Interaction__c > interList = new List<Interaction__c >();

        interList.add(new Interaction__c(Contact__c = conList[0].Id, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdConsInteraction,Follow_Up_Consultation_Type__c ='Follow-Up for Online clients',Location__c='City Hall', Meeting_Status__c = 'Requested',Date_of_Contact__c = date.today(),Advisor__c= 'Funmi',Meeting_Date__c=date.today()));
        
        interList.add(new Interaction__c(Contact__c = conList[1].Id, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdConsInteraction,Follow_Up_Consultation_Type__c ='Follow-Up for Online clients',Location__c='City Hall', Meeting_Status__c = 'Requested',Date_of_Contact__c = date.today(),Advisor__c= 'Funmi',Meeting_Date__c=date.today()));
        
        interList.add(new Interaction__c(Contact__c = conList[2].Id, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdConsInteraction,Follow_Up_Consultation_Type__c ='Follow-Up for Online clients',Location__c='City Hall', Meeting_Status__c = 'Requested',Date_of_Contact__c = date.today(),Advisor__c= 'Funmi',Meeting_Date__c=date.today()));
        
        Contact consCon =[Select Id, AccountId from Contact Where AccountId =:accList[1].Id];
        interList.add(new Interaction__c(Contact__c = consCon.Id, Account__c = accList[1].Id,RecordTypeId=RecordTypeIdConsInteraction,Follow_Up_Consultation_Type__c ='Follow-Up for Online clients',Location__c='City Hall', Meeting_Status__c = 'Requested',Date_of_Contact__c = date.today(),Advisor_Lookup__c= UserInfo.getUserId()));
        
        Contact con =[Select Id, AccountId from Contact Where AccountId =:accList[2].Id];
        interList.add(new Interaction__c(Contact__c = con.Id, Account__c = accList[2].Id,RecordTypeId=RecordTypeIdComIntInteraction,Purpose_of_the_Interaction__c = 'Business Development - Market Development**'));
        
        
        interList.add(new Interaction__c(Contact__c = accList[0].PersonContactId__c, Account__c = accList[2].Id,RecordTypeId=RecordTypeIdConsInteraction,Follow_Up_Consultation_Type__c ='Follow-Up for Online clients',Location__c='City Hall', Meeting_Status__c = 'Requested',Date_of_Contact__c = date.today(),Advisor_Lookup__c= UserInfo.getUserId()));
        
        interList.add(new Interaction__c(Contact__c = conList[3].Id, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdComIntInteraction,Purpose_of_the_Interaction__c = 'Business Development - Market Development**'));
        interList.add(new Interaction__c(Contact__c = conList[4].Id, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdComIntInteraction,Purpose_of_the_Interaction__c = 'Business Development - Market Development**'));
        interList.add(new Interaction__c(Contact__c = conList[5].Id, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdComIntInteraction,Purpose_of_the_Interaction__c = 'Business Development - Market Development**'));
        
       
        try{
            insert interList;
            interList[0].Meeting_Status__c='Confirmed';
            interList[1].Meeting_Status__c='Confirmed';
            update interList;
        
        }
        catch (DMLException e) {
            
        }
    }
    static testMethod void createTestData3(){
        
        RecordType rtBus = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
        RecordType rtPerson = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='PersonAccount'];
        
        Id RecordTypeIdConsInteraction = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Consultation').getRecordTypeId();
        Id RecordTypeIdComIntInteraction = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Company Intelligence').getRecordTypeId();
        //Below code create list of Account records Business and Person Account
        List<Account> accList = new List<Account>(); 
        
        accList.add(new Account(Name='City Of Toronto 1',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client'));
        accList.add(new Account(FirstName='City Of Toronto 3',LastName='Person Account', PersonEmail = 'city11@toronto.ca',PersonMailingCountry = 'Canada', PersonOtherCountry = 'Canada',RecordTypeId = rtPerson.Id));
        accList.add(new Account(FirstName='City Of Toronto 4',LastName='Person Account', PersonEmail = 'city11@toronto.ca',PersonMailingCountry = 'Canada', PersonOtherCountry = 'Canada',RecordTypeId = rtPerson.Id));
        insert accList ;
        
        //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
           Account acct = accList[0];            
            // For each account just inserted, add contacts
            for (Integer k=0;k<6;k++) {
                conList.add(new Contact(firstname='Test'+k,
                                     lastname='Test'+k,
                                     Email='test@cityoftoronto.com'+k,
                                     AccountId=acct.Id));
            }
        conList.add(new Contact(firstname='Test'+7,lastname='Test'+7,Email='test@cityoftoronto.com'+7, AccountId=accList[1].Id));   
        // Insert all contacts for all accounts
        insert conList;
        List<Interaction__c > interList = new List<Interaction__c>();
        interList.add(new Interaction__c(Contact__c = conList[0].Id, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdConsInteraction,Follow_Up_Consultation_Type__c ='Follow-Up for Online clients',Location__c='City Hall', Meeting_Status__c = 'Requested',Date_of_Contact__c = date.today(),Advisor__c= 'Funmi',Meeting_Date__c=date.today()));
        interList.add(new Interaction__c(Contact__c = conList[1].Id, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdComIntInteraction,Purpose_of_the_Interaction__c = 'Business Development - Expansion Assistance**'));
        interList.add(new Interaction__c(Contact__c = conList[2].Id, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdComIntInteraction,Purpose_of_the_Interaction__c = 'Business Development - Expansion Assistance**'));
//      interList.add(new Interaction__c(Contact__c = accList[2].PersonContactId__c, Account__c = accList[3].Id,RecordTypeId=RecordTypeIdComIntInteraction,Purpose_of_the_Interaction__c = 'Business Development - Expansion Assistance**'));
            
        try{
            insert interList;
            interList[0].Meeting_Status__c='Confirmed';
            update interList;
            interList[1].Account__c = accList[1].Id;
            update interList;
        }
        catch (DMLException e) {
        }
    } 
    static testMethod void createTestData4(){
       
        RecordType rtPerson = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='PersonAccount'];
        Id RecordTypeIdConsInteraction = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Consultation').getRecordTypeId();
       
       //Below code create list of  Person Account
        List<Account> accList = new List<Account>(); 
        
        accList.add(new Account(FirstName='City Of Toronto 3',LastName='Person Account', PersonEmail = 'city11@toronto.com',PersonMailingCountry = 'Canada', PersonOtherCountry = 'Canada',RecordTypeId = rtPerson.Id));
        accList.add(new Account(FirstName='City Of Toronto 4',LastName='Person Account', PersonEmail = 'city11@toronto.ca',PersonMailingCountry = 'Canada', PersonOtherCountry = 'Canada',RecordTypeId = rtPerson.Id));
        insert accList ;
        
   
        Date myDate = Date.newInstance(2015,10,17);
        List<Interaction__c > interList = new List<Interaction__c>();
        interList.add(new Interaction__c(Contact__c = accList[0].PersonContactId__c, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdConsInteraction));
        
        try{
            database.Insert(interList);
        }
        catch (DMLException e) {
        }
    }   
}