force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This is the ability to classify the types of organizations.
It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.
Options are:
Business Client - a business we are working with.
Business Prospect - a business or investment we are trying to work with.
Service Provider - a business that we purchase goods or services from.
Partner - an organization that we work with.</description>
    <inlineHelpText>It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Client</fullName>
                <default>true</default>
                <label>Business Client</label>
            </value>
            <value>
                <fullName>Business Prospect</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Continent__c.field-meta.xml
<CustomField>
    <fullName>Physical_Continent__c</fullName>
    <description>The continent value in this field is corresponding to country.</description>
    <label>Physical Continent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Antartica</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia/Europe</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <description>Organization accounts with multiple contacts.</description>
    <label>Business Account</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/Financial_Incentive__c.object-meta.xml
<CustomObject>
    <description>This object will be used to build various grant process within salesforce application to various department like ES, BIA and BGS</description>
    <label>Financial Incentive</label>
    <nameField>
        <displayFormat>FIN-{YYYY}-{000000}</displayFormat>
        <label>Financial Incentive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Incentives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Incentive__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Incentives</relationshipLabel>
    <relationshipName>Financial_Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Acknowledgement_Signature_of_Chair__c.field-meta.xml
<CustomField>
    <fullName>Acknowledgement_Signature_of_Chair__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Acknowledgement that BIA Board is aware of the Application</description>
    <inlineHelpText>Acknowledgement that BIA Board is aware of the Application</inlineHelpText>
    <label>Acknowledgement - Signature of Chair</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Financial Incentives</relationshipLabel>
    <relationshipName>Financial_Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Has_Application_been_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Has_Application_been_Submitted__c</fullName>
    <label>Has Application been Submitted</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Application_submitted_by__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Permission_to_Bind_Corporation__c.field-meta.xml
<CustomField>
    <fullName>Permission_to_Bind_Corporation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permission to Bind Corporation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Permission_to_Photograph_Individual__c.field-meta.xml
<CustomField>
    <fullName>Permission_to_Photograph_Individual__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permission to Photograph Individual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Permission_to_Photograph_Video_Building__c.field-meta.xml
<CustomField>
    <fullName>Permission_to_Photograph_Video_Building__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permission to Photograph or Video Building</description>
    <inlineHelpText>Permission to Photograph or Video Building</inlineHelpText>
    <label>Permission to Photograph/Video Building</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Personal_Information_Declaration__c.field-meta.xml
<CustomField>
    <fullName>Personal_Information_Declaration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>I declare the information provided in this application to be true,complete and accurate to the best of my ability</description>
    <inlineHelpText>I declare the information provided in this application to be true,complete and accurate to the best of my ability</inlineHelpText>
    <label>Personal Information Declaration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Property_Street__c.field-meta.xml
<CustomField>
    <fullName>Property_Street__c</fullName>
    <description>Property Street Address</description>
    <inlineHelpText>Property Street Address</inlineHelpText>
    <label>Property Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Pending Extension</fullName>
            </value>
            <value>
                <fullName>Extension Approved</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved by GM</fullName>
            </value>
            <value>
                <fullName>Approved by City Council</fullName>
            </value>
            <value>
                <fullName>With Legal</fullName>
            </value>
            <value>
                <fullName>Legal Agreement Completed</fullName>
            </value>
            <value>
                <fullName>Reassessment</fullName>
            </value>
            <value>
                <fullName>Amending Agreement</fullName>
            </value>
            <value>
                <fullName>Compliance/Payment Review</fullName>
            </value>
            <value>
                <fullName>Withdrawn/Inactive</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Application Declined</fullName>
            </value>
            <value>
                <fullName>Extension Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Eligibility Criteria not Met</fullName>
            </value>
            <value>
                <fullName>Interview Required</fullName>
            </value>
            <value>
                <fullName>Declined after Interview</fullName>
            </value>
            <value>
                <fullName>Approved for Training</fullName>
            </value>
            <value>
                <fullName>Declined for Training</fullName>
            </value>
            <value>
                <fullName>Training Completed</fullName>
            </value>
            <value>
                <fullName>Business Plan Received</fullName>
            </value>
            <value>
                <fullName>Score Card Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/BIA_Commercial_Industrial_Facade_and_Property_Improvement.recordType-meta.xml
<RecordType>
    <fullName>BIA_Commercial_Industrial_Facade_and_Property_Improvement</fullName>
    <active>true</active>
    <description>This type is specifically applicable to BIA Commercial - Industrial Facade and Property Improvement for BIA Accounts</description>
    <label>BIA Commercial - Industrial Facade and Property Improvement</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/BIA_Innovation_Fund.recordType-meta.xml
<RecordType>
    <fullName>BIA_Innovation_Fund</fullName>
    <active>true</active>
    <description>This type is specifically applicable to BIA Innovation Fund and Property Improvement for BIA Accounts</description>
    <label>BIA Innovation Fund</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/BIA_Leadership_Fund.recordType-meta.xml
<RecordType>
    <fullName>BIA_Leadership_Fund</fullName>
    <active>true</active>
    <description>This type is specifically applicable to BIA Leadership Fund and Property Improvement for BIA Accounts</description>
    <label>BIA Leadership Fund</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/BIA_Outside_Mural_and_Street_Art_Grant.recordType-meta.xml
<RecordType>
    <fullName>BIA_Outside_Mural_and_Street_Art_Grant</fullName>
    <active>true</active>
    <description>This type is specifically applicable to BIA Outside Mural and Street Art Grant and Property Improvement for BIA Accounts</description>
    <label>BIA Outside Mural and Street Art</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/BIA_Streetscape_Master_Plan_Funding.recordType-meta.xml
<RecordType>
    <fullName>BIA_Streetscape_Master_Plan_Funding</fullName>
    <active>true</active>
    <description>This type is specifically applicable to BIA Streetscape Master Plan Funding and Property Improvement for BIA Accounts</description>
    <label>BIA Streetscape Master Plan Funding</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/Business_Incubation_Grant.recordType-meta.xml
<RecordType>
    <fullName>Business_Incubation_Grant</fullName>
    <active>true</active>
    <description>This type is used for creating Grant records applicable only for Business Incubation i.e. a grant to a business incubator.</description>
    <label>Business Incubation Grant</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/Event_Sponsorship_Grant.recordType-meta.xml
<RecordType>
    <fullName>Event_Sponsorship_Grant</fullName>
    <active>true</active>
    <description>This type is used for creating Grant records applicable only for Event Sponsorship for an external event focused on the business community</description>
    <label>Event Sponsorship Grant</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/IMIT.recordType-meta.xml
<RecordType>
    <fullName>IMIT</fullName>
    <active>true</active>
    <description>This is used for creating Financial Incentive of IMIT Type</description>
    <label>IMIT</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/Sector_Grant.recordType-meta.xml
<RecordType>
    <fullName>Sector_Grant</fullName>
    <active>true</active>
    <description>This Record type is only applicable to various Grant related to sector like Event. Project and Membership</description>
    <label>Sector Grant</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/Starter_Company_Grant.recordType-meta.xml
<RecordType>
    <fullName>Starter_Company_Grant</fullName>
    <active>true</active>
    <description>Applicable to Starter Company Program</description>
    <label>Starter Company Grant</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>Information about individual people.</description>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/Test_FinancialIncentiveTriggerActions.cls
@isTest
public class Test_FinancialIncentiveTriggerActions{
    
    static testMethod void createTestData1(){
            
        RecordType rtBus = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
        RecordType rtPerson = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='PersonAccount'];
        
        List<RecordType> finRTList = [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType WHERE SobjectType = 'Financial_Incentive__c'];
        
        
        Map<String,String> finRTMap = new Map<String,String>();
        for(RecordType rt: [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType WHERE SobjectType = 'Financial_Incentive__c']){
            finRTMap.put(rt.DeveloperName,rt.Id); 
        }
        //Below code create list of Account records Business and Person Account
        List<Account> accList = new List<Account>(); 
        
        accList.add(new Account(Name='City Of Toronto 1',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='North America'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'India', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='Asia'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'Mexico', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='South America'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'France', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='Europe'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='North America'));
        
        insert accList;
        //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
            // For each account just inserted, add contacts
            for (Integer k=0;k<4;k++) {
                conList.add(new Contact(firstname='Test'+k,
                                     lastname='Test'+k,
                                     Email='test@cityoftoronto.com'+k,
                                     AccountId=accList[k].Id));
            }
        conList.add(new Contact(firstname='Test7', lastname='Test7', Email='test@cityoftoronto.com7',AccountId=accList[0].Id));
        // Insert all contacts for all accounts
        insert conList;
        
        List<Financial_Incentive__c> finIncList = new List<Financial_Incentive__c >();

        //BIA CFI Record
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[0].Id, Account__c = accList[0].Id,RecordTypeId=finRTMap.get('BIA_Commercial_Industrial_Facade_and_Property_Improvement'),Status__c='Draft',Personal_Information_Declaration__c=true,Permission_to_Bind_Corporation__c=true,Permission_to_Photograph_Video_Building__c=true));
        //BIA Innovation Fund Record
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[1].Id, Account__c = accList[1].Id,RecordTypeId=finRTMap.get('BIA_Innovation_Fund'),Status__c='Draft',Personal_Information_Declaration__c=true,Acknowledgement_Signature_of_Chair__c=true));
        //BIA Leadersip Record
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[2].Id, Account__c = accList[2].Id,RecordTypeId=finRTMap.get('BIA_Leadership_Fund'),Status__c='Draft',Personal_Information_Declaration__c=true,Permission_to_Photograph_Individual__c=true));
        //BIA Outside Mural Record
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[3].Id, Account__c = accList[3].Id,RecordTypeId=finRTMap.get('BIA_Outside_Mural_and_Street_Art_Grant'),Status__c='Draft',Personal_Information_Declaration__c=true,Permission_to_Photograph_Video_Building__c=true,Acknowledgement_Signature_of_Chair__c=true));
        //BIA Streetscape Record
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[0].Id, Account__c = accList[0].Id,RecordTypeId=finRTMap.get('BIA_Streetscape_Master_Plan_Funding'),Status__c='Draft',Personal_Information_Declaration__c=true,Acknowledgement_Signature_of_Chair__c=true));
        //Business Incubation Grant Record
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[1].Id, Account__c = accList[1].Id,RecordTypeId=finRTMap.get('Business_Incubation_Grant'),Status__c='Draft'));
        //Event Grant Record
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[2].Id, Account__c = accList[2].Id,RecordTypeId=finRTMap.get('Event_Sponsorship_Grant'),Status__c='Draft'));
        //Event Grant Record
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[2].Id, Account__c = accList[2].Id,RecordTypeId=finRTMap.get('Event_Sponsorship_Grant'),Status__c='Submitted'));
        //Sector Grant Record
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[3].Id, Account__c = accList[3].Id,RecordTypeId=finRTMap.get('Sector_Grant'),Status__c='Draft'));
        //
        //Starter Company Grant Record
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[3].Id, Account__c = accList[3].Id,RecordTypeId=finRTMap.get('Starter_Company_Grant'),Status__c='Draft'));
        //IMIT Record   
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[1].Id, Account__c = accList[1].Id,Property_Street__c='100 Queen Street',RecordTypeId=finRTMap.get('IMIT'),Status__c='Draft',Has_Application_been_Submitted__c='Yes'));
        //IMIT Record   
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[2].Id, Account__c = accList[2].Id,RecordTypeId=finRTMap.get('IMIT'),Status__c='Submitted',Has_Application_been_Submitted__c='Yes'));
        
        insert finIncList;
        
        
        finIncList[0].Status__c='Application Declined';
        finIncList[1].Status__c='Extension Approved';
        finIncList[3].Status__c='Approved';
        finIncList[4].Status__c='Pending Approval';
        finIncList[5].Status__c='Completed';
        finIncList[7].Status__c='In Review';
        finIncList[9].Status__c='Compliance/Payment Review';
        finIncList[10].Status__c='Approved by GM';
        try{
            update finIncList;
            finIncList[8].Contact__c = conList[4].Id;
            update finIncList;
            
        }
        catch (DMLException ex) {
        System.debug('****** Exception Caught :   '+ex.getMessage());            
        }
    }
}