force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This is the ability to classify the types of organizations.
It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.
Options are:
Business Client - a business we are working with.
Business Prospect - a business or investment we are trying to work with.
Service Provider - a business that we purchase goods or services from.
Partner - an organization that we work with.</description>
    <inlineHelpText>It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Client</fullName>
                <default>true</default>
                <label>Business Client</label>
            </value>
            <value>
                <fullName>Business Prospect</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Continent__c.field-meta.xml
<CustomField>
    <fullName>Physical_Continent__c</fullName>
    <description>The continent value in this field is corresponding to country.</description>
    <label>Physical Continent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Antartica</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia/Europe</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <description>Organization accounts with multiple contacts.</description>
    <label>Business Account</label>
</RecordType>

force-app/main/default/objects/International_Agreement__c/International_Agreement__c.object-meta.xml
<CustomObject>
    <description>This custom object will be used to capture details related to various Agreement related to International mission.</description>
    <label>International Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>International Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/International_Agreement__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/International_Agreement__c/fields/Agreement_Country__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Country__c</fullName>
    <label>Agreement Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/International_Agreement__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <description>Partnership has no expiry date.</description>
    <inlineHelpText>Partnership has no expiry date.</inlineHelpText>
    <label>Agreement Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Friendship</fullName>
            </value>
            <value>
                <fullName>MOU</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/International_Agreement__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/International_Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Aborted can be used if the interest to complete an agreement has ended or if both party signatures are not received, or, agreement terminated prior term by either of the parties</description>
    <inlineHelpText>Aborted can be used if the interest to complete an agreement has ended or if both party signatures are not received, or, agreement terminated prior term by either of the parties</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Agreement</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>External Review</fullName>
            </value>
            <value>
                <fullName>Internal Review</fullName>
            </value>
            <value>
                <fullName>Final Review</fullName>
            </value>
            <value>
                <fullName>External Approval</fullName>
            </value>
            <value>
                <fullName>Internal Approval</fullName>
            </value>
            <value>
                <fullName>External Signature Received</fullName>
            </value>
            <value>
                <fullName>Internal Signature Received</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>Information about individual people.</description>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/Test_AgreementTriggerActions.cls
@isTest
public class Test_AgreementTriggerActions{
    
    static testMethod void createTestData(){
            
        RecordType rtBus = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
        RecordType rtPerson = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='PersonAccount'];
        
        
        //Below code create list of Account records Business and Person Account
        List<Account> accList = new List<Account>(); 
        
        accList.add(new Account(Name='City Of Toronto 1',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='North America'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'India', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='Asia'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'Mexico', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='South America'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'France', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='Europe'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='North America'));
        
        insert accList;
        //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
            // For each account just inserted, add contacts
            for (Integer k=0;k<4;k++) {
                conList.add(new Contact(firstname='Test'+k,
                                     lastname='Test'+k,
                                     Email='test@cityoftoronto.com'+k,
                                     AccountId=accList[k].Id));
            }
        conList.add(new Contact(firstname='Test7', lastname='Test7', Email='test@cityoftoronto.com7',AccountId=accList[0].Id));
        // Insert all contacts for all accounts
        insert conList;
        
        Profile pfl = [select id from profile where name='Standard User'];     
        List<User> lstUser = new List<User>();
        lstUser.add(new User(alias = 'db', email='Vanna@toronto.test.ca', emailencodingkey= 'UTF-8', FirstName='Vanna', lastname='Petropoulos',languagelocalekey='en_US',localesidkey='en_US', profileid = pfl.Id,country='United States',CommunityNickname = 'u1',timezonesidkey='America/Los_Angeles',username='Vanna@toronto.test.ca'));
        lstUser.add(new User(alias = 'dbm', email='Connie@toronto.test.ca',emailencodingkey='UTF-8', FirstName='Connie', lastname='Fusillo' , languagelocalekey='en_US',localesidkey='en_US', profileid = pfl.Id,  country='United States',CommunityNickname = 'u2',timezonesidkey='America/Los_Angeles',username='Connie@toronto.test.ca'));
        lstUser.add(new User(alias = 'dbm', email='Linda@toronto.test.ca',emailencodingkey='UTF-8', FirstName='Linda', lastname='Fava' , languagelocalekey='en_US',localesidkey='en_US', profileid = pfl.Id,  country='United States',CommunityNickname = 'u3',timezonesidkey='America/Los_Angeles',username='Linda@toronto.test.ca'));
        lstUser.add(new User(alias = 'dbm', email='Susana@toronto.test.ca',emailencodingkey='UTF-8', FirstName='Susana', lastname='Vaz' , languagelocalekey='en_US',localesidkey='en_US', profileid = pfl.Id,  country='United States',CommunityNickname = 'u4',timezonesidkey='America/Los_Angeles',username='Susana@toronto.test.ca'));
        insert lstUser;
    
        List<International_Agreement__c > agreementList = new List<International_Agreement__c >();
      
        agreementList.add(new International_Agreement__c (Contact_Name__c = conList[0].Id, Account_Name__c = accList[0].Id,Agreement_Country__c='India',Agreement_Type__c='Partnership',Status__c='Pre Agreement'));
        agreementList.add(new International_Agreement__c (Contact_Name__c = conList[1].Id, Account_Name__c = accList[1].Id,Agreement_Country__c='Germany',Agreement_Type__c='Partnership',Status__c='Pre Agreement'));
        agreementList.add(new International_Agreement__c (Contact_Name__c = conList[2].Id, Account_Name__c = accList[2].Id,Agreement_Country__c='Canada',Agreement_Type__c='Partnership',Status__c='Pre Agreement'));
        agreementList.add(new International_Agreement__c (Contact_Name__c = conList[3].Id, Account_Name__c = accList[3].Id,Agreement_Country__c='Mexico',Agreement_Type__c='Partnership',Status__c='Pre Agreement'));
            
        try{
            insert agreementList;
            agreementList[0].Agreement_Country__c='Mexico';
            agreementList[0].Account_Name__c = accList[3].Id;
            update agreementList;
        }
        catch (DMLException e) {
            
        }
    }    
}