force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This is the ability to classify the types of organizations.
It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.
Options are:
Business Client - a business we are working with.
Business Prospect - a business or investment we are trying to work with.
Service Provider - a business that we purchase goods or services from.
Partner - an organization that we work with.</description>
    <inlineHelpText>It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Client</fullName>
                <default>true</default>
                <label>Business Client</label>
            </value>
            <value>
                <fullName>Business Prospect</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Continent__c.field-meta.xml
<CustomField>
    <fullName>Physical_Continent__c</fullName>
    <description>The continent value in this field is corresponding to country.</description>
    <label>Physical Continent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Antartica</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia/Europe</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <description>Organization accounts with multiple contacts.</description>
    <label>Business Account</label>
</RecordType>

force-app/main/default/objects/Financial_Incentive__c/Financial_Incentive__c.object-meta.xml
<CustomObject>
    <description>This object will be used to build various grant process within salesforce application to various department like ES, BIA and BGS</description>
    <label>Financial Incentive</label>
    <nameField>
        <displayFormat>FIN-{YYYY}-{000000}</displayFormat>
        <label>Financial Incentive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Incentives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Incentive__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Incentives</relationshipLabel>
    <relationshipName>Financial_Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Financial Incentives</relationshipLabel>
    <relationshipName>Financial_Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Has_Application_been_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Has_Application_been_Submitted__c</fullName>
    <label>Has Application been Submitted</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Application_submitted_by__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Property_Street__c.field-meta.xml
<CustomField>
    <fullName>Property_Street__c</fullName>
    <description>Property Street Address</description>
    <inlineHelpText>Property Street Address</inlineHelpText>
    <label>Property Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Pending Extension</fullName>
            </value>
            <value>
                <fullName>Extension Approved</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved by GM</fullName>
            </value>
            <value>
                <fullName>Approved by City Council</fullName>
            </value>
            <value>
                <fullName>With Legal</fullName>
            </value>
            <value>
                <fullName>Legal Agreement Completed</fullName>
            </value>
            <value>
                <fullName>Reassessment</fullName>
            </value>
            <value>
                <fullName>Amending Agreement</fullName>
            </value>
            <value>
                <fullName>Compliance/Payment Review</fullName>
            </value>
            <value>
                <fullName>Withdrawn/Inactive</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Application Declined</fullName>
            </value>
            <value>
                <fullName>Extension Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Eligibility Criteria not Met</fullName>
            </value>
            <value>
                <fullName>Interview Required</fullName>
            </value>
            <value>
                <fullName>Declined after Interview</fullName>
            </value>
            <value>
                <fullName>Approved for Training</fullName>
            </value>
            <value>
                <fullName>Declined for Training</fullName>
            </value>
            <value>
                <fullName>Training Completed</fullName>
            </value>
            <value>
                <fullName>Business Plan Received</fullName>
            </value>
            <value>
                <fullName>Score Card Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Incentive__c/recordTypes/IMIT.recordType-meta.xml
<RecordType>
    <fullName>IMIT</fullName>
    <active>true</active>
    <description>This is used for creating Financial Incentive of IMIT Type</description>
    <label>IMIT</label>
</RecordType>

force-app/main/default/objects/IMIT_Payment__c/IMIT_Payment__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture more than one payment details applicable to IMIT Grant Financial Incentive.</description>
    <label>IMIT Payment</label>
    <nameField>
        <displayFormat>IMIPAY-{000000}</displayFormat>
        <label>IMIT Payment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IMIT Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IMIT_Payment__c/fields/Financial_Incentive__c.field-meta.xml
<CustomField>
    <fullName>Financial_Incentive__c</fullName>
    <label>Financial Incentive</label>
    <referenceTo>Financial_Incentive__c</referenceTo>
    <relationshipLabel>IMIT Payments</relationshipLabel>
    <relationshipName>IMIT_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IMIT_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Compliance Preparation</fullName>
                <default>true</default>
                <label>Compliance Preparation</label>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>Compliance Approved</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_IMITPaymentTriggerActions.cls
@isTest
public class Test_IMITPaymentTriggerActions{
    
    static testMethod void createTestData(){
            
        RecordType rtBus = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
        
        List<RecordType> finRTList = [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType WHERE SobjectType = 'Financial_Incentive__c'];
        
        
        Map<String,String> finRTMap = new Map<String,String>();
        for(RecordType rt: [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType WHERE SobjectType = 'Financial_Incentive__c' AND DeveloperName = 'IMIT']){
            finRTMap.put(rt.DeveloperName,rt.Id); 
        }
        //Below code create list of Account records Business and Person Account
        List<Account> accList = new List<Account>(); 
        
        accList.add(new Account(Name='City Of Toronto 1',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='North America'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'India', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='Asia'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'Mexico', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='South America'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'France', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='Europe'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client',Physical_Continent__c ='North America'));
        
        insert accList;
        //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
            // For each account just inserted, add contacts
            for (Integer k=0;k<4;k++) {
                conList.add(new Contact(firstname='Test'+k,
                                     lastname='Test'+k,
                                     Email='test@cityoftoronto.com'+k,
                                     AccountId=accList[k].Id));
            }
        // Insert all contacts for all accounts
        insert conList;
        
        List<Financial_Incentive__c> finIncList = new List<Financial_Incentive__c >();

        //IMIT Record   
        finIncList.add(new Financial_Incentive__c (Contact__c = conList[1].Id, Account__c = accList[1].Id,Property_Street__c='100 Queen Street',RecordTypeId=finRTMap.get('IMIT'),Status__c='Draft',Has_Application_been_Submitted__c='Yes'));
        insert finIncList;
        
        List<IMIT_Payment__c> imitPaymentList = new List<IMIT_Payment__c>();
        imitPaymentList.add(new IMIT_Payment__c(Financial_Incentive__c= finIncList[0].Id, Payment_Status__c= 'Compliance Preparation'));
        imitPaymentList.add(new IMIT_Payment__c(Financial_Incentive__c= finIncList[0].Id, Payment_Status__c= 'Compliance Preparation'));
        
        insert imitPaymentList;
        imitPaymentList[0].Payment_Status__c = 'Terminated';
        imitPaymentList[1].Payment_Status__c = 'Invalid Status';
        try{
            Database.update(imitPaymentList);
        }
        catch (DMLException e) {
            
        }
                    
    }    
}