force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This is the ability to classify the types of organizations.
It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.
Options are:
Business Client - a business we are working with.
Business Prospect - a business or investment we are trying to work with.
Service Provider - a business that we purchase goods or services from.
Partner - an organization that we work with.</description>
    <inlineHelpText>It identifies if this account is a true client or if the account is a possible prospect that we have contacted but not established a firm relationship with.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Client</fullName>
                <default>true</default>
                <label>Business Client</label>
            </value>
            <value>
                <fullName>Business Prospect</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <description>Organization accounts with multiple contacts.</description>
    <label>Business Account</label>
</RecordType>

force-app/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <description>This Custom Object will be used for capturing Issue of Opportunity and Problem type i.e related to various parent object records like Account, Contact, Interaction, Initiative, Financial Incentive etc</description>
    <label>Issue</label>
    <nameField>
        <displayFormat>ISSUE-{YYYY}-{000000}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Date_Raised__c.field-meta.xml
<CustomField>
    <fullName>Date_Raised__c</fullName>
    <description>The date the issue was identified/raised</description>
    <inlineHelpText>The date the issue was identified/raised</inlineHelpText>
    <label>Date Raised</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>Information about individual people.</description>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/Test_IssueTriggerActions.cls
@isTest
public class Test_IssueTriggerActions{
    
    static testMethod void createTestData(){
        RecordType rtBus = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
        RecordType rtPerson = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='PersonAccount'];
        
        //Below code create list of Account records Business and Person Account
        List<Account> accList = new List<Account>(); 
        
        accList.add(new Account(Name='City Of Toronto 1',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client'));
        accList.add(new Account(FirstName='City Of Brampton ',LastName='Person Account', PersonEmail = 'city11@toronto.ca',PersonMailingCountry = 'Canada', PersonOtherCountry = 'Canada',RecordTypeId = rtPerson.Id));
        accList.add(new Account(FirstName='City Of Oakville ',LastName='Person Account', PersonEmail = 'city12@toronto.ca',PersonMailingCountry = 'Canada', PersonOtherCountry = 'Canada',RecordTypeId = rtPerson.Id));
        insert accList ;
        
        //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
           Account acct = accList[0];            
            // For each account just inserted, add contacts
            for (Integer k=0;k<6;k++) {
                conList.add(new Contact(firstname='Test'+k,
                                     lastname='Test'+k,
                                     Email='test@cityoftoronto.com'+k,
                                     AccountId=acct.Id));
            }
        // Insert all contacts for all accounts
        insert conList;
        
        List<Issue__c> issueList = new List<Issue__c>();

        issueList.add(new Issue__c(Contact__c = conList[0].Id, Account__c = accList[0].Id,Date_Raised__c=date.today(),Priority__c='Low'));
        issueList.add(new Issue__c(Contact__c = conList[1].Id, Account__c = accList[1].Id,Date_Raised__c=date.today(),Priority__c='Low'));
        issueList.add(new Issue__c(Contact__c = conList[2].Id, Account__c = accList[2].Id));
        issueList.add(new Issue__c(Contact__c = conList[2].Id, Account__c = accList[3].Id));
        
        
        try{
            insert issueList;
        }
        catch (DMLException e) {
            
        }
    }    
}