force-app/main/default/objects/Account/fields/Automated_Account_Creation__c.field-meta.xml
<CustomField>
    <fullName>Automated_Account_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag will be used to identify the Account that are created manually in salesforce or coming through some other integrated app and based on that duplicate rule will handle the records.</description>
    <label>Automated Account Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <description>Organization accounts with multiple contacts.</description>
    <label>Business Account</label>
</RecordType>

force-app/main/default/objects/Corporate_Calling__c/Corporate_Calling__c.object-meta.xml
<CustomObject>
    <label>Corporate Calling</label>
    <nameField>
        <displayFormat>CCN-{0000}</displayFormat>
        <label>Corporate Calling Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporate Calling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Corporate_Calling__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Corporate Callings</relationshipLabel>
    <relationshipName>Corporate_Callings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CorporateCallingSubjects__c/CorporateCallingSubjects__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Corporate Calling Subjects for CorporateCallingTrigger</description>
    <label>Corporate Calling Subjects</label>
</CustomObject>

force-app/main/default/objects/CorporateCallingSubjects__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Please enter subjects separated by comma</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CCEventTest.cls
@isTest
private class CCEventTest{
    public static TestMethod void MyTest(){
        RecordType rt = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
        Account acc = new Account();
        acc.Name='City Of Toronto';
        acc.BillingCountry = 'Canada';
        acc.ShippingCountry = 'Canada';
        acc.RecordTypeId = rt.Id;
        acc.Automated_Account_Creation__c = true;
        insert acc;  
        Contact con = new Contact();
        con.LastName ='Test Contact';
        con.Email = 'Test@test.com';
        con.AccountId = acc.Id;
        insert con;
        Corporate_Calling__c cc = new Corporate_Calling__c();
        cc.Contact__c = con.Id;
        insert cc;
        CorporateCallingSubjects__c c = new CorporateCallingSubjects__c();
        c.Subject__c = 'Corporate Call, Corporate Call Meeting'; 
        insert c;     
        test.StartTest();
        
        Event ev = new Event();
        ev.WhatId = cc.Id;
        ev.DurationInMinutes = 10;
        Datetime dt = DateTime.newInstance(2017,10,8,01,02,03);
        ev.ActivityDateTime = dt;
        ev.StartDateTime = dt;
        ev.EndDateTime = dt.Addminutes(10);
        ev.Subject = 'Corporate Call';
        
        insert ev;
        
        test.StopTest();
    }
}