force-app/main/default/objects/Account/fields/Automated_Account_Creation__c.field-meta.xml
<CustomField>
    <fullName>Automated_Account_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag will be used to identify the Account that are created manually in salesforce or coming through some other integrated app and based on that duplicate rule will handle the records.</description>
    <label>Automated Account Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Board_Size__c.field-meta.xml
<CustomField>
    <fullName>Board_Size__c</fullName>
    <description>Count of Councillors is included in Board Size</description>
    <inlineHelpText>Count of Councillors is included in Board Size</inlineHelpText>
    <label>Board Size</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_Continent__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Continent__c</fullName>
    <description>The continent value in this field is corresponding to Mailing/Shipping country.</description>
    <label>Mailing Continent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Antartica</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia/Europe</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Continent__c.field-meta.xml
<CustomField>
    <fullName>Physical_Continent__c</fullName>
    <description>The continent value in this field is corresponding to country.</description>
    <label>Physical Continent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Antartica</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia/Europe</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Quorum__c.field-meta.xml
<CustomField>
    <fullName>Quorum__c</fullName>
    <label>Quorum</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Standing_Members__c.field-meta.xml
<CustomField>
    <fullName>Standing_Members__c</fullName>
    <label>Standing Members</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vacancies__c.field-meta.xml
<CustomField>
    <fullName>Vacancies__c</fullName>
    <label>Vacancies</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Country_Continent_Mapping__mdt/Account_Country_Continent_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Meta Data will be used to store mapping of Continent corresponding to each country value.</description>
    <label>Account Country Continent Mapping</label>
    <pluralLabel>Account Country Continent Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Account_Country_Continent_Mapping__mdt/fields/Continent_Name__c.field-meta.xml
<CustomField>
    <fullName>Continent_Name__c</fullName>
    <inlineHelpText>List of all applicable continent City of Toronto have business with.</inlineHelpText>
    <label>Continent Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
                <default>true</default>
                <label>Africa</label>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Asia/Europe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Country_Continent_Mapping__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <default>true</default>
                <label>AD</label>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>AX</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BJ</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountTriggerActions.cls
public class AccountTriggerActions 
{
    public static void updateContinentOnAccount( List<Account> newAccountList,Map<Id,Account> oldAccounMap){
        Account_Country_Continent_Mapping__mdt[] countryContinentList = [SELECT MasterLabel, QualifiedApiName, Continent_Name__c, Country_Code__c FROM Account_Country_Continent_Mapping__mdt];
        Map<String,String> countryContinentMap = new Map<String,String>();        
        for(Account_Country_Continent_Mapping__mdt accCont : countryContinentList){
            countryContinentMap.put(accCont.Country_Code__c,accCont.Continent_Name__c);
        }
        for(Account acc:newAccountList){
            if((oldAccounMap!=null && ((oldAccounMap.get(acc.Id).BillingCountryCode!=acc.BillingCountryCode) || ( acc.Physical_Continent__c==null && acc.BillingCountryCode!=null))) || (oldAccounMap==null && acc.BillingCountryCode!=null)){
                if(countryContinentMap.get(acc.BillingCountryCode)!=null)
                acc.Physical_Continent__c = countryContinentMap.get(acc.BillingCountryCode); 
            }
            if((oldAccounMap!=null && ((oldAccounMap.get(acc.Id).ShippingCountryCode!=acc.ShippingCountryCode)|| (acc.Mailing_Continent__c==null && acc.ShippingCountryCode!=null))) || (oldAccounMap==null && acc.ShippingCountryCode!=null)){
                if(countryContinentMap.get(acc.ShippingCountryCode)!=null)
                acc.Mailing_Continent__c = countryContinentMap.get(acc.ShippingCountryCode); 
            }
        }
    }
    public static void updateAutoAccCreationFlagOnAccount(List<Account> newAccountList,Map<Id,Account> oldAccounMap){
        String urlvaluestring; 
        system.debug('urlvaluestring++'+System.URL.getCurrentRequestUrl().getPath());
        for(Account acc:newAccountList){
            urlvaluestring =  String.valueOf(System.URL.getCurrentRequestUrl().getPath());
            system.debug('urlvaluestring++'+urlvaluestring);
            if((urlvaluestring.contains('services/data')|| urlvaluestring.contains('a0A/e') || urlvaluestring.contains('/p/process/ProcessInstanceWorkitemWizardStageManager')) && acc.Automated_Account_Creation__c == false){
                acc.Automated_Account_Creation__c = true;    
            }
        }    
    }
    public static void updateBIABoardSizeBeforeUpdate(List<Account> newAccountList,Map<Id,Account> oldAccounMap){
        
        for(Account acc : newAccountList){
            if(acc.Board_Size__c!=null && acc.Standing_Members__c!=null && acc.Board_Size__c>acc.Standing_Members__c && acc.Vacancies__c==null)
                acc.Vacancies__c = acc.Board_Size__c-acc.Standing_Members__c;
            if(acc.Board_Size__c!=null && acc.Vacancies__c!=null && acc.Board_Size__c >acc.Vacancies__c  && acc.Standing_Members__c==null)
                acc.Standing_Members__c = acc.Board_Size__c-acc.Vacancies__c;
        
            if((acc.Standing_Members__c!=null && acc.Standing_Members__c>1 && acc.Quorum__c==null && ((acc.Standing_Members__c/2) -1)>0)|| (oldAccounMap!=null && oldAccounMap.get(acc.Id).Standing_Members__c != acc.Standing_Members__c && acc.Standing_Members__c!=null && acc.Standing_Members__c>1 && acc.Quorum__c==oldAccounMap.get(acc.Id).Quorum__c && ((acc.Standing_Members__c/2) -1)>0))
                if(Math.round((acc.Standing_Members__c/2) -1)>3){
                    acc.Quorum__c = Math.round((acc.Standing_Members__c/2) -1);
                }else{
                    acc.Quorum__c = 3;
                }
        }
    }
}