force-app/main/default/objects/Account/fields/Automated_Account_Creation__c.field-meta.xml
<CustomField>
    <fullName>Automated_Account_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag will be used to identify the Account that are created manually in salesforce or coming through some other integrated app and based on that duplicate rule will handle the records.</description>
    <label>Automated Account Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <description>Organization accounts with multiple contacts.</description>
    <label>Business Account</label>
</RecordType>

force-app/main/default/objects/Campaign/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investment Activity Programs</relationshipLabel>
    <relationshipName>Investment_Activity_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <inlineHelpText>Business Support - Supporting external organizations and their events.
Networking Events -Track attendees at networking events delivered by EDC.
Business Training-Track attendees at training sessions delivered by EDC.</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Event Support</fullName>
            </value>
            <value>
                <fullName>Networking Events</fullName>
            </value>
            <value>
                <fullName>Business Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Group_Management_Type__c.field-meta.xml
<CustomField>
    <fullName>Group_Management_Type__c</fullName>
    <inlineHelpText>Advisory Group - Groups providing input in Toronto programming and policy making.
Stakeholder Group - Used to manage a list of stakeholders – such as a list of manufacturers that can be consulted on projects.</inlineHelpText>
    <label>Group Management Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advisory Group (Formal)</fullName>
            </value>
            <value>
                <fullName>Distribution List (Informal)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/International_Project_Type__c.field-meta.xml
<CustomField>
    <fullName>International_Project_Type__c</fullName>
    <label>International Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outbound Mission</fullName>
            </value>
            <value>
                <fullName>Inbound Mission</fullName>
            </value>
            <value>
                <fullName>International Relationships</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Program_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Sub_Type__c</fullName>
    <label>Business Training Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Event_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>International Events</fullName>
            </value>
            <value>
                <fullName>Business Start Up</fullName>
            </value>
            <value>
                <fullName>Business Expansion</fullName>
            </value>
            <value>
                <fullName>Online Training</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Projects</fullName>
            </value>
            <value>
                <fullName>Project Support (BIA)</fullName>
            </value>
            <value>
                <fullName>International Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Events.recordType-meta.xml
<RecordType>
    <fullName>Events</fullName>
    <active>true</active>
    <description>For tracking work on external event projects where the City is providing support in organizing.</description>
    <label>Events</label>
</RecordType>

force-app/main/default/objects/Campaign/recordTypes/Group_Management.recordType-meta.xml
<RecordType>
    <fullName>Group_Management</fullName>
    <active>true</active>
    <description>Groups associated with economic development projects, including advisory bodies and stakeholders.</description>
    <label>Group Management</label>
</RecordType>

force-app/main/default/objects/Campaign/recordTypes/Investment_Activity.recordType-meta.xml
<RecordType>
    <fullName>Investment_Activity</fullName>
    <active>true</active>
    <description>Project of Investment Activity type</description>
    <label>Investment Activity</label>
</RecordType>

force-app/main/default/objects/Campaign/recordTypes/Projects.recordType-meta.xml
<RecordType>
    <fullName>Projects</fullName>
    <active>true</active>
    <description>Projects that are being developed and implemented to support the business community.</description>
    <label>Projects</label>
</RecordType>

force-app/main/default/objects/CampaignMember/fields/Member_Role__c.field-meta.xml
<CustomField>
    <fullName>Member_Role__c</fullName>
    <inlineHelpText>Int-Team Memb-CoT staff
Ext-Team Memb-Ext Org
Srvcs Provider- Hired to assist
Attendee-Registers for the event
Invs, Target-Investment attraction project
BIA Member 
Bus Community Member - Part of the project
Dlgte Inb -Dlgte from inb miss</inlineHelpText>
    <label>Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>External - Team Member</fullName>
            </value>
            <value>
                <fullName>Internal - Team Member</fullName>
            </value>
            <value>
                <fullName>Stakeholder - Attendee</fullName>
            </value>
            <value>
                <fullName>Stakeholder - BIA Member</fullName>
            </value>
            <value>
                <fullName>Stakeholder - Business Community</fullName>
            </value>
            <value>
                <fullName>Stakeholder - Delegate (Inbound)</fullName>
            </value>
            <value>
                <fullName>Stakeholder - Delegate (Outbound)</fullName>
            </value>
            <value>
                <fullName>Stakeholder - Investment Target</fullName>
            </value>
            <value>
                <fullName>Stakeholder - Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Survey_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Start_Date__c</fullName>
    <label>Survey Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/Client_FollowUp__c.object-meta.xml
<CustomObject>
    <description>This Object is to capture the Business Outcome response against various objects like Interaction, Online Registration and Project of Event Type.</description>
    <label>Business Outcome Survey</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Business Outcome Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Outcome Surveys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_FollowUp__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Outcome Surveys</relationshipLabel>
    <relationshipName>Account_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contat_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Start Up Event</fullName>
            </value>
            <value>
                <fullName>Online Registration</fullName>
            </value>
            <value>
                <fullName>Consultation Interaction</fullName>
            </value>
            <value>
                <fullName>Company Intelligence Interaction</fullName>
            </value>
            <value>
                <fullName>Business Expansion Event</fullName>
            </value>
            <value>
                <fullName>Online Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Start Up</fullName>
            </value>
            <value>
                <fullName>Business Expansion</fullName>
            </value>
            <value>
                <fullName>Export Development</fullName>
            </value>
            <value>
                <fullName>Mission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Survey_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Start_Date__c</fullName>
    <description>This field will be used as base date to trigger all email alert through workflow.</description>
    <inlineHelpText>This field will be used as base date to trigger all email alert through workflow.</inlineHelpText>
    <label>Survey Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_CampaignTriggerActions.cls
@isTest
private class Test_CampaignTriggerActions{
        
    static testMethod void createTestData(){
        RecordType rt = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
       
        //Below code create list of Account records
        List<Account> accList = new List<Account>(); 
        for(Integer i=0;i<6;i++){
            Account acc = new Account();
            acc.Name='City Of Toronto';
            acc.BillingCountry = 'Canada';
            acc.ShippingCountry = 'Canada';
            acc.RecordTypeId = rt.Id;
            acc.Automated_Account_Creation__c = true;
            accList.add(acc);
        }
        insert accList ;
        
       //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
        for (Integer j=0;j<accList.size();j++) {
            Account acct = accList[j];            
            // For each account just inserted, add contacts
            for (Integer k=0;k<5;k++) {
                conList.add(new Contact(firstname='Test'+k,
                                     lastname='Test'+k,
                                     Email='test@cityoftoronto.com'+k,
                                     AccountId=acct.Id));
            }
        }
       
        // Insert all contacts for all accounts
        insert conList;
        RecordType rtEvent = [select id,Name from RecordType where SobjectType='Campaign' and DeveloperName='Events'];
        RecordType rtGroup = [select id,Name from RecordType where SobjectType='Campaign' and DeveloperName='Group_Management'];
        RecordType rtInvst = [select id,Name from RecordType where SobjectType='Campaign' and DeveloperName='Investment_Activity'];
        RecordType rtPrjct = [select id,Name from RecordType where SobjectType='Campaign' and DeveloperName='Projects'];
        
        //Insert Campaign List
        List<Campaign> campList = new List<Campaign>();
        campList.add(new Campaign(Name='Event Campaign 1',RecordTypeId= rtEvent.Id,Event_Type__c='Business Training',Program_Sub_Type__c='Business Start Up',StartDate = system.today(),EndDate = system.today()+10,Status = 'Completed'));
        campList.add(new Campaign(Name='Event Campaign 1',RecordTypeId= rtEvent.Id,Event_Type__c='Business Training',Program_Sub_Type__c='Business Expansion',StartDate = system.today(),EndDate = system.today()+8));
        campList.add(new Campaign(Name='Event Campaign 2 ',RecordTypeId= rtEvent.Id,Event_Type__c='Event Support'));
        campList.add(new Campaign(Name='Event Campaign 3',RecordTypeId= rtEvent.Id,Event_Type__c='Business Training',Program_Sub_Type__c='International Events'));
        campList.add(new Campaign(Name='Event Campaign 4',RecordTypeId= rtEvent.Id,Event_Type__c='Business Training',Program_Sub_Type__c='Online Training',Status = 'Completed'));
        campList.add(new Campaign(Name='Group Campaign',RecordTypeId= rtGroup.Id,Group_Management_Type__c='Advisory Group (Formal)'));
        campList.add(new Campaign(Name='Invstement Campaign',RecordTypeId= rtInvst.Id,Account__c=accList[0].Id,StartDate = system.today()+2));
        campList.add(new Campaign(Name='Project Campaign',RecordTypeId= rtPrjct.Id,Project_Type__c='International Project',International_Project_Type__c='Outbound Mission',StartDate = system.today()+2,EndDate = system.today()+10,Status = 'Completed'));
        insert campList;
        
         //Business Outcome Survey Sample Records
        List<Client_FollowUp__c> busOutList = new List<Client_FollowUp__c >();
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[1].Id,Survey_Start_Date__c = system.today()+12,Engagement_Type__c='Business Start Up Event'));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[3].Id,Survey_Start_Date__c = system.today()+12));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[2].Id,Survey_Start_Date__c = system.today()+12));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[0].Id,Survey_Start_Date__c = system.today(),Engagement_Type__c='Online Training'));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[3].Id,Survey_Start_Date__c = system.today()+5,Engagement_Type__c='Business Expansion Event;Online Training'));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[4].Id,Survey_Start_Date__c =system.today()));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[5].Id,Survey_Start_Date__c = null,Engagement_Type__c=''));
        insert busOutList;
        
        //Insert Campaign Member List
        List<CampaignMember> campMemList = new List<CampaignMember>();
        campMemList.add(new CampaignMember(CampaignId = campList[0].Id,ContactId = conList[0].Id,Member_Role__c = 'Internal - Team Member'));
        campMemList.add(new CampaignMember(CampaignId = campList[1].Id,ContactId = conList[1].Id,Member_Role__c = 'Internal - Team Member'));
        campMemList.add(new CampaignMember(CampaignId = campList[1].Id,ContactId = conList[2].Id,Member_Role__c = 'Internal - Team Member'));
        campMemList.add(new CampaignMember(CampaignId = campList[0].Id,ContactId = conList[4].Id,Member_Role__c = 'Internal - Team Member'));
        campMemList.add(new CampaignMember(CampaignId = campList[1].Id,ContactId = conList[4].Id,Member_Role__c = 'Internal - Team Member'));
        campMemList.add(new CampaignMember(CampaignId = campList[2].Id,ContactId = conList[2].Id));
        campMemList.add(new CampaignMember(CampaignId = campList[3].Id,ContactId = conList[3].Id));
        campMemList.add(new CampaignMember(CampaignId = campList[4].Id,ContactId = conList[4].Id,Member_Role__c = 'Internal - Team Member',Survey_Start_Date__c=system.today()));
        campMemList.add(new CampaignMember(CampaignId = campList[4].Id,ContactId = conList[5].Id,Member_Role__c = 'Internal - Team Member',Survey_Start_Date__c=system.today()+7));
        campMemList.add(new CampaignMember(CampaignId = campList[5].Id,ContactId = conList[5].Id));
        campMemList.add(new CampaignMember(CampaignId = campList[6].Id,ContactId = conList[1].Id));
        campMemList.add(new CampaignMember(CampaignId = campList[7].Id,ContactId = conList[1].Id));
        
        //insert campMemList;
        try{
            Database.insert(campMemList);
        }
        catch (DMLException e) {
            
        }
        
        campList[1].Event_Type__c = 'Networking Events';
        campList[1].StartDate = system.today();
        campList[1].EndDate = system.today()+10;
        campList[1].Status = 'Completed';
        update campList;
        
    }
    static testMethod void createTestData2(){
        RecordType rt = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
       
        //Below code create list of Account records
        List<Account> accList = new List<Account>(); 
        for(Integer i=0;i<6;i++){
            Account acc = new Account();
            acc.Name='City Of Toronto';
            acc.BillingCountry = 'Canada';
            acc.ShippingCountry = 'Canada';
            acc.RecordTypeId = rt.Id;
            acc.Automated_Account_Creation__c = true;
            accList.add(acc);
        }
        insert accList ;
        
       //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
        for (Integer j=0;j<accList.size();j++) {
            Account acct = accList[j];            
            // For each account just inserted, add contacts
            for (Integer k=0;k<5;k++) {
                conList.add(new Contact(firstname='Test'+k,
                                     lastname='Test'+k,
                                     Email='test@cityoftoronto.com'+k,
                                     AccountId=acct.Id));
            }
        }
       
        // Insert all contacts for all accounts
        insert conList;
        RecordType rtEvent = [select id,Name from RecordType where SobjectType='Campaign' and DeveloperName='Events'];
        RecordType rtGroup = [select id,Name from RecordType where SobjectType='Campaign' and DeveloperName='Group_Management'];
        RecordType rtInvst = [select id,Name from RecordType where SobjectType='Campaign' and DeveloperName='Investment_Activity'];
        RecordType rtPrjct = [select id,Name from RecordType where SobjectType='Campaign' and DeveloperName='Projects'];
        
        //Insert Campaign List
        List<Campaign> campList = new List<Campaign>();
        campList.add(new Campaign(Name='Event Campaign 1',RecordTypeId= rtEvent.Id,Event_Type__c='Business Training',Program_Sub_Type__c='Business Start Up',StartDate = system.today(),EndDate = system.today()+10,Status = 'Completed'));
        campList.add(new Campaign(Name='Event Campaign 1',RecordTypeId= rtEvent.Id,Event_Type__c='Business Training',Program_Sub_Type__c='Business Expansion',StartDate = system.today(),EndDate = system.today()+8));
        campList.add(new Campaign(Name='Event Campaign 2 ',RecordTypeId= rtEvent.Id,Event_Type__c='Event Support'));
        campList.add(new Campaign(Name='Event Campaign 3',RecordTypeId= rtEvent.Id,Event_Type__c='Business Training',Program_Sub_Type__c='International Events'));
        campList.add(new Campaign(Name='Event Campaign 4',RecordTypeId= rtEvent.Id,Event_Type__c='Business Training',Program_Sub_Type__c='Online Training',Status = 'Completed'));
        campList.add(new Campaign(Name='Group Campaign',RecordTypeId= rtGroup.Id,Group_Management_Type__c='Advisory Group (Formal)'));
        campList.add(new Campaign(Name='Invstement Campaign',RecordTypeId= rtInvst.Id,Account__c=accList[0].Id,StartDate = system.today()+2));
        campList.add(new Campaign(Name='Project Campaign',RecordTypeId= rtPrjct.Id,Project_Type__c='International Project',International_Project_Type__c='Outbound Mission',StartDate = system.today()+2,EndDate = system.today()+10,Status = 'Completed'));
        insert campList;
        
        
        //Insert Campaign Member List
        List<CampaignMember> campMemList = new List<CampaignMember>();
        campMemList.add(new CampaignMember(CampaignId = campList[0].Id,ContactId = conList[0].Id,Member_Role__c = 'Internal - Team Member'));
        campMemList.add(new CampaignMember(CampaignId = campList[1].Id,ContactId = conList[1].Id,Member_Role__c = 'Internal - Team Member'));
        campMemList.add(new CampaignMember(CampaignId = campList[2].Id,ContactId = conList[2].Id));
        campMemList.add(new CampaignMember(CampaignId = campList[3].Id,ContactId = conList[3].Id));
        campMemList.add(new CampaignMember(CampaignId = campList[4].Id,ContactId = conList[4].Id,Member_Role__c = 'Internal - Team Member'));
        campMemList.add(new CampaignMember(CampaignId = campList[5].Id,ContactId = conList[5].Id));
        campMemList.add(new CampaignMember(CampaignId = campList[6].Id,ContactId = conList[1].Id));
        
        //insert campMemList;
        
        try{
            Database.insert(campMemList);
        }
        catch (DMLException e) {
            
        }
        campList[1].Event_Type__c = 'Networking Events';
        campList[1].StartDate = system.today();
        campList[1].EndDate = system.today()+10;
        campList[1].Status = 'Completed';
        update campList;
        
    }
}