force-app/main/default/objects/Account/fields/Automated_Account_Creation__c.field-meta.xml
<CustomField>
    <fullName>Automated_Account_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag will be used to identify the Account that are created manually in salesforce or coming through some other integrated app and based on that duplicate rule will handle the records.</description>
    <label>Automated Account Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_Registration_BNR__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Registration_BNR__c</fullName>
    <label>Type of Registration (BNR)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sole Proprietorship</fullName>
            </value>
            <value>
                <fullName>General Partnership</fullName>
            </value>
            <value>
                <fullName>Operating Name of Existing Corporation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <description>Organization accounts with multiple contacts.</description>
    <label>Business Account</label>
</RecordType>

force-app/main/default/objects/Client_FollowUp__c/Client_FollowUp__c.object-meta.xml
<CustomObject>
    <description>This Object is to capture the Business Outcome response against various objects like Interaction, Online Registration and Project of Event Type.</description>
    <label>Business Outcome Survey</label>
    <nameField>
        <displayFormat>BAS-{0000}</displayFormat>
        <label>Business Outcome Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Outcome Surveys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_FollowUp__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Outcome Surveys</relationshipLabel>
    <relationshipName>Account_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contat_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Start Up Event</fullName>
            </value>
            <value>
                <fullName>Online Registration</fullName>
            </value>
            <value>
                <fullName>Consultation Interaction</fullName>
            </value>
            <value>
                <fullName>Company Intelligence Interaction</fullName>
            </value>
            <value>
                <fullName>Business Expansion Event</fullName>
            </value>
            <value>
                <fullName>Online Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Online_Registration__c.field-meta.xml
<CustomField>
    <fullName>Online_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Online Registration</label>
    <referenceTo>Online_Registration__c</referenceTo>
    <relationshipName>Online_Registration_Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_FollowUp__c/fields/Survey_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Start_Date__c</fullName>
    <description>This field will be used as base date to trigger all email alert through workflow.</description>
    <inlineHelpText>This field will be used as base date to trigger all email alert through workflow.</inlineHelpText>
    <label>Survey Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Online_Registration__c/Online_Registration__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s online business registration module - handles data related to business registrations.</description>
    <label>Online Registration</label>
    <nameField>
        <displayFormat>ET-Reg-{000000}</displayFormat>
        <label>ET-Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Online_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Online Registrations</relationshipLabel>
    <relationshipName>Online_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Online_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Online Registrations</relationshipLabel>
    <relationshipName>Online_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Online_Registration__c/fields/Type_of_Registration_BNR__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Registration_BNR__c</fullName>
    <label>Type of Registration (BNR)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sole Proprietorship</fullName>
            </value>
            <value>
                <fullName>General Partnership</fullName>
            </value>
            <value>
                <fullName>Operating Name of Existing Corporation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_OnlineRegTriggerActions.cls
@isTest
public class Test_OnlineRegTriggerActions {
    
    static testMethod void testCreateData() {
       RecordType rt = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
       
        //Below code create list of Account records
        List<Account> accList = new List<Account>(); 
        for(Integer i=0;i<6;i++){
            Account acc = new Account();
            acc.Name='City Of Toronto';
            acc.BillingCountry = 'Canada';
            acc.ShippingCountry = 'Canada';
            acc.RecordTypeId = rt.Id;
            acc.Automated_Account_Creation__c = true;
            accList.add(acc);
        }
        insert accList ;
        
       //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
        for (Integer j=0;j<accList.size();j++) {
            Account acct = accList[j];            
            // For each account just inserted, add contacts
            for (Integer k=0;k<5;k++) {
                conList.add(new Contact(firstname='Test'+k,
                                     lastname='Test'+k,
                                     Email='test@cityoftoronto.com'+k,
                                     AccountId=acct.Id));
            }
        }
        // Insert all contacts for all accounts
        insert conList;
        
        //Below code create list of Online Registration records
        List<Online_Registration__c> onRegList = new List<Online_Registration__c>();
        for (Integer j=0;j<accList.size();j++) {
            Account acct = accList[j];
            Contact con = conList[j];            
            // For each account just inserted, add contacts
            for (Integer k=0;k<5;k++) {
                onRegList.add(new Online_Registration__c(Account__c=acct.Id,Contact__c=con.Id));
            }
        }
        // Insert all Online Registration for all Contact
        insert onRegList;
        onRegList[0].Type_of_Registration_BNR__c = 'General Partnership';
        update onRegList;
    }
    
    static testMethod void testCreateData2() {
       RecordType rt = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
       
        //Below code create list of Account records
        List<Account> accList = new List<Account>(); 
        for(Integer i=0;i<6;i++){
            Account acc = new Account();
            acc.Name='City Of Toronto';
            acc.BillingCountry = 'Canada';
            acc.ShippingCountry = 'Canada';
            acc.RecordTypeId = rt.Id;
            acc.Automated_Account_Creation__c = true;
            accList.add(acc);
        }
        insert accList ;
        
       //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
        for (Integer j=0;j<accList.size();j++) {
            Account acct = accList[j];            
            // For each account just inserted, add contacts
            for (Integer k=0;k<5;k++) {
                conList.add(new Contact(firstname='Test'+k,
                                     lastname='Test'+k,
                                     Email='test@cityoftoronto.com'+k,
                                     AccountId=acct.Id));
            }
        }
        // Insert all contacts for all accounts
        insert conList;
        
        //Business Outcome Survey Sample Records
        List<Client_FollowUp__c> busOutList = new List<Client_FollowUp__c >();
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[0].Id,Survey_Start_Date__c = system.today()+12,Engagement_Type__c='Online Registration'));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[4].Id,Survey_Start_Date__c = system.today()+12,Engagement_Type__c='Business Expansion Event'));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[1].Id,Survey_Start_Date__c = system.today()+12,Engagement_Type__c=null));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[2].Id,Survey_Start_Date__c = system.today()-1));
        busOutList.add(new Client_FollowUp__c(Contact__c=conList[3].Id,Survey_Start_Date__c = null));
        insert busOutList;
        
        //Below code create list of Online Registration records
        List<Online_Registration__c> onRegList = new List<Online_Registration__c>();
        for (Integer j=0;j<accList.size();j++) {
            Account acct = accList[j];
            Contact con = conList[j];            
            // For each account just inserted, add contacts
            for (Integer k=0;k<5;k++) {
                onRegList.add(new Online_Registration__c(Account__c=acct.Id,Contact__c=con.Id));
            }
        }
        // Insert all Online Registration for all Contact
        insert onRegList;
    }
}