force-app/main/default/objects/Account/fields/Number_of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Employees__c</fullName>
    <description>Number of employees the business employs</description>
    <inlineHelpText>Number of employees the business employs</inlineHelpText>
    <label>Number of Employees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/Client_Follow_up__c.object-meta.xml
<CustomObject>
    <description>A follow-up process that re-engages ET clients if they completed a business registration, consultation or training event.</description>
    <label>Client Follow-Up</label>
    <nameField>
        <displayFormat>CLF-{0000}</displayFormat>
        <label>Client Follow-up Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Follow-Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Follow_up__c/fields/Account_ClientFollowUp__c.field-meta.xml
<CustomField>
    <fullName>Account_ClientFollowUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Follow-Ups</relationshipLabel>
    <relationshipName>Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/fields/Consultation_ClientFollowUp__c.field-meta.xml
<CustomField>
    <fullName>Consultation_ClientFollowUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If they have a record that created or modified this object, it would be linked to via this object.</description>
    <label>Consultation ID</label>
    <referenceTo>Consultation__c</referenceTo>
    <relationshipLabel>Client Follow-Ups</relationshipLabel>
    <relationshipName>Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/fields/Contact_ClientFollowUp__c.field-meta.xml
<CustomField>
    <fullName>Contact_ClientFollowUp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Follow-Ups</relationshipLabel>
    <relationshipName>Client_Follow_Ups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/fields/ET_Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Engagement_Type__c</fullName>
    <label>ET Engagement Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/fields/Work_Flow_Session__c.field-meta.xml
<CustomField>
    <fullName>Work_Flow_Session__c</fullName>
    <description>Identifies what record type is driving the work flow.</description>
    <label>Work Flow Session</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultation__c/Consultation__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s client sign-in and follow-up module.</description>
    <label>Consultation</label>
    <nameField>
        <displayFormat>C-{YYYY}-{00000000}</displayFormat>
        <label>Consultation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultation__c/fields/Contact_Consultation__c.field-meta.xml
<CustomField>
    <fullName>Contact_Consultation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consultations</relationshipLabel>
    <relationshipName>Consultations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consultation__c/fields/Number_Of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Employees__c</fullName>
    <label>Number Of Employees</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClientFollowUpsForConsultTests.cls
@isTest
public class ClientFollowUpsForConsultTests {

    static testMethod void validateUpdate() {
        Account a = new Account(Name = 'TestAccountqwert', RecordTypeId='012o0000000Gb8K');
        insert a;
        
        Contact c = new Contact();
        c.Email = 'test@testmailqwerty.com';
        c.AccountId = a.Id;
        c.LastName = 'Testqwerty';
        insert c;
        
        Consultation__c co = new Consultation__c();
        co.Contact_Consultation__c = c.Id;
        insert co;
        
        co.Number_Of_Employees__c = 1;
        update co;
        
        // Retrieve the new Client_Follow_up__c
        /*
        Client_Follow_up__c cf = [SELECT ET_Engagement_Type__c, Work_Flow_Session__c FROM Client_Follow_up__c WHERE Contact_ClientFollowUp__c =: c.Id];
        
        System.assertEquals('Consultation', cf.ET_Engagement_Type__c);
        System.assertEquals('Consultation', cf.Work_Flow_Session__c);
        */
    }
    
    static testMethod void validateInsert1() {
        Account a = new Account(Name = 'TestAccountqwert', RecordTypeId='012o0000000Gb8K');
        insert a;
        
        Contact c = new Contact();
        c.Email = 'test@testmailqwerty.com';
        c.AccountId = a.Id;
        c.LastName = 'Testqwerty';
        insert c;
        
        Client_Follow_up__c cf = new Client_Follow_up__c();
        cf.Contact_ClientFollowUp__c = c.Id;
        cf.Account_ClientFollowUp__c = a.Id;
        insert cf;
        
        Consultation__c co = new Consultation__c();
        co.Contact_Consultation__c = c.Id;
        insert co;
        
        // Retrieve the new Client_Follow_up__c
        /*
        cf = [SELECT Account_ClientFollowUp__c, Consultation_ClientFollowUp__c, Contact_ClientFollowUp__c, ET_Engagement_Type__c, Work_Flow_Session__c FROM Client_Follow_up__c WHERE Contact_ClientFollowUp__c =: c.Id];
        
        System.assertEquals(a.Id, cf.Account_ClientFollowUp__c);
        System.assertEquals(co.Id, cf.Consultation_ClientFollowUp__c);
        System.assertEquals(c.Id, cf.Contact_ClientFollowUp__c);
        System.assertEquals('Consultation', cf.ET_Engagement_Type__c);
        System.assertEquals('Consultation', cf.Work_Flow_Session__c);    
        */
    }
    
    static testMethod void validateInsert2() {
        Account a = new Account(Name = 'TestAccount', RecordTypeId='012o0000000Gb8K');
        insert a;
        
        Contact c = new Contact();
        c.Email = 'test@testmail.com';
        c.AccountId = a.Id;
        c.LastName = 'Test';
        insert c;
        
        Consultation__c co = new Consultation__c();
        co.Contact_Consultation__c = c.Id;
        insert co;
        
        // Retrieve the new Client_Follow_up__c
        /*Client_Follow_up__c cf = [SELECT Account_ClientFollowUp__c, Consultation_ClientFollowUp__c, Contact_ClientFollowUp__c, ET_Engagement_Type__c, Work_Flow_Session__c FROM Client_Follow_up__c WHERE Contact_ClientFollowUp__c =: c.Id];
        
        //System.assertEquals(a.Id, cf.Account_ClientFollowUp__c);
        System.assertEquals(co.Id, cf.Consultation_ClientFollowUp__c);
        System.assertEquals(c.Id, cf.Contact_ClientFollowUp__c);
        System.assertEquals('Consultation', cf.ET_Engagement_Type__c);
        System.assertEquals('Consultation', cf.Work_Flow_Session__c);
        */
    }
}