force-app/main/default/objects/Account/fields/Type_of_Registration_BNR__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Registration_BNR__c</fullName>
    <label>Type of Registration (BNR)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sole Proprietorship</fullName>
            </value>
            <value>
                <fullName>General Partnership</fullName>
            </value>
            <value>
                <fullName>Operating Name of Existing Corporation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/Client_Follow_up__c.object-meta.xml
<CustomObject>
    <description>A follow-up process that re-engages ET clients if they completed a business registration, consultation or training event.</description>
    <label>Client Follow-Up</label>
    <nameField>
        <displayFormat>CLF-{0000}</displayFormat>
        <label>Client Follow-up Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Follow-Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Follow_up__c/fields/Account_ClientFollowUp__c.field-meta.xml
<CustomField>
    <fullName>Account_ClientFollowUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Follow-Ups</relationshipLabel>
    <relationshipName>Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/fields/Contact_ClientFollowUp__c.field-meta.xml
<CustomField>
    <fullName>Contact_ClientFollowUp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Follow-Ups</relationshipLabel>
    <relationshipName>Client_Follow_Ups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/fields/ET_Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>ET_Engagement_Type__c</fullName>
    <label>ET Engagement Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/fields/RegistrationID__c.field-meta.xml
<CustomField>
    <fullName>RegistrationID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If they have a record that created or modified this object, it would be linked to via this object.</description>
    <label>Registration ID</label>
    <referenceTo>Online_Registration__c</referenceTo>
    <relationshipLabel>Client Follow-Ups</relationshipLabel>
    <relationshipName>Client_Follow_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Follow_up__c/fields/Work_Flow_Session__c.field-meta.xml
<CustomField>
    <fullName>Work_Flow_Session__c</fullName>
    <description>Identifies what record type is driving the work flow.</description>
    <label>Work Flow Session</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Online_Registration__c/Online_Registration__c.object-meta.xml
<CustomObject>
    <description>Enterprise Toronto&#39;s online business registration module - handles data related to business registrations.</description>
    <label>Online Registration</label>
    <nameField>
        <displayFormat>ET-Reg-{000000}</displayFormat>
        <label>ET-Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Online_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Online Registrations</relationshipLabel>
    <relationshipName>Online_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Online_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Online Registrations</relationshipLabel>
    <relationshipName>Online_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Online_Registration__c/fields/Type_of_Registration_BNR__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Registration_BNR__c</fullName>
    <label>Type of Registration (BNR)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sole Proprietorship</fullName>
            </value>
            <value>
                <fullName>General Partnership</fullName>
            </value>
            <value>
                <fullName>Operating Name of Existing Corporation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClientFollowUpsForOnlineRegTests.cls
@isTest
public class ClientFollowUpsForOnlineRegTests {
    
    static testMethod void validateUpdate() {
        Account a = new Account(Name = 'TestAccountqwert', RecordTypeId='012o0000000Gb8K');
        insert a;
        
        Contact c = new Contact();
        c.Email = 'test@testmailqwerty.com';
        c.AccountId = a.Id;
        c.LastName = 'Testqwerty';
        insert c;
        
        Online_Registration__c o = new Online_Registration__c();
        o.Account__c = a.Id;
        o.Contact__c = c.Id;
        insert o;
        
        o.Type_of_Registration_BNR__c = 'General Partnership';
        update o;
        
        // Retrieve the new Client_Follow_up__c
        /*
        Client_Follow_up__c cf = [SELECT ET_Engagement_Type__c, Work_Flow_Session__c FROM Client_Follow_up__c WHERE Contact_ClientFollowUp__c =: c.Id];
        
        System.assertEquals('Registration', cf.ET_Engagement_Type__c);
        System.assertEquals('Registration', cf.Work_Flow_Session__c);
        */
    }
    
    static testMethod void validateInsert1() {
        Account a = new Account(Name = 'TestAccountqwert', RecordTypeId='012o0000000Gb8K');
        insert a;
        
        Contact c = new Contact();
        c.Email = 'test@testmailqwerty.com';
        c.AccountId = a.Id;
        c.LastName = 'Testqwerty';
        insert c;
        
        Client_Follow_up__c cf = new Client_Follow_up__c();
        cf.Contact_ClientFollowUp__c = c.Id;
        cf.Account_ClientFollowUp__c = a.Id;
        insert cf;
        
        Online_Registration__c o = new Online_Registration__c();
        o.Account__c = a.Id;
        o.Contact__c = c.Id;
        insert o;
        
        // Retrieve the new Client_Follow_up__c
        /*
        cf = [SELECT Account_ClientFollowUp__c, RegistrationID__c, Contact_ClientFollowUp__c, ET_Engagement_Type__c, Work_Flow_Session__c FROM Client_Follow_up__c WHERE Contact_ClientFollowUp__c =: c.Id];
        
        System.assertEquals(a.Id, cf.Account_ClientFollowUp__c);
        System.assertEquals(o.Id, cf.RegistrationID__c);
        System.assertEquals(c.Id, cf.Contact_ClientFollowUp__c);
        System.assertEquals('Registration', cf.ET_Engagement_Type__c);
        System.assertEquals('Registration', cf.Work_Flow_Session__c);
        */    
    }
    
    static testMethod void validateInsert2() {
        Account a = new Account(Name = 'TestAccountqwert', RecordTypeId='012o0000000Gb8K');
        insert a;
        
        Contact c = new Contact();
        c.Email = 'test@testmailqwerty.com';
        c.AccountId = a.Id;
        c.LastName = 'Testqwerty';
        insert c;
        
        Online_Registration__c o = new Online_Registration__c();
        o.Account__c = a.Id;
        o.Contact__c = c.Id;
        insert o;
        
        // Retrieve the new Client_Follow_up__c
        /*
        Client_Follow_up__c cf = [SELECT Account_ClientFollowUp__c, RegistrationID__c, Contact_ClientFollowUp__c, ET_Engagement_Type__c, Work_Flow_Session__c FROM Client_Follow_up__c WHERE Contact_ClientFollowUp__c =: c.Id];
        
        System.assertEquals(a.Id, cf.Account_ClientFollowUp__c);
        System.assertEquals(o.Id, cf.RegistrationID__c);
        System.assertEquals(c.Id, cf.Contact_ClientFollowUp__c);
        System.assertEquals('Registration', cf.ET_Engagement_Type__c);
        System.assertEquals('Registration', cf.Work_Flow_Session__c);
        */
    }
}