force-app/main/default/objects/Custom_Calendar__c/Custom_Calendar__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture consultation schedule for various ES user on data by date basis with specific working hours.</description>
    <label>Custom Calendar</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Custom Calendar Object</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Calendar</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Calendar__c/fields/Calendar_Date__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Date__c</fullName>
    <label>Calendar Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Custom_Calendar__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Downtown Toronto</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre - 5100 Yonge Street - Main Floor</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre - 150 Borough Drive - Main Floor</fullName>
            </value>
            <value>
                <fullName>Parkdale Innovation Centre (1464 Queen Street West)</fullName>
            </value>
            <value>
                <fullName>WeWork, Downtown Toronto</fullName>
                <isActive>false</isActive>
                <label>WeWork, Downtown Toronto</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Calendar__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Calendar_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture the Interaction with various Account and Contact coming through various different channels in salesforce.</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{00000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Advisor_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which Advisor is conducting consultation</description>
    <inlineHelpText>Which Advisor is conducting consultation</inlineHelpText>
    <label>Advisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Related_Interaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Business_Status__c.field-meta.xml
<CustomField>
    <fullName>Business_Status__c</fullName>
    <description>Business Status</description>
    <inlineHelpText>Business Status</inlineHelpText>
    <label>Business Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
                <default>true</default>
                <label>Existing Client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interaction</relationshipLabel>
    <relationshipName>Interaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender</description>
    <inlineHelpText>Gender</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of consultation</description>
    <inlineHelpText>Location of consultation</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scarborough Civic Centre - 150 Borough Drive - Main Floor</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre - 5100 Yonge Street - Main Floor</fullName>
            </value>
            <value>
                <fullName>Parkdale Innovation Centre (1464 Queen Street West)</fullName>
            </value>
            <value>
                <fullName>Outreach</fullName>
            </value>
            <value>
                <fullName>Downtown Toronto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <description>Meeting Date</description>
    <inlineHelpText>Meeting Date</inlineHelpText>
    <label>Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Meeting_Status__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Status__c</fullName>
    <description>Meeting Status</description>
    <inlineHelpText>Meeting Status</inlineHelpText>
    <label>Meeting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled by Client</fullName>
            </value>
            <value>
                <fullName>Cancelled by Advisor</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Meeting_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Time__c</fullName>
    <description>Meeting Time</description>
    <inlineHelpText>Meeting Time</inlineHelpText>
    <label>Meeting Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>830</fullName>
            </value>
            <value>
                <fullName>900</fullName>
            </value>
            <value>
                <fullName>930</fullName>
            </value>
            <value>
                <fullName>1000</fullName>
            </value>
            <value>
                <fullName>1030</fullName>
            </value>
            <value>
                <fullName>1100</fullName>
            </value>
            <value>
                <fullName>1130</fullName>
            </value>
            <value>
                <fullName>1200</fullName>
            </value>
            <value>
                <fullName>1230</fullName>
            </value>
            <value>
                <fullName>1300</fullName>
            </value>
            <value>
                <fullName>1330</fullName>
            </value>
            <value>
                <fullName>1400</fullName>
            </value>
            <value>
                <fullName>1430</fullName>
            </value>
            <value>
                <fullName>1500</fullName>
            </value>
            <value>
                <fullName>1530</fullName>
            </value>
            <value>
                <fullName>1600</fullName>
            </value>
            <value>
                <fullName>1630</fullName>
            </value>
            <value>
                <fullName>1700</fullName>
            </value>
            <value>
                <fullName>1730</fullName>
            </value>
            <value>
                <fullName>1800</fullName>
            </value>
            <value>
                <fullName>800</fullName>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>12</fullName>
                <isActive>false</isActive>
                <label>12</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>14</fullName>
                <isActive>false</isActive>
                <label>14</label>
            </value>
            <value>
                <fullName>15</fullName>
                <isActive>false</isActive>
                <label>15</label>
            </value>
            <value>
                <fullName>16</fullName>
                <isActive>false</isActive>
                <label>16</label>
            </value>
            <value>
                <fullName>17</fullName>
                <isActive>false</isActive>
                <label>17</label>
            </value>
            <value>
                <fullName>18</fullName>
                <isActive>false</isActive>
                <label>18</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/Leave_Plan__c.object-meta.xml
<CustomObject>
    <description>This custom object is used to capture Leave Plan for various ES Users that will be checked against showing their availability for online consultations.</description>
    <label>Leave Plan</label>
    <nameField>
        <label>Leave Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Plan__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leave_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Consultation_Location__c.field-meta.xml
<CustomField>
    <fullName>Consultation_Location__c</fullName>
    <label>Consultation Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Downtown Toronto</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre - 5100 Yonge Street - Main Floor</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre - 150 Borough Drive - Main Floor</fullName>
            </value>
            <value>
                <fullName>Parkdale Innovation Centre (1464 Queen Street West)</fullName>
                <isActive>false</isActive>
                <label>Parkdale Innovation Centre (1464 Queen Street West)</label>
            </value>
            <value>
                <fullName>WeWork, Downtown Toronto</fullName>
                <isActive>false</isActive>
                <label>WeWork, Downtown Toronto</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>City Hall</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_OnlineConsMeetingSchCompCtrl.cls
@istest(SeeAllData=false)
public class Test_OnlineConsMeetingSchCompCtrl{
    static testmethod void createOnlineSchedulingCmpData(){
        
        Profile pfl = [select id from profile where name='EDC_Admin'];     
        List<User> lstUser = new List<User>();
        lstUser.add(new User(alias = 'asriv', email='16sep.test@gmail.com', emailencodingkey= 'UTF-8', Firstname='Test' ,lastname='User',languagelocalekey='en_US',localesidkey='en_US', profileid = pfl.Id,country='United States',CommunityNickname = 'u1',timezonesidkey='America/Los_Angeles',username='16sep.test@gmail.com', Consultation_Location__c = 'North York Civic Centre - 5100 Yonge Street - Main Floor'));
        lstUser.add(new User(alias = 'jli', email='jlli@toronto.ca.sandplay',emailencodingkey='UTF-8', Firstname='Test', lastname='User2', languagelocalekey='en_US',localesidkey='en_US', profileid = pfl.Id,  country='United States',CommunityNickname = 'u2',timezonesidkey='America/Los_Angeles',username='jlli@toronto.ca.sandplay',Consultation_Location__c = 'North York Civic Centre - 5100 Yonge Street - Main Floor'));
        insert lstUser;
        
        Account acct = new Account(Name='City Of Toronto', RecordTypeId='012o0000000Gb8K');
        insert acct;
        Id acctID = acct.ID;
         
        Contact firstCon = new Contact (LastName='Ray', AccountID = acctID, Email='test@cityoftoronto.com');
        insert firstCon;
        Id contactID = firstCon.ID;
        
        test.starttest();
         
        List<Interaction__c > interList = new List<Interaction__c >();
        interList.add(new Interaction__c(Contact__c = contactID,Account__c = acctID ,Business_Status__c= 'Existing',Gender__c= 'Male'));
        interList.add(new Interaction__c(Contact__c = contactID,Account__c = acctID ,Business_Status__c= 'Existing',Gender__c= 'Male',Advisor_Lookup__c=lstUser[0].Id,Meeting_Status__c='Cancelled by Advisor',Meeting_date__c=Date.newInstance(2025, 11, 11)));
        interList.add(new Interaction__c(Contact__c = contactID,Account__c = acctID ,Business_Status__c= 'Existing',Gender__c= 'Male',Advisor_Lookup__c=lstUser[0].Id,Meeting_Status__c='Requested',Meeting_date__c=Date.newInstance(2025, 11, 11),Meeting_Time__c='1500'));
        insert interList;
        
        Date myDate1 = Date.newInstance(2025,11,11);
        Date myDate2 = Date.newInstance(2025,10,23);
        Date myDate3 = Date.newInstance(2025,10,27);
        Date myDate4 = Date.newInstance(2025,10,28);
        
        List<Custom_Calendar__c> ccList = new List<Custom_Calendar__c>();
        ccList.add(new Custom_Calendar__c(User__c =lstUser[0].Id,Calendar_Date__c =  myDate1, Availability_Start_Time__c = '08 00 AM',Availability_End_Time__c = '06 00 PM', Location__c = 'North York Civic Centre - 5100 Yonge Street - Main Floor'));
        ccList.add(new Custom_Calendar__c(User__c =lstUser[0].Id,Calendar_Date__c =  myDate2, Availability_Start_Time__c = '09 00 AM',Availability_End_Time__c = '03 00 PM', Location__c = 'North York Civic Centre - 5100 Yonge Street - Main Floor'));
        ccList.add(new Custom_Calendar__c(User__c =lstUser[0].Id,Calendar_Date__c =  myDate3, Availability_Start_Time__c = '09 00 AM',Availability_End_Time__c = '03 00 PM', Location__c = 'North York Civic Centre - 5100 Yonge Street - Main Floor'));
        insert ccList;
        system.debug('ccList+++'+ccList);
        
        List<Leave_Plan__c> lstLeavePlan = new List<Leave_Plan__c>();
        lstLeavePlan.add( new Leave_Plan__c(User__c =lstUser[0].Id, Start_Date__c = myDate3 , End_Date__c = myDate4 , Start_Time__c ='09 AM', End_Time__c ='06 PM'));
        insert lstLeavePlan;
        
        List<Event> evList = new List <Event>();
        evList.add(new Event(DurationInMinutes = 60,OwnerId = lstUser[0].id,ActivityDateTime= DateTime.newInstance(2025, 11, 11, 11, 30, 00)));
        evList.add(new Event(DurationInMinutes = 60,OwnerId = lstUser[0].id,ActivityDateTime= DateTime.newInstance(2025, 11, 11, 08, 00, 00)));
        evList.add(new Event(DurationInMinutes = 15,OwnerId = lstUser[0].id,ActivityDateTime= DateTime.newInstance(2025, 11, 11, 13, 00, 00)));
        
        insert evList;
        
        OnlineConsultationMeetingSchCompCtrl Smeet = new OnlineConsultationMeetingSchCompCtrl();
        Smeet.InteractionRecId = interList[0].Id; 
        Smeet.AvailableLocations = null; 
        Smeet.AvailableAdvisors = null; 
        Smeet.AvailableTimeSlots = null; 
        Smeet.AvailableDateSlots = null;
        Smeet.WorkingDates= null;  
        
        Smeet.AvailableLocations();
        Smeet.LocationSelected= 'North York Civic Centre - 5100 Yonge Street - Main Floor';
        
        Smeet.AvailableAdvisors();
        Smeet.AdvisorSelected = lstUser[0].id;
        Smeet.AvailableDays();
        Smeet.DateSelected = '11-11-2025';
        Smeet.AvailableTimeSlots();
        Smeet.TimeSelected = '1000';
        Smeet.scheduleMeeting();
        PageReference pageRef = new PageReference('/apex/OnlineConsultationMeetingScheduler?InteractionId='+interList[0].Id);
        Smeet.PG = pageRef;
        Test.setCurrentPage(pageRef);
        
        OnlineConsultationMeetingSchCompCtrl Smeet1 = new OnlineConsultationMeetingSchCompCtrl();
        Smeet1.InteractionRecId = interList[1].Id; 
         
        Smeet1.AvailableLocations();
        Smeet1.LocationSelected= 'North York Civic Centre - 5100 Yonge Street - Main Floor';
        
        Smeet1.AvailableAdvisors();
        Smeet1.AdvisorSelected = lstUser[0].id;
        Smeet1.AvailableDays();
        Smeet1.DateSelected = '23-10-2025';
        Smeet1.AvailableTimeSlots();
        Smeet1.TimeSelected = '1000';
        Smeet1.scheduleMeeting();
        test.stoptest();

    } 
}