force-app/main/default/objects/Custom_Calendar__c/Custom_Calendar__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture consultation schedule for various ES user on data by date basis with specific working hours.</description>
    <label>Custom Calendar</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Custom Calendar Object</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Calendar</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Calendar__c/fields/Availability_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Availability_End_Time__c</fullName>
    <label>Availability - End Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>08 00 AM</fullName>
            </value>
            <value>
                <fullName>08 30 AM</fullName>
            </value>
            <value>
                <fullName>09 00 AM</fullName>
            </value>
            <value>
                <fullName>09 30 AM</fullName>
            </value>
            <value>
                <fullName>10 00 AM</fullName>
            </value>
            <value>
                <fullName>10 30 AM</fullName>
            </value>
            <value>
                <fullName>11 00 AM</fullName>
            </value>
            <value>
                <fullName>11 30 AM</fullName>
            </value>
            <value>
                <fullName>12 00 PM</fullName>
            </value>
            <value>
                <fullName>12 30 PM</fullName>
            </value>
            <value>
                <fullName>01 00 PM</fullName>
            </value>
            <value>
                <fullName>01 30 PM</fullName>
            </value>
            <value>
                <fullName>02 00 PM</fullName>
            </value>
            <value>
                <fullName>02 30 PM</fullName>
            </value>
            <value>
                <fullName>03 00 PM</fullName>
            </value>
            <value>
                <fullName>03 30 PM</fullName>
            </value>
            <value>
                <fullName>04 00 PM</fullName>
            </value>
            <value>
                <fullName>04 30 PM</fullName>
            </value>
            <value>
                <fullName>05 00 PM</fullName>
            </value>
            <value>
                <fullName>05 30 PM</fullName>
            </value>
            <value>
                <fullName>06 00 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
                <isActive>false</isActive>
                <label>01 PM</label>
            </value>
            <value>
                <fullName>02 PM</fullName>
                <isActive>false</isActive>
                <label>02 PM</label>
            </value>
            <value>
                <fullName>03 PM</fullName>
                <isActive>false</isActive>
                <label>03 PM</label>
            </value>
            <value>
                <fullName>04 PM</fullName>
                <isActive>false</isActive>
                <label>04 PM</label>
            </value>
            <value>
                <fullName>05 PM</fullName>
                <isActive>false</isActive>
                <label>05 PM</label>
            </value>
            <value>
                <fullName>06 PM</fullName>
                <isActive>false</isActive>
                <label>06 PM</label>
            </value>
            <value>
                <fullName>08 AM</fullName>
                <isActive>false</isActive>
                <label>08 AM</label>
            </value>
            <value>
                <fullName>09 AM</fullName>
                <isActive>false</isActive>
                <label>09 AM</label>
            </value>
            <value>
                <fullName>10 AM</fullName>
                <isActive>false</isActive>
                <label>10 AM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Calendar__c/fields/Availability_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Availability_Start_Time__c</fullName>
    <label>Availability - Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>08 00 AM</fullName>
            </value>
            <value>
                <fullName>08 30 AM</fullName>
            </value>
            <value>
                <fullName>09 00 AM</fullName>
            </value>
            <value>
                <fullName>09 30 AM</fullName>
            </value>
            <value>
                <fullName>10 00 AM</fullName>
            </value>
            <value>
                <fullName>10 30 AM</fullName>
            </value>
            <value>
                <fullName>11 00 AM</fullName>
            </value>
            <value>
                <fullName>11 30 AM</fullName>
            </value>
            <value>
                <fullName>12 00 PM</fullName>
            </value>
            <value>
                <fullName>12 30 PM</fullName>
            </value>
            <value>
                <fullName>01 00 PM</fullName>
            </value>
            <value>
                <fullName>01 30 PM</fullName>
            </value>
            <value>
                <fullName>02 00 PM</fullName>
            </value>
            <value>
                <fullName>02 30 PM</fullName>
            </value>
            <value>
                <fullName>03 00 PM</fullName>
            </value>
            <value>
                <fullName>03 30 PM</fullName>
            </value>
            <value>
                <fullName>04 00 PM</fullName>
            </value>
            <value>
                <fullName>04 30 PM</fullName>
            </value>
            <value>
                <fullName>05 00 PM</fullName>
            </value>
            <value>
                <fullName>05 30 PM</fullName>
            </value>
            <value>
                <fullName>06 00 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
                <isActive>false</isActive>
                <label>01 PM</label>
            </value>
            <value>
                <fullName>02 PM</fullName>
                <isActive>false</isActive>
                <label>02 PM</label>
            </value>
            <value>
                <fullName>03 PM</fullName>
                <isActive>false</isActive>
                <label>03 PM</label>
            </value>
            <value>
                <fullName>04 PM</fullName>
                <isActive>false</isActive>
                <label>04 PM</label>
            </value>
            <value>
                <fullName>05 PM</fullName>
                <isActive>false</isActive>
                <label>05 PM</label>
            </value>
            <value>
                <fullName>06 PM</fullName>
                <isActive>false</isActive>
                <label>06 PM</label>
            </value>
            <value>
                <fullName>08 AM</fullName>
                <isActive>false</isActive>
                <label>08 AM</label>
            </value>
            <value>
                <fullName>09 AM</fullName>
                <isActive>false</isActive>
                <label>09 AM</label>
            </value>
            <value>
                <fullName>10 AM</fullName>
                <isActive>false</isActive>
                <label>10 AM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Calendar__c/fields/Calendar_Date__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Date__c</fullName>
    <label>Calendar Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Custom_Calendar__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Downtown Toronto</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre - 5100 Yonge Street - Main Floor</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre - 150 Borough Drive - Main Floor</fullName>
            </value>
            <value>
                <fullName>Parkdale Innovation Centre (1464 Queen Street West)</fullName>
            </value>
            <value>
                <fullName>WeWork, Downtown Toronto</fullName>
                <isActive>false</isActive>
                <label>WeWork, Downtown Toronto</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Calendar__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Calendar_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/Leave_Plan__c.object-meta.xml
<CustomObject>
    <description>This custom object is used to capture Leave Plan for various ES Users that will be checked against showing their availability for online consultations.</description>
    <label>Leave Plan</label>
    <nameField>
        <label>Leave Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Plan__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08 AM</fullName>
            </value>
            <value>
                <fullName>09 AM</fullName>
            </value>
            <value>
                <fullName>10 AM</fullName>
            </value>
            <value>
                <fullName>11 AM</fullName>
            </value>
            <value>
                <fullName>12 PM</fullName>
            </value>
            <value>
                <fullName>01 PM</fullName>
            </value>
            <value>
                <fullName>02 PM</fullName>
            </value>
            <value>
                <fullName>03 PM</fullName>
            </value>
            <value>
                <fullName>04 PM</fullName>
            </value>
            <value>
                <fullName>05 PM</fullName>
            </value>
            <value>
                <fullName>06 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Plan__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leave_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Consultation_Location__c.field-meta.xml
<CustomField>
    <fullName>Consultation_Location__c</fullName>
    <label>Consultation Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Downtown Toronto</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre - 5100 Yonge Street - Main Floor</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre - 150 Borough Drive - Main Floor</fullName>
            </value>
            <value>
                <fullName>Parkdale Innovation Centre (1464 Queen Street West)</fullName>
                <isActive>false</isActive>
                <label>Parkdale Innovation Centre (1464 Queen Street West)</label>
            </value>
            <value>
                <fullName>WeWork, Downtown Toronto</fullName>
                <isActive>false</isActive>
                <label>WeWork, Downtown Toronto</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>City Hall</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre</fullName>
            </value>
            <value>
                <fullName>Scarborough Civic Centre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_LeavePlanTrigger.cls
@isTest
private class Test_LeavePlanTrigger{
        
    static testMethod void createTestData(){
    
        Profile pfl = [select id from profile where name='EDC_Admin'];     
        List<User> lstUser = new List<User>();
        
        Date myDate1 = Date.newInstance(2020,11,11);
        Date myDate2 = Date.newInstance(2020,10,23);
        Date myDate3 = Date.newInstance(2020,10,27);
        Date myDate4 = Date.newInstance(2020,10,28);
         
        lstUser.add(new User(alias = 'tusr', email='16sep.test@gmail.com', emailencodingkey= 'UTF-8', Firstname='Test' ,lastname='User',languagelocalekey='en_US',localesidkey='en_US', profileid = pfl.Id,country='United States',CommunityNickname = 'u1',timezonesidkey='America/Los_Angeles',username='16sep.test@gmail.com', Consultation_Location__c = 'North York Civic Centre - 5100 Yonge Street - Main Floor'));
        lstUser.add(new User(alias = 'susr', email='jlli@toronto.ca.sandplay',emailencodingkey='UTF-8', Firstname='Sample', lastname='User', languagelocalekey='en_US',localesidkey='en_US', profileid = pfl.Id,  country='United States',CommunityNickname = 'u2',timezonesidkey='America/Los_Angeles',username='jlli@toronto.ca.sandplay',Consultation_Location__c = 'North York Civic Centre - 5100 Yonge Street - Main Floor'));
        insert lstUser;
        
        List<Leave_Plan__c> lstLeavePlan = new List<Leave_Plan__c>();
        
        List<Custom_Calendar__c> ccList = new List<Custom_Calendar__c>();
        ccList.add(new Custom_Calendar__c(User__c =lstUser[0].Id,Calendar_Date__c =  myDate1, Availability_Start_Time__c = '09 00 AM',Availability_End_Time__c = '03 00 PM', Location__c = 'North York Civic Centre - 5100 Yonge Street - Main Floor'));
        ccList.add(new Custom_Calendar__c(User__c =lstUser[0].Id,Calendar_Date__c =  myDate2, Availability_Start_Time__c = '09 00 AM',Availability_End_Time__c = '03 00 PM', Location__c = 'North York Civic Centre - 5100 Yonge Street - Main Floor'));
        ccList.add(new Custom_Calendar__c(User__c =lstUser[0].Id,Calendar_Date__c =  myDate3, Availability_Start_Time__c = '09 00 AM',Availability_End_Time__c = '03 00 PM', Location__c = 'North York Civic Centre - 5100 Yonge Street - Main Floor'));
        ccList.add(new Custom_Calendar__c(User__c =lstUser[0].Id,Calendar_Date__c =  myDate4, Availability_Start_Time__c = '09 00 AM',Availability_End_Time__c = '03 00 PM', Location__c = 'North York Civic Centre - 5100 Yonge Street - Main Floor'));
        ccList.add(new Custom_Calendar__c(User__c =lstUser[1].Id,Calendar_Date__c =  myDate1, Availability_Start_Time__c = '09 00 AM',Availability_End_Time__c = '03 00 PM', Location__c = 'North York Civic Centre - 5100 Yonge Street - Main Floor'));
        insert ccList;
        
        lstLeavePlan.add( new Leave_Plan__c(User__c =lstUser[0].Id, Start_Date__c = myDate3 , End_Date__c = myDate3 , Start_Time__c ='09 AM', End_Time__c ='06 PM'));
        lstLeavePlan.add( new Leave_Plan__c(User__c =lstUser[0].Id, Start_Date__c = myDate4 , End_Date__c = myDate4 , Start_Time__c ='09 AM', End_Time__c ='06 PM'));
        
        insert lstLeavePlan;
        
        delete lstLeavePlan[1];
    }
}