force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture the Interaction with various Account and Contact coming through various different channels in salesforce.</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{00000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Advisor_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which Advisor is conducting consultation</description>
    <inlineHelpText>Which Advisor is conducting consultation</inlineHelpText>
    <label>Advisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Related_Interaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of consultation</description>
    <inlineHelpText>Location of consultation</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scarborough Civic Centre - 150 Borough Drive - Main Floor</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre - 5100 Yonge Street - Main Floor</fullName>
            </value>
            <value>
                <fullName>Parkdale Innovation Centre (1464 Queen Street West)</fullName>
            </value>
            <value>
                <fullName>Outreach</fullName>
            </value>
            <value>
                <fullName>Downtown Toronto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Meeting_Status__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Status__c</fullName>
    <description>Meeting Status</description>
    <inlineHelpText>Meeting Status</inlineHelpText>
    <label>Meeting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled by Client</fullName>
            </value>
            <value>
                <fullName>Cancelled by Advisor</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Meeting_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Time__c</fullName>
    <description>Meeting Time</description>
    <inlineHelpText>Meeting Time</inlineHelpText>
    <label>Meeting Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>830</fullName>
            </value>
            <value>
                <fullName>900</fullName>
            </value>
            <value>
                <fullName>930</fullName>
            </value>
            <value>
                <fullName>1000</fullName>
            </value>
            <value>
                <fullName>1030</fullName>
            </value>
            <value>
                <fullName>1100</fullName>
            </value>
            <value>
                <fullName>1130</fullName>
            </value>
            <value>
                <fullName>1200</fullName>
            </value>
            <value>
                <fullName>1230</fullName>
            </value>
            <value>
                <fullName>1300</fullName>
            </value>
            <value>
                <fullName>1330</fullName>
            </value>
            <value>
                <fullName>1400</fullName>
            </value>
            <value>
                <fullName>1430</fullName>
            </value>
            <value>
                <fullName>1500</fullName>
            </value>
            <value>
                <fullName>1530</fullName>
            </value>
            <value>
                <fullName>1600</fullName>
            </value>
            <value>
                <fullName>1630</fullName>
            </value>
            <value>
                <fullName>1700</fullName>
            </value>
            <value>
                <fullName>1730</fullName>
            </value>
            <value>
                <fullName>1800</fullName>
            </value>
            <value>
                <fullName>800</fullName>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>12</fullName>
                <isActive>false</isActive>
                <label>12</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>14</fullName>
                <isActive>false</isActive>
                <label>14</label>
            </value>
            <value>
                <fullName>15</fullName>
                <isActive>false</isActive>
                <label>15</label>
            </value>
            <value>
                <fullName>16</fullName>
                <isActive>false</isActive>
                <label>16</label>
            </value>
            <value>
                <fullName>17</fullName>
                <isActive>false</isActive>
                <label>17</label>
            </value>
            <value>
                <fullName>18</fullName>
                <isActive>false</isActive>
                <label>18</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OnlineConsultationMeetingSchedulerCtrl.cls
public class OnlineConsultationMeetingSchedulerCtrl
{
    public boolean ShowRegisConfirmPnlId{get;set;}
    public boolean ShowMeetingConfimedMsg{get;set;}
    public boolean ShowCalendar{get;set;}
    public boolean ShowErrMsg{get;set;}
    public String  InteractionId;
    public String  FollowUpIntId;
    
    public OnlineConsultationMeetingSchedulerCtrl()
    {  
        ShowRegisConfirmPnlId = false;
        ShowMeetingConfimedMsg = false;
        ShowCalendar = false;
        ShowErrMsg= false;
        InteractionId = ApexPages.currentPage().getParameters().get('InteractionId');
        FollowUpIntId = ApexPages.currentPage().getParameters().get('FollowRecId');
        
        Interaction__c intRec = new Interaction__c();
        Interaction__c followUpRec = new Interaction__c();
        
        system.debug('InteractionId ++++'+InteractionId);
        if(InteractionId != '' && InteractionId!=null){
            try{
                intRec = [SELECT Id, Name, Account__c FROM Interaction__c WHERE ID = :InteractionId AND ((Meeting_Status__c=null and Location__c =null and Meeting_Time__c = null and Advisor_Lookup__c=null) OR (Meeting_Status__c= 'Cancelled by Advisor' OR Meeting_Status__c= 'Cancelled by Client'))];
                } catch(Exception ex){
                intRec = null;
            }
            System.debug('intRec +++'+intRec);
            if(intRec != null){
                ShowRegisConfirmPnlId = true;
                ShowCalendar = true;
            }
            else {
                ShowErrMsg = true;
                ShowRegisConfirmPnlId = false;
                ShowCalendar = false;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.info, 'Incorrect  Record ID Specified. Please contact City staff and share the error with URL at edc_toronto@toronto.ca '));
            }
        }
        if(InteractionId == ''){
             ShowErrMsg = true;
             ShowRegisConfirmPnlId = false;
             ShowCalendar = false;
             ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.info, 'No Record ID Specified. Please Check the URL'));
        }
        if(FollowUpIntId != '' && FollowUpIntId !=null){
            try{
                followUpRec = [SELECT Id, Name, Account__c FROM Interaction__c WHERE ID = :FollowUpIntId AND Meeting_Status__c=:'Requested'];
                } catch(Exception ex){
                followUpRec = null;
            }
            if(followUpRec != null){
                ShowMeetingConfimedMsg = true;
                ShowCalendar = false;
                ShowRegisConfirmPnlId =  false;
            }
            else
            {
                ShowErrMsg = true;
                ShowMeetingConfimedMsg = false;
                ShowCalendar = false;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.info, 'Incorrect  Record ID Specified. Please contact City staff and share the error with URL at edc_toronto@toronto.ca '));
            }
        }
        if(ApexPages.currentPage().getParameters().get('FollowRecId') == ''){
            ShowErrMsg = true;
            ShowMeetingConfimedMsg = false;
            ShowCalendar = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.info, 'No Record ID Specified. Please Check the URL'));
        }
        
    }
}