force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture the Interaction with various Account and Contact coming through various different channels in salesforce.</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{00000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <description>Which Advisor is conducting consultation</description>
    <inlineHelpText>Which Advisor is conducting consultation</inlineHelpText>
    <label>Advisor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vikas Jain</fullName>
            </value>
            <value>
                <fullName>Sandi Koitsis-Zigomanis</fullName>
            </value>
            <value>
                <fullName>Jason Li</fullName>
            </value>
            <value>
                <fullName>Karen Keskull</fullName>
            </value>
            <value>
                <fullName>Chris Rickett</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Business_Status__c.field-meta.xml
<CustomField>
    <fullName>Business_Status__c</fullName>
    <description>Business Status</description>
    <inlineHelpText>Business Status</inlineHelpText>
    <label>Business Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
                <default>true</default>
                <label>Existing Client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interaction</relationshipLabel>
    <relationshipName>Interaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Date_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Contact__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The date the interaction took place</description>
    <inlineHelpText>The date the interaction took place</inlineHelpText>
    <label>Date of Contact</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Follow_Up_Consultation_Type__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Consultation_Type__c</fullName>
    <description>What type of follow up is required</description>
    <inlineHelpText>What type of follow up is required</inlineHelpText>
    <label>Follow-Up Consultation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Follow-Up for Walk in clients</fullName>
            </value>
            <value>
                <fullName>Follow-Up for Online clients</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender</description>
    <inlineHelpText>Gender</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of consultation</description>
    <inlineHelpText>Location of consultation</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scarborough Civic Centre - 150 Borough Drive - Main Floor</fullName>
            </value>
            <value>
                <fullName>North York Civic Centre - 5100 Yonge Street - Main Floor</fullName>
            </value>
            <value>
                <fullName>Parkdale Innovation Centre (1464 Queen Street West)</fullName>
            </value>
            <value>
                <fullName>Outreach</fullName>
            </value>
            <value>
                <fullName>Downtown Toronto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <description>Meeting Date</description>
    <inlineHelpText>Meeting Date</inlineHelpText>
    <label>Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Meeting_Status__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Status__c</fullName>
    <description>Meeting Status</description>
    <inlineHelpText>Meeting Status</inlineHelpText>
    <label>Meeting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled by Client</fullName>
            </value>
            <value>
                <fullName>Cancelled by Advisor</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Meeting_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Time__c</fullName>
    <description>Meeting Time</description>
    <inlineHelpText>Meeting Time</inlineHelpText>
    <label>Meeting Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>830</fullName>
            </value>
            <value>
                <fullName>900</fullName>
            </value>
            <value>
                <fullName>930</fullName>
            </value>
            <value>
                <fullName>1000</fullName>
            </value>
            <value>
                <fullName>1030</fullName>
            </value>
            <value>
                <fullName>1100</fullName>
            </value>
            <value>
                <fullName>1130</fullName>
            </value>
            <value>
                <fullName>1200</fullName>
            </value>
            <value>
                <fullName>1230</fullName>
            </value>
            <value>
                <fullName>1300</fullName>
            </value>
            <value>
                <fullName>1330</fullName>
            </value>
            <value>
                <fullName>1400</fullName>
            </value>
            <value>
                <fullName>1430</fullName>
            </value>
            <value>
                <fullName>1500</fullName>
            </value>
            <value>
                <fullName>1530</fullName>
            </value>
            <value>
                <fullName>1600</fullName>
            </value>
            <value>
                <fullName>1630</fullName>
            </value>
            <value>
                <fullName>1700</fullName>
            </value>
            <value>
                <fullName>1730</fullName>
            </value>
            <value>
                <fullName>1800</fullName>
            </value>
            <value>
                <fullName>800</fullName>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>12</fullName>
                <isActive>false</isActive>
                <label>12</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>14</fullName>
                <isActive>false</isActive>
                <label>14</label>
            </value>
            <value>
                <fullName>15</fullName>
                <isActive>false</isActive>
                <label>15</label>
            </value>
            <value>
                <fullName>16</fullName>
                <isActive>false</isActive>
                <label>16</label>
            </value>
            <value>
                <fullName>17</fullName>
                <isActive>false</isActive>
                <label>17</label>
            </value>
            <value>
                <fullName>18</fullName>
                <isActive>false</isActive>
                <label>18</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/recordTypes/Consultation.recordType-meta.xml
<RecordType>
    <fullName>Consultation</fullName>
    <active>true</active>
    <description>Interaction for providing new Business Consultation</description>
    <label>Consultation</label>
</RecordType>

force-app/main/default/objects/Related_Interaction_Contact__c/Related_Interaction_Contact__c.object-meta.xml
<CustomObject>
    <description>This Object will be used to hold many to many relation between Contact and Interaction.</description>
    <label>Related Interaction Contact</label>
    <nameField>
        <displayFormat>CIN-{0000}</displayFormat>
        <label>Related Interaction Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Interaction Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Interaction_Contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>if(NOT(Interaction__r.Account__r.IsPersonAccount),Interaction__r.Account__r.Name,Interaction__r.Contact__r.FirstName+&#39; &#39;+Interaction__r.Contact__r.LastName )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Interaction_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Interactions</relationshipLabel>
    <relationshipName>Related_Interaction_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Interaction_Contact__c/fields/Date_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Contact__c</fullName>
    <label>Date of Contact</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Related_Interaction_Contact__c/fields/Interaction__c.field-meta.xml
<CustomField>
    <fullName>Interaction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Interaction</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Can not be associated with Interaction linked to Person Account</errorMessage>
        <filterItems>
            <field>Interaction__c.Account__r.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Interaction__c</referenceTo>
    <relationshipLabel>Related Interaction Contacts</relationshipLabel>
    <relationshipName>Related_Interaction_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_RelatedInteractionContactTrigger.cls
@isTest
private class Test_RelatedInteractionContactTrigger{
        
     static testMethod void createTestData(){
     
     RecordType rt = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
        
        //Below code create list of Account records
        List<Account> accList = new List<Account>(); 
        for(Integer i=0;i<6;i++){
            Account acc = new Account();
            acc.Name='City Of Toronto';
            acc.BillingCountry = 'Canada';
            acc.ShippingCountry = 'Canada';
            acc.RecordTypeId = rt.Id;
            accList.add(acc);
        }
        
        insert accList ;
        
       //Below code create list of Contact records
        List<Contact> conList = new List<Contact>();
        for (Integer j=0;j<accList.size();j++) {
            Account acct = accList[j];            
            // For each account just inserted, add contacts
            for (Integer k=0;k<5;k++) {
                conList.add(new Contact(firstname='Test'+k,
                                     lastname='Test'+k,
                                     Email='test@cityoftoronto.com'+k,
                                     AccountId=acct.Id));
            }
        }
        // Insert all contacts for all accounts
        insert conList;
        
        //Below code create list of Interaction records
        Date myDate = Date.newInstance(2015,10,17);
        List<Interaction__c > interList = new List<Interaction__c >();
        for (Integer k=0;k<4;k++) {
            interList.add(new Interaction__c (Contact__c = conList[0].Id,
                                              Account__c = accList[0].Id,
                                              Business_Status__c= 'Existing',
                                              Gender__c= 'Male',
                                              Meeting_Date__c = myDate, 
                                              Advisor__c = 'Vikas Jain',
                                              Meeting_Status__c ='Confirmed', 
                                              Meeting_Time__c ='1000',
                                              Location__c = 'City Hall'));
        }                                 
        insert interList;
        
        List<Related_Interaction_Contact__c > interContList = new List<Related_Interaction_Contact__c >();
        for (Integer k=0;k<4;k++) {
            interContList.add(new Related_Interaction_Contact__c (Contact__c = conList[0].Id,
                                              Interaction__c = interList[0].Id
                                              ));
        }                                 
         try{
            insert interContList;
         }
         catch (DMLException e) {
            
        }
    }
    static testMethod void createTestData2(){
        
        RecordType rtBus = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
        RecordType rtPerson = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='PersonAccount'];
        
        Id RecordTypeIdConsInteraction = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Consultation').getRecordTypeId();
        Id RecordTypeIdComIntInteraction = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Company Intelligence').getRecordTypeId();
        //Below code create list of Account records Business and Person Account
        List<Account> accList = new List<Account>(); 
        
        accList.add(new Account(Name='City Of Toronto',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id));
        accList.add(new Account(FirstName='City Of Toronto ',LastName='Person Account', PersonEmail = 'city11@toronto.ca',PersonMailingCountry = 'Canada', PersonOtherCountry = 'Canada',RecordTypeId = rtPerson.Id));
        insert accList ;
        
        List<Interaction__c > interList = new List<Interaction__c >();
        interList.add(new Interaction__c(Contact__c = accList[0].Id, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdConsInteraction,Follow_Up_Consultation_Type__c ='Follow-Up for Online clients',Location__c='City Hall', Meeting_Status__c = 'Requested',Date_of_Contact__c = date.today(),Advisor__c= UserInfo.getUserId() ));
        interList.add(new Interaction__c(Contact__c = accList[1].Id, Account__c = accList[1].Id,RecordTypeId=RecordTypeIdConsInteraction));
        interList.add(new Interaction__c(Contact__c = accList[0].Id, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdComIntInteraction,Purpose_of_the_Interaction__c = 'Biz Development - Expansion Assistance'));
        interList.add(new Interaction__c(Contact__c = accList[1].Id, Account__c = accList[1].Id,RecordTypeId=RecordTypeIdComIntInteraction,Purpose_of_the_Interaction__c = 'Biz Development - Expansion Assistance'));
        
        Account accnt = new Account();
        accnt.Name='City Of Toronto Sample 12';
        accnt.BillingCountry = 'Canada';
        accnt.ShippingCountry = 'Canada';
        accnt.RecordTypeId = rtBus.Id;
        accnt.Automated_Account_Creation__c = true;
        insert accnt;
        
        Contact consample = new Contact();
        consample.firstname='Test 10';
        consample.lastname='Test 12';
        consample.Email='test@cityoftoronto12.com';
        consample.AccountId=accnt.Id;
        insert consample;
        
        try{
            insert interList;
            List<Related_Interaction_Contact__c > interContList = new List<Related_Interaction_Contact__c >();
            for (Integer k=0;k<4;k++) {
            interContList.add(new Related_Interaction_Contact__c (Contact__c = accList[0].Id, 
                                              Interaction__c = interList[0].Id
                                              ));
            } 
            interContList.add(new Related_Interaction_Contact__c (Contact__c = consample.Id,
                                              Interaction__c = interList[0].Id
                                              ));  
            insert interContList;
        }
        catch (DMLException e) {
            
        }
    }
    static testMethod void createTestData3(){
       
        RecordType rtBus = [select id,Name from RecordType where SobjectType='Account' and DeveloperName='Business_Account'];
        
        Id RecordTypeIdConsInteraction = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Consultation').getRecordTypeId();
       
       //Below code create list of Account records Business and Person Account
        List<Account> accList = new List<Account>(); 
        
        accList.add(new Account(Name='City Of Toronto 1',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client'));
        accList.add(new Account(Name='City Of Toronto 2',BillingCountry = 'Canada', ShippingCountry = 'Canada',RecordTypeId = rtBus.Id,Account_Type__c ='Business Client'));
        insert accList ;
        
        List<Contact> conList = new List<Contact>();
        conList.add(new Contact(firstname='Test'+7,lastname='Test'+7,Email='test@cityoftoronto.com'+7, AccountId=accList[0].Id));   
        conList.add(new Contact(firstname='Test'+7,lastname='Test'+7,Email='test@cityoftoronto.com'+8, AccountId=accList[1].Id));   
        insert conList ;
        
        List<Interaction__c > interList = new List<Interaction__c>();
        interList.add(new Interaction__c(Contact__c = conList[0].Id, Account__c = accList[0].Id,RecordTypeId=RecordTypeIdConsInteraction));
        
        try{
            database.Insert(interList);
             Related_Interaction_Contact__c relInt = new Related_Interaction_Contact__c ();
             relInt.Contact__c = conList[1].Id;
             relInt.Interaction__c= interList[0].Id;
             insert relInt;
        }
        catch (DMLException e) {
        }
    }        
}